/** Browser-only behavior checks for the Cedar & Thread storefront. The grader supplies a cart-only storage fixture. */
export function ecommerceAssessmentBody(assessmentId: string): string | undefined {
  if (!/^shop-.*-(guided-[12]|apply|debug|combine)$/.test(assessmentId)) return undefined;
  const topic = assessmentId.replace(/-(guided-[12]|apply|debug|combine)$/, '');
  const full = !(assessmentId.endsWith('-guided-1') || assessmentId.endsWith('-apply'));
  return String.raw`
const assert = (condition, message) => { if (!condition) throw new Error(message); };
const wait = ms => new Promise(resolve => setTimeout(resolve, ms));
const eventually = async (check, message) => { for (let n=0;n<100;n+=1) { if (check()) return; await wait(3); } throw new Error(message); };
const $ = selector => document.querySelector(selector); const text = node => node?.textContent || '';
const click = selector => { const node=$(selector); assert(node, 'Missing '+selector); node.click(); };
if (${JSON.stringify(topic)} === 'shop-scope-catalog-and-originality') {
  assert($('#shop-scope') && /browse/i.test(text($('#shop-scope'))) && /detail/i.test(text($('#shop-scope'))) && /cart/i.test(text($('#shop-scope'))) && /checkout/i.test(text($('#shop-scope'))), 'Describe browse, detail, cart and checkout in #shop-scope.');
  assert($('#catalog-identity') && /Cedar.{0,8}Thread/i.test(text($('#catalog-identity'))) && /original/i.test(text($('#originality-boundary'))), 'Name an original Cedar & Thread catalog and its fixture boundary.');
  ${full ? "assert($('#flow-map') && /catalog/i.test(text($('#flow-map'))) && /detail/i.test(text($('#flow-map'))) && /cart/i.test(text($('#flow-map'))) && /checkout/i.test(text($('#flow-map'))), 'Map catalog, detail, cart and checkout in #flow-map.'); assert($('#scope-exclusions') && /real payment|personal data|account/i.test(text($('#scope-exclusions'))) && !/amazon/i.test(text(document.body)), 'State the excluded real-payment, personal-data and account scope without marketplace branding.');" : ''}
} else if (${JSON.stringify(topic)} === 'shop-stack-data-and-route-plan') {
  assert($('#shop-stack-plan') && /plain javascript/i.test(text($('#shop-stack-plan'))) && /vite react/i.test(text($('#shop-stack-plan'))) && /full.stack/i.test(text($('#shop-stack-plan'))) && /vanilla/i.test(text($('#shop-stack-plan'))), 'Compare Plain JavaScript, Vite React and a full-stack framework, then choose vanilla modules.'); assert($('#data-plan') && /local product fixture/i.test(text($('#data-plan'))), 'Describe a local product fixture.');
  ${full ? "assert($('#route-plan') && /#\/catalog/.test(text($('#route-plan'))) && /#\/product\/:id/.test(text($('#route-plan'))) && /#\/cart/.test(text($('#route-plan'))) && /#\/checkout/.test(text($('#route-plan'))), 'List the four hash routes.'); assert($('#boundary-plan') && /database/i.test(text($('#boundary-plan'))) && /payment/i.test(text($('#boundary-plan'))) && $('#file-plan') && /cartStorage\.js/i.test(text($('#file-plan'))), 'Separate local browser work from server responsibilities and name the planned files.');" : ''}
} else {
  assert($('#shop-app') && $('#shop-nav') && $('#catalog-grid'), 'Render the Cedar & Thread app, navigation and #catalog-grid.');
  await eventually(() => document.querySelectorAll('[data-product-id]').length >= 4, 'Render four deterministic original products.');
  if (${JSON.stringify(topic)} === 'shop-setup-navigation-and-catalog') { assert($('[data-route="catalog"]'), 'Provide a catalog hash-navigation link.'); ${full ? "assert(Array.from(document.querySelectorAll('[data-product-id]')).every(card => /\$/.test(text(card))), 'Each catalog card needs a visible local price.');" : ''} }
  else if (${JSON.stringify(topic)} === 'shop-product-details-and-client-server-boundaries') { location.hash='#/product/ember-mug'; await eventually(() => $('[data-product-detail="ember-mug"]'), 'A valid product hash must render Ember Mug details.'); ${full ? "location.hash='#/product/nope'; await eventually(() => $('#product-not-found'), 'An unknown product hash needs #product-not-found.');" : ''} }
  else if (${JSON.stringify(topic)} === 'shop-product-search-and-filters') { assert($('#shop-search') && $('#category-filter') && $('#price-filter') && $('#empty-results') && $('#results-status'), 'Provide search, category/price filters and visible result feedback.'); $('#shop-search').value='not-a-product'; $('#shop-search').dispatchEvent(new Event('input',{bubbles:true})); await eventually(() => /no products/i.test(text($('#empty-results'))), 'A search with no result needs a clear empty state.'); ${full ? "$('#shop-search').value=''; $('#shop-search').dispatchEvent(new Event('input',{bubbles:true})); $('#category-filter').value='paper'; $('#category-filter').dispatchEvent(new Event('change',{bubbles:true})); await eventually(() => document.querySelectorAll('[data-product-id]').length===1 && /Field Notebook/.test(text($('#catalog-grid'))), 'Category filtering must derive a predictable result.');" : ''} }
  else if (${JSON.stringify(topic)} === 'shop-cart-quantity-and-persistence') { assert($('[data-cart-add]') && $('#cart-list') && $('#cart-total') && $('#cart-status'), 'Provide add-to-cart controls and cart feedback.'); click('[data-cart-add="ember-mug"]'); await eventually(() => /Ember Mug/.test(text($('#cart-list'))), 'Adding a product must show it in the cart.'); ${full ? "const quantity=$('[data-cart-quantity=\"ember-mug\"]'); assert(quantity, 'Expose an ID-based quantity input.'); quantity.value='2'; quantity.dispatchEvent(new Event('change',{bubbles:true})); await eventually(() => /2/.test(text($('#cart-count'))) && globalThis.__gradeStorage?.value?.includes('ember-mug'), 'Quantity updates must persist the cart envelope.'); if (/malformed|invalid-shape|duplicate-product|read-failure/.test(globalThis.__gradeStorage?.mode||'')) assert($('#recover-cart') || $('#retry-cart'), 'Invalid cart storage requires explicit recovery or retry.');" : ''} }
  else if (${JSON.stringify(topic)} === 'shop-checkout-validation-and-failure-states') { assert($('#checkout-form') && $('#checkout-delivery') && $('#checkout-consent') && $('#checkout-outcome') && $('#checkout-status') && !document.querySelector('input[type=password],input[name*=card i],input[name*=email i],input[name*=name i],textarea'), 'Use the non-personal simulated checkout controls only.'); click('#checkout-submit'); await eventually(() => /choose|simulation/i.test(text($('#checkout-status'))), 'Checkout validates its fictional delivery and simulation consent.'); ${full ? "$('#checkout-delivery').value='pickup-demo'; $('#checkout-consent').checked=true; $('#checkout-outcome').value='decline'; click('#checkout-submit'); await eventually(() => /declined/i.test(text($('#checkout-status'))), 'A declined simulation must be visible and recoverable.');" : ''} }
  else if (${JSON.stringify(topic)} === 'shop-testing-export-and-handoff') { assert($('#run-shop-smoke') && $('#shop-smoke-status'), 'Provide a real #run-shop-smoke control and status.'); click('#run-shop-smoke'); await eventually(() => /passed|failed/i.test(text($('#shop-smoke-status'))), 'Smoke must report an observed result.'); assert(/passed/i.test(text($('#shop-smoke-status'))), 'Reference smoke must pass.'); ${full ? "assert($('#shop-export-handoff') && /python -m http.server/i.test(text($('#shop-export-handoff'))) && /export again/i.test(text($('#shop-export-handoff'))), 'Give static-server and re-export handoff guidance.'); const wish=$('[data-wishlist-toggle]'); assert(wish && $('#wishlist-count') && $('#wishlist-status'), 'Combine milestone requires an in-memory wishlist.'); const before=text($('#wishlist-count')); wish.click(); await eventually(() => text($('#wishlist-count')) !== before, 'Wishlist toggle must change its count.');" : ''} }
}
`;
}

export const isEcommerceAssessment = (id: string) => /^shop-.*-(guided-[12]|apply|debug|combine)$/.test(id);
export const ecommerceAssessmentNeedsStorage = (id: string) => /^shop-(cart-quantity-and-persistence|checkout-validation-and-failure-states|testing-export-and-handoff)-/.test(id);
export default ecommerceAssessmentBody;
