/** Browser-only DOM checks for the React Task Dashboard. The grader supplies storage fixtures. */
export function reactAssessmentBody(assessmentId: string): string | undefined {
  if (!/-(guided-[12]|apply|debug|combine)$/.test(assessmentId)) return undefined;
  const topic = assessmentId.replace(/-(guided-[12]|apply|debug|combine)$/, '');
  if (!topic.startsWith('react-')) return undefined;
  const full = !(assessmentId.endsWith('-guided-1') || assessmentId.endsWith('-apply'));
  return String.raw`
const assert = (condition, message) => { if (!condition) throw new Error(message); };
const wait = milliseconds => new Promise(resolve => setTimeout(resolve, milliseconds));
const text = node => node?.textContent || '';
const root = () => document.querySelector('#root') || document;
const form = () => root().querySelector('form'); const input = () => root().querySelector('#task-input'); const list = () => Array.from(root().querySelectorAll('#task-list li'));
const status = id => root().querySelector(id);
const eventually = async (check, message, limit = 30) => { for (let n = 0; n < limit; n += 1) { if (check()) return; await wait(10); } throw new Error(message); };
const setNativeValue = (field, value) => { const setter = Object.getOwnPropertyDescriptor(HTMLInputElement.prototype, 'value')?.set; setter?.call(field, value); field.dispatchEvent(new Event('input', { bubbles: true })); };
const submit = async value => { const field = input(), current = form(); assert(field && current, 'Render a labelled task form with #task-input.'); setNativeValue(field, value); const event = new Event('submit', { bubbles: true, cancelable: true }); current.dispatchEvent(event); assert(event.defaultPrevented, 'Prevent the task form from navigating.'); await wait(15); };
const ready = async () => { const field = input(); if (!field) return; await eventually(() => !field.disabled || Boolean(status('#recover-storage')), 'Finish startup recovery and expose a clear next action.'); };
const taskContract = async () => { await ready(); assert(form() && input() && root().querySelector('#task-list') && status('#task-count') && status('#empty-state'), 'Use a form, #task-input, #task-list, #task-count, and #empty-state.'); assert(root().querySelector('label[for="task-input"]'), 'Connect the visible New task label to #task-input.'); for (const node of [status('#task-count'), status('#empty-state')]) assert(node.getAttribute('aria-live') === 'polite', 'Use polite live regions for changing count and empty feedback.'); };
const stateChecks = async () => { await taskContract(); const count = status('#task-count'); await submit('   '); assert(/enter|task|required/i.test(text(status('#input-error'))), 'Whitespace input needs visible feedback.'); await submit('  <strong>Literal</strong>  '); await eventually(() => list().some(row => text(row).includes('<strong>Literal</strong>')), 'Add trimmed literal task text.'); assert(!list().some(row => row.querySelector('strong')), 'Render task text as text, never injected HTML.'); await submit('Same'); await submit('Same'); assert(list().filter(row => text(row).includes('Same')).length === 2, 'Keep duplicate labels as independent tasks.'); const same = list().filter(row => text(row).includes('Same')); same[1].querySelector('input[type="checkbox"]').click(); await wait(15); let after = list().filter(row => text(row).includes('Same')); assert(!after[0].querySelector('input').checked && after[1].querySelector('input').checked && /1\s+of/i.test(text(count)), 'Toggle only the selected task and derive the count.'); after[1].querySelector('input[type="checkbox"]').click(); await wait(15); after = list().filter(row => text(row).includes('Same')); assert(!after[1].querySelector('input').checked, 'Toggling twice restores the same task.'); after[1].querySelector('input[type="checkbox"]').click(); root().querySelector('[data-filter="active"]').click(); await wait(15); assert(list().every(row => !row.querySelector('input').checked), 'Active filter must derive from source tasks without mutating them.'); root().querySelector('[data-filter="completed"]').click(); await wait(15); assert(list().length >= 1 && list().every(row => row.querySelector('input').checked), 'Completed filter must show completed tasks.'); list()[0].querySelector('button').click(); await wait(15); root().querySelector('[data-filter="all"]').click(); await wait(15); assert(list().some(row => text(row).includes('Same')), 'Deleting a filtered row must preserve hidden task records.'); };
if (${JSON.stringify(topic)} === 'react-dashboard-scope-and-component-map') {
  const scope = document.querySelector('#dashboard-scope'); const map = Array.from(document.querySelectorAll('#component-map li')).map(node => text(node)).join(' ');
  assert(scope && /add|complete|delete|filter/i.test(text(scope)), 'Describe the dashboard’s task flows in #dashboard-scope.');
  assert(/App/.test(map) && /TaskForm/.test(map) && /TaskList/.test(map) && /TaskRow/.test(map), 'Name App, TaskForm, TaskList, and TaskRow in #component-map.');
  ${full ? "assert(/owns.*task|tasks.*owner/i.test(map) && /onAdd|onToggle|onDelete/i.test(map), 'State ownership and callback props must be explicit.'); assert(/vanilla|vite|full.stack/i.test(text(document.querySelector('#stack-plan'))), 'Compare Vanilla, Vite React, and a full-stack framework.');" : ''}
}
else if (${JSON.stringify(topic)} === 'react-stack-and-project-setup') {
  await eventually(() => root().querySelector('main'), 'Mount React into #root.'); assert(root().querySelector('h1'), 'Render a React dashboard heading.'); const stack = document.querySelector('#stack-plan'); assert(stack && /vanilla|React|Vite|full.stack/i.test(text(stack)), 'Compare Vanilla, React with Vite, and a full-stack framework in #stack-plan.');
  ${full ? "assert(document.querySelector('#root') && root().querySelector('form') && document.querySelector('#stack-plan'), 'Use the #root mount, React dashboard form, and stack/file plan.');" : ''}
}
else if (${JSON.stringify(topic)} === 'react-components-props-and-layout') {
  await taskContract(); assert(root().querySelector('button[type="button"]'), 'Use non-submit buttons for filters or task actions.');
  ${full ? "assert(list().length >= 2 && list().every(row => row.querySelector('input[type=checkbox]') && row.querySelector('button[type=button]')), 'Render static task rows with named checkbox and delete controls.'); assert(root().querySelector('#input-error')?.getAttribute('role') === 'alert', 'Use role=alert for input feedback.');" : ''}
}
else if (${JSON.stringify(topic)} === 'react-task-state-and-interactions') {
  await taskContract(); await submit('State task'); assert(list().some(row => text(row).includes('State task')), 'Adding a valid task must update React state.');
  ${full ? 'await stateChecks();' : ''}
}
else if (${JSON.stringify(topic)} === 'react-effects-persistence-and-errors') {
  await taskContract(); const save = status('#save-status'), sync = status('#sync-status'); assert(save && sync, 'Expose #save-status and #sync-status as visible effect states.'); assert(save.getAttribute('aria-live') === 'polite' && sync.getAttribute('aria-live') === 'polite', 'Make persistence and async feedback polite live regions.');
  const mode = globalThis.__gradeStorage?.mode; await wait(35);
  if (/malformed|invalid-version|duplicate-id|read-failure/.test(mode || '')) { const prior = globalThis.__gradeStorage?.value; const recover = root().querySelector('#recover-storage'); assert(recover || root().querySelector('#retry-restore'), 'Do not silently overwrite invalid saved data; offer recovery or retry.'); assert(globalThis.__gradeStorage?.value === prior, 'Keep an invalid record unchanged until the user chooses recovery.'); if (recover) { recover.click(); await eventually(() => !input().disabled, 'Explicit recovery must return a usable form.'); await submit('Recovered'); } }
  else if (mode === 'legacy') { assert(text(root()).includes('Legacy task'), 'Migrate a legacy task array into the dashboard.'); await eventually(() => /"version":2/.test(globalThis.__gradeStorage?.value || ''), 'Persist the migrated legacy data as a version-2 envelope.'); }
  else if (mode === 'save-failure') { await submit('Still visible'); await eventually(() => /could not save|still visible/i.test(text(save)), 'Keep visible changes and explain a failed save.'); }
  else { if (mode === 'valid') assert(text(root()).includes('Restored'), 'Restore valid saved tasks before enabling edits.'); if (mode === 'reload') assert(text(root()).includes('Persisted'), 'Reload must restore the prior frame snapshot.'); await submit('Persisted'); await eventually(() => globalThis.__gradeStorage?.value?.includes('Persisted'), 'Save the versioned task snapshot after a real add.'); }
  ${full ? "const click = label => Array.from(root().querySelectorAll('button')).find(button => text(button) === label)?.click(); click('Load Empty'); assert(/loading/i.test(text(sync)), 'Clear prior async output and announce Loading.'); await eventually(() => /no tasks/i.test(text(sync)), 'Empty needs a distinct visible state.'); click('Load Error'); await eventually(() => /unavailable|try again/i.test(text(sync)), 'Error needs visible recovery feedback.'); click('Load Slow'); await wait(2); click('Load Fast'); await eventually(() => /Loaded Fast/.test(text(sync)), 'Fast must become the current async result.'); await wait(110); assert(/Loaded Fast/.test(text(sync)) && text(root()).includes('Fast response'), 'A stale Slow completion must not replace Fast.'); click('Load SlowError'); await wait(2); click('Load Fast'); await eventually(() => /Loaded Fast/.test(text(sync)), 'A stale rejection must not replace Fast.'); click('Load IgnoreSlow'); await wait(2); click('Load Fast'); await eventually(() => /Loaded Fast/.test(text(sync)), 'Fast must win after an abort-ignoring fixture starts.'); await wait(110); assert(/Loaded Fast/.test(text(sync)), 'Generation guards must ignore a completion after cancellation is ignored.'); assert((globalThis.__taskApiEvents || []).some(event => event.type === 'abort' && /Slow/.test(event.name)), 'Clean up replaced async effects with AbortController.');" : ''}
}
else if (${JSON.stringify(topic)} === 'react-testing-and-export') {
  await taskContract(); const smoke = root().querySelector('#run-react-smoke'), result = status('#react-smoke-status'), handoff = status('#react-export-handoff'); assert(smoke && result, 'Provide React smoke controls.'); const before = globalThis.__gradeStorage?.value, writes = (globalThis.__taskStorageEvents || []).filter(event => event === 'set').length; smoke.click(); await eventually(() => /passed|failed/i.test(text(result)), 'A smoke test must report a real result.'); assert(/passed/i.test(text(result)), 'The reference smoke workflow must pass.'); assert((globalThis.__taskStorageEvents || []).filter(event => event === 'set').length >= writes + 1, 'Smoke must exercise a saved change, not only print passed.'); assert(globalThis.__gradeStorage?.value === before, 'Smoke cleanup must restore the prior saved task snapshot.');
  ${full ? "assert(/main\.jsx/i.test(text(handoff)) && /App\.jsx/i.test(text(handoff)) && /server|http\.server/i.test(text(handoff)) && /export again|rebuild/i.test(text(handoff)), 'Explain the React source map, re-export, and static HTTP handoff.');" : ''}
}
else throw new Error('Unknown React assessment: ' + ${JSON.stringify(topic)});
`;
}

export const isReactAssessment = (assessmentId: string) => /^react-.*-(guided-[12]|apply|debug|combine)$/.test(assessmentId);
export const reactAssessmentNeedsStorage = (assessmentId: string) => /^react-(effects-persistence-and-errors|testing-and-export)-/.test(assessmentId);
export default reactAssessmentBody;
