import type { AssessmentQuestion } from './schema';

const path = 'projects/vanilla-todo/topics/todo-dom-events-and-task-state/questions';
type Category = AssessmentQuestion['reasoningCategory'];
type Group = 'rendering' | 'events' | 'state' | 'identity';
function q(id: string, category: Category, group: Group, kind: AssessmentQuestion['kind'], prompt: string, acceptedAnswers: string[], misconceptionFeedback: string): AssessmentQuestion {
  return { id: `todo-dom-q-${id}`, identity: `todo-dom-q-${id}`, path: `${path}/todo-dom-q-${id}`, reasoningCategory: category, equivalenceGroup: group, kind, prompt, acceptedAnswers, misconceptionFeedback, reviewed: true };
}

/** Astra reviewed: bounded answers, original reasoning tasks, and eight materially different reserve scenarios. */
export const domQuestions: AssessmentQuestion[] = [
  q('predict-empty', 'prediction', 'events', 'conceptual', 'The list already contains two tasks. Submit receives "   ". How many tasks remain? Answer with a number.', ['2', 'two'], 'Trimming produces an empty string, so validation leaves the existing two tasks unchanged.'),
  q('predict-trim', 'prediction', 'events', 'code', 'The input is "  Buy  milk  ". After trim(), what exact label is stored? Type the label without quotes, preserving its internal spaces.', ['Buy  milk'], 'trim removes outer whitespace; the two spaces between Buy and milk remain.'),
  q('predict-count', 'prediction', 'state', 'conceptual', 'Two tasks exist and one has done: true. What exact count text should render?', ['1 of 2 complete'], 'Count true done flags for the numerator and all task records for the denominator.'),
  q('predict-literal', 'prediction', 'rendering', 'code', 'task.text is "<em>Plan</em>". label.textContent = task.text. Type the exact visible label, without surrounding quotes.', ['<em>Plan</em>'], 'textContent displays angle brackets literally rather than creating an em element.'),
  q('predict-toggle', 'prediction', 'state', 'conceptual', 'A matching task starts done: false. toggleTask runs twice for its id. What is done afterward? Answer true or false.', ['false'], 'Each toggle flips the boolean: false → true → false.'),
  q('predict-input', 'prediction', 'events', 'conceptual', 'A valid add returns a new array. The handler clears input only when nextTasks !== tasks. Is the input cleared? Answer yes or no.', ['yes'], 'A successful add returns a different array reference, so the handler clears the input.'),
  q('debug-id-type', 'debugging', 'identity', 'code', 'task.id is numeric. Complete the smallest repair: task.id === String(id) becomes task.id === ____ . The callback already supplies a numeric id.', ['id'], 'Compare the numeric id directly; strict equality does not match it to a string.'),
  q('debug-inner-html', 'debugging', 'rendering', 'code', 'A label parses "<img>" as markup. Fill the property name: label.____ = task.text;', ['textContent'], 'textContent inserts literal text. innerHTML parses markup.'),
  q('debug-stale-count', 'debugging', 'state', 'conceptual', 'After deleting a completed task, the count is stale. Choose the repair: A) decrement a separate counter on add; B) derive count from current tasks inside render. Answer A or B.', ['B'], 'B derives the count after every transition, including deleting a completed task.'),
  q('debug-submit', 'debugging', 'events', 'code', 'Native form submission navigates away. Fill the method name: event.____();', ['preventDefault'], 'Prevent the native submission while keeping your JavaScript submit handler.'),
  q('debug-replace', 'debugging', 'rendering', 'code', 'Every render appends duplicate rows. Fill the method that replaces the old list: list.____(...rows);', ['replaceChildren'], 'replaceChildren replaces the previous children with the rows derived from current state.'),
  q('debug-invalid-clear', 'debugging', 'events', 'conceptual', 'The handler clears whitespace input even when addTask returns the original tasks array. Which condition should guard input clearing? A) nextTasks === tasks; B) nextTasks !== tasks. Answer A or B.', ['B'], 'Only a successful add returns a different array in this design.'),
  q('explain-array', 'explanation', 'state', 'conceptual', 'Why does this addTask design return a new array on success? A) so reference comparison can distinguish success from rejected input; B) because JavaScript arrays cannot be changed. Answer A or B.', ['A'], 'Arrays can be mutated. This design deliberately returns a new array to make successful transitions explicit.'),
  q('explain-render', 'explanation', 'rendering', 'conceptual', 'What is render responsible for? A) reading user input and changing task ids; B) deriving the DOM from task state. Answer A or B.', ['B'], 'Event handlers change state; render projects that state into labels, controls, and count.'),
  q('explain-text', 'explanation', 'rendering', 'conceptual', 'Why use textContent for task labels? A) it encrypts input; B) it displays input as text without parsing HTML. Answer A or B.', ['B'], 'textContent controls how text is inserted; it does not encrypt or save it.'),
  q('explain-id', 'explanation', 'identity', 'conceptual', 'Two tasks are both named Review. Why identify row actions by id? A) labels can be duplicated; B) ids make the checkbox render faster. Answer A or B.', ['A'], 'An id identifies the record independently of its display text.'),
  q('explain-count', 'explanation', 'state', 'conceptual', 'Why calculate tasks.filter(task => task.done).length during render? A) to avoid keeping a second count that could disagree with task state; B) to remove completed tasks. Answer A or B.', ['A'], 'filter creates a temporary array for counting. It does not remove records from tasks.'),
  q('explain-scope', 'explanation', 'identity', 'conceptual', 'A row is rebuilt on every render. Its handler closes over task.id. Why? A) the DOM row itself must be permanent; B) the stable id still refers to the intended task record. Answer A or B.', ['B'], 'The row can be replaced; the record keeps its stable id across renders.'),
  q('apply-add', 'application', 'events', 'code', 'Complete the validation boundary: const text = rawText.____();', ['trim'], 'Trim before checking whether the candidate is empty.'),
  q('apply-new-task', 'application', 'identity', 'code', 'Complete the initial task flag: { id: nextId++, text, done: ____ }', ['false'], 'A newly added task starts incomplete and has its own id.'),
  q('apply-toggle', 'application', 'state', 'code', 'Complete the matching branch: { ...task, done: ____ } to invert the existing done flag. Use the ! operator.', ['!task.done'], 'Logical negation flips true and false while the spread preserves other fields.'),
  q('apply-delete', 'application', 'identity', 'code', 'Choose the strict comparison operator: tasks.filter(task => task.id ____ id) must keep every task except the selected id.', ['!=='], 'filter keeps records whose predicate is true; keep nonmatching ids.'),
  q('apply-count', 'application', 'state', 'code', 'Complete the count expression: tasks.filter(task => task.done).____', ['length'], 'The filtered array contains completed records; length counts them.'),
  q('apply-label', 'application', 'rendering', 'code', 'The grader expects a span with class task-label. Complete: label.className = ____; Include JavaScript string quotes.', ["'task-label'", '"task-label"', '`task-label`'], 'className takes a string; both single and double quotes are valid JavaScript spellings.'),

  // Reserve items share concepts with earlier items but require different evidence or transitions.
  q('equivalent-predict-count', 'prediction', 'identity', 'conceptual', 'Ids 1 and 2 are added, then id 1 is deleted. A broken creator chooses tasks.length + 1 for the next id. Which existing id would it duplicate? Answer with a number.', ['2', 'two'], 'One task remains, so length + 1 yields 2, which already exists. A monotonically increasing nextId avoids reuse.'),
  q('equivalent-predict-toggle', 'prediction', 'rendering', 'conceptual', 'task.done is false. You manually set its DOM checkbox.checked to true without changing tasks. render rebuilds the row from tasks. Is the new checkbox checked? Answer yes or no.', ['no'], 'A DOM-only change is lost when render rebuilds from the unchanged false state.'),
  q('equivalent-debug-duplicate', 'debugging', 'identity', 'code', 'Deleting by text removes both duplicate labels. Fill the record field to retain only nonmatching ids: tasks.filter(task => task.____ !== id)', ['id'], 'Filtering by the stable id removes one record even if labels match.'),
  q('equivalent-debug-render', 'debugging', 'rendering', 'conceptual', 'The count updates after toggle but a rebuilt checkbox always appears unchecked. Choose the missing assignment: A) checkbox.checked = task.done; B) checkbox.value = task.text. Answer A or B.', ['A'], 'checked is the current boolean control state; value does not set whether a checkbox is checked.'),
  q('equivalent-explain-state', 'explanation', 'events', 'conceptual', 'A Delete button is moved inside the form. Why explicitly set its type to button? A) to prevent it also submitting the add form; B) to stop its click listener from running. Answer A or B.', ['A'], 'Inside a form, a button without an explicit type can submit. type="button" keeps its click behavior without native submit.'),
  q('equivalent-explain-immutability', 'explanation', 'state', 'conceptual', 'A toggle uses tasks.map(task => task.id === id ? changedTask : task). Why return task in the nonmatching branch? A) to discard all other records; B) to preserve them in the new array. Answer A or B.', ['B'], 'map returns one output for every input; returning task preserves nonmatching records.'),
  q('equivalent-apply-empty', 'application', 'events', 'code', 'Complete the early-return statement after trimming: if (!text) ____ tasks;', ['return'], 'Return the unchanged array before creating a record for invalid input.'),
  q('equivalent-apply-checkbox', 'application', 'state', 'conceptual', 'Add A and B (both incomplete), toggle B, delete A, then add C. What exact count text should render?', ['1 of 2 complete'], 'B stays complete, A is gone, and C starts incomplete: one completed record out of two.'),
];
