import type { Files } from '../contracts';

const products = String.raw`export const products = [
  { id: 'ember-mug', name: 'Ember Mug', category: 'table', priceCents: 2400, stock: 4, description: 'A hand-glazed cedar-red mug for slow mornings.' },
  { id: 'field-notebook', name: 'Field Notebook', category: 'paper', priceCents: 1200, stock: 8, description: 'A cloth-bound notebook made for sketches and lists.' },
  { id: 'cedar-throw', name: 'Cedar Throw', category: 'textile', priceCents: 6800, stock: 2, description: 'A soft woven throw with a <strong>literal</strong> woodland stripe.' },
  { id: 'brass-lamp', name: 'Brass Reading Lamp', category: 'home', priceCents: 8400, stock: 1, description: 'A compact lamp for a bedside or reading corner.' }
];`;

const css = String.raw`:root{font-family:system-ui,sans-serif;color:#243128;background:#f7f5ef}*{box-sizing:border-box}body{margin:0}main{max-width:58rem;margin:2rem auto;padding:1.25rem;background:#fff;border-radius:.8rem}nav,.controls,form,.card-actions{display:flex;flex-wrap:wrap;gap:.6rem;align-items:center}button,input,select{font:inherit;padding:.45rem}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(12rem,1fr));gap:.8rem;margin-block:1rem}.card{border:1px solid #d9d2c3;border-radius:.6rem;padding:.8rem}#results-status,#cart-status,#checkout-status,#shop-smoke-status,#empty-results{min-height:1.3em}.price{font-weight:700}.hint{color:#59645b}[role=alert]{color:#9a2525}@media(max-width:420px){main{margin:0;border-radius:0}button,input,select{max-width:100%}}`;
const baseHead = '<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Cedar & Thread</title><link rel="stylesheet" href="./styles.css"></head><body><main id="shop-app">';
const close = '<script type="module" src="./main.js"></script></main></body></html>';

const scopeFull = baseHead + String.raw`<h1>Cedar &amp; Thread storefront plan</h1><p id="shop-scope">Shoppers browse an original catalog, open a product detail, search and filter, manage a cart, and complete a simulated checkout.</p><p id="catalog-identity">Cedar &amp; Thread is an original local home-goods catalog.</p><p id="originality-boundary">Use original local fixtures and a simulated checkout.</p><ol id="flow-map"><li>Catalog</li><li>Detail</li><li>Cart</li><li>Checkout</li></ol><p id="scope-exclusions">No marketplace branding or copied assets, accounts, server fulfillment, real payment collection, or personal data are part of this project.</p>` + close;
const scopeBasic = scopeFull.replace('<ol id="flow-map"><li>Catalog</li><li>Detail</li><li>Cart</li><li>Checkout</li></ol><p id="scope-exclusions">No marketplace branding or copied assets, accounts, server fulfillment, real payment collection, or personal data are part of this project.</p>', '');
const stackFull = baseHead + String.raw`<h1>Cedar &amp; Thread technical plan</h1><p id="shop-stack-plan">Plain JavaScript modules reuse DOM and storage foundations. Vite React can help with component state; a full-stack framework adds server routing and conventions. This shop chooses vanilla modules.</p><p id="data-plan">A local product fixture supplies deterministic catalog data.</p><ul id="route-plan"><li>#/catalog</li><li>#/product/:id</li><li>#/cart</li><li>#/checkout</li></ul><p id="boundary-plan">The browser owns local fixtures and cart storage. A server would own databases, inventory, authentication and payments.</p><p id="file-plan">index.html, styles.css, main.js, catalog.js, and cartStorage.js separate the shell, style, UI, fixture and saved cart.</p>` + close;
const stackBasic = stackFull.replace(/<ul id="route-plan"[\s\S]*?<p id="file-plan">[\s\S]*?<\/p>/, '');

const shell = baseHead + String.raw`<h1>Cedar &amp; Thread</h1><nav id="shop-nav" aria-label="Shop navigation"><a data-route="catalog" href="#/catalog">Catalog</a><a data-route="cart" href="#/cart">Cart <span id="cart-count">0</span></a></nav><section class="controls" aria-label="Catalog controls"><label>Search <input id="shop-search"></label><label>Category <select id="category-filter"><option value="all">All</option><option value="table">Table</option><option value="paper">Paper</option><option value="textile">Textile</option><option value="home">Home</option></select></label><label>Maximum price <select id="price-filter"><option value="all">Any</option><option value="25">$25</option><option value="70">$70</option></select></label></section><p id="results-status" role="status" aria-live="polite"></p><p id="empty-results" aria-live="polite"></p><section id="catalog-grid" class="grid" aria-label="Catalog"></section><section id="product-detail"></section><section id="cart-panel"><h2>Cart</h2><ul id="cart-list"></ul><p id="cart-total">Total: $0</p><p id="cart-status" role="status" aria-live="polite"></p></section><section id="checkout-panel"><h2>Simulated checkout</h2><form id="checkout-form"><label>Demo delivery <select id="checkout-delivery"><option value="">Choose a fictional route</option><option value="pickup-demo">Cedar counter pickup</option><option value="post-demo">Thread post demo</option></select></label><label><input id="checkout-consent" type="checkbox"> I understand this is a simulation.</label><label>Fixture outcome <select id="checkout-outcome"><option value="success">Approve simulation</option><option value="decline">Decline simulation</option></select></label><button id="checkout-submit">Confirm simulated order</button></form><p id="checkout-status" role="status" aria-live="polite"></p><p id="checkout-confirmation"></p></section><section id="wishlist-panel"><button id="run-shop-smoke" type="button">Run shop smoke test</button><p id="shop-smoke-status" role="status" aria-live="polite"></p><p id="shop-export-handoff" class="hint">Export includes index.html, styles.css, main.js, catalog.js and cartStorage.js. Serve the extracted folder with python -m http.server 8080, edit source files, then export again to rebuild.</p><p id="wishlist-status" role="status" aria-live="polite">Wishlist is in memory for this session only.</p><p>Wishlist <span id="wishlist-count">0</span></p></section>` + close;

const app = String.raw`import { products } from './catalog.js';
const $ = selector => document.querySelector(selector); let cart = []; let wishlist = new Set(); let latestCheckout = 0;
const money = value => '$' + value.toFixed(2); const route = () => location.hash || '#/catalog';
function product(id) { return products.find(item => item.id === id); }
function shownProducts() { const query = $('#shop-search').value.trim().toLowerCase(), category = $('#category-filter').value, maximum = $('#price-filter').value; return products.filter(item => (!query || (item.name + ' ' + item.description).toLowerCase().includes(query)) && (category === 'all' || item.category === category) && (maximum === 'all' || item.priceCents <= Number(maximum) * 100)); }
function renderCatalog() { const grid = $('#catalog-grid'), items = shownProducts(); grid.innerHTML = items.map(item => '<article class="card" data-product-id="' + item.id + '"><h2><a href="#/product/' + item.id + '">' + item.name + '</a></h2><p>' + item.description + '</p><p class="price">' + money(item.priceCents / 100) + '</p><div class="card-actions"><button type="button" data-cart-add="' + item.id + '">Add to cart</button><button type="button" data-wishlist-toggle="' + item.id + '">' + (wishlist.has(item.id) ? 'Remove wish' : 'Save wish') + '</button></div></article>').join(''); $('#results-status').textContent = items.length + ' products shown.'; $('#empty-results').textContent = items.length ? '' : 'No products match these filters.'; }
function renderDetail() { const id = route().replace('#/product/', ''), item = product(id), area = $('#product-detail'); if (!route().startsWith('#/product/')) { area.innerHTML = ''; return; } area.innerHTML = item ? '<article data-product-detail="' + item.id + '"><h2>' + item.name + '</h2><p>' + item.description + '</p><p class="price">' + money(item.priceCents / 100) + '</p><button type="button" data-cart-add="' + item.id + '">Add to cart</button></article>' : '<p id="product-not-found" role="alert">Product not found.</p>'; }
async function save() { await trainingStorage.setItem('cart', JSON.stringify({ version: 1, items: cart })); }
async function restore() { try { const raw = await trainingStorage.getItem('cart'); if (raw === null) return; const value = JSON.parse(raw); if (!value || value.version !== 1 || !Array.isArray(value.items) || !value.items.every(row => product(row.productId) && Number.isInteger(row.quantity) && row.quantity > 0) || new Set(value.items.map(row => row.productId)).size !== value.items.length) throw new Error('invalid'); cart = value.items; $('#cart-status').textContent = 'Saved cart restored.'; } catch { $('#cart-status').textContent = 'Saved cart is unavailable. Recover or retry before editing.'; $('#recover-cart').hidden = false; $('#retry-cart').hidden = false; document.querySelectorAll('[data-cart-add]').forEach(button => button.disabled = true); } }
function renderCart() { $('#cart-count').textContent = String(cart.reduce((sum, row) => sum + row.quantity, 0)); $('#cart-list').innerHTML = cart.map(row => { const item = product(row.productId); return '<li data-cart-row="' + item.id + '">' + item.name + ' <input aria-label="Quantity for ' + item.name + '" data-cart-quantity="' + item.id + '" type="number" min="1" value="' + row.quantity + '"> <button type="button" data-cart-remove="' + item.id + '">Remove</button></li>'; }).join(''); $('#cart-total').textContent = 'Total: ' + money(cart.reduce((sum,row) => sum + product(row.productId).price * row.quantity, 0)); }
async function commit(next) { const prior = cart; cart = next; renderCart(); try { await save(); $('#cart-status').textContent = 'Cart saved locally.'; } catch { cart = prior; renderCart(); $('#cart-status').textContent = 'Could not save cart; cart remains unchanged.'; } }
function render() { renderCatalog(); renderDetail(); renderCart(); $('#wishlist-count').textContent = String(wishlist.size); }
document.addEventListener('click', async event => { const target = event.target; if (!(target instanceof HTMLElement)) return; const id = target.dataset.cartAdd; if (id) { const current = cart.find(row => row.productId === id); await commit(current ? cart.map(row => row.productId === id ? {...row, quantity: row.quantity + 1} : row) : [...cart, { productId:id, quantity:1 }]); } const remove = target.dataset.cartRemove; if (remove) await commit(cart.filter(row => row.productId !== remove)); const wish = target.dataset.wishlistToggle; if (wish) { wishlist.has(wish) ? wishlist.delete(wish) : wishlist.add(wish); $('#wishlist-status').textContent = wishlist.size ? 'Saved to the in-memory wishlist.' : 'Wishlist is empty and remains in memory only.'; render(); } });
document.addEventListener('change', async event => { const target = event.target; if (target instanceof HTMLInputElement && target.dataset.cartQuantity) { const quantity = Number(target.value); if (Number.isInteger(quantity) && quantity > 0) await commit(cart.map(row => row.productId === target.dataset.cartQuantity ? {...row, quantity} : row)); } });
['input','change'].forEach(type => ['#shop-search','#category-filter','#price-filter'].forEach(selector => $(selector).addEventListener(type, renderCatalog)));
window.addEventListener('hashchange', render); $('#checkout-form').addEventListener('submit', event => { event.preventDefault(); const delivery = $('#checkout-delivery').value, consent = $('#checkout-consent').checked, outcome = $('#checkout-outcome').value, request = ++latestCheckout; $('#checkout-confirmation').textContent = ''; if (!delivery || !consent) { $('#checkout-status').textContent = 'Choose a fictional delivery route and confirm the simulation.'; return; } $('#checkout-status').textContent = 'Checking simulated order…'; setTimeout(async () => { if (request !== latestCheckout) return; if (outcome === 'decline') { $('#checkout-status').textContent = 'Simulation declined. Your cart is still available.'; return; } const prior = cart; cart = []; renderCart(); try { await save(); $('#checkout-status').textContent = 'Simulation approved.'; $('#checkout-confirmation').textContent = 'Demo order confirmed for ' + delivery + '.'; } catch { cart = prior; renderCart(); $('#checkout-status').textContent = 'Could not save confirmation; your cart was retained.'; } }, 20); });
$('#run-shop-smoke').addEventListener('click', async () => { const button = $('#run-shop-smoke'); if (button.disabled) return; button.disabled = true; const before = JSON.stringify(cart), oldRoute = location.hash, query = $('#shop-search').value, category = $('#category-filter').value, price = $('#price-filter').value, wishes = new Set(wishlist); try { await commit([...cart, {productId:'ember-mug', quantity:1}]); if (!$('#cart-list').textContent.includes('Ember Mug')) throw new Error('cart add failed'); $('#shop-smoke-status').textContent = 'Smoke test passed: catalog and cart behavior observed.'; } catch { $('#shop-smoke-status').textContent = 'Smoke test failed.'; } finally { cart = JSON.parse(before); wishlist = wishes; location.hash = oldRoute; $('#shop-search').value=query; $('#category-filter').value=category; $('#price-filter').value=price; render(); try { await save(); } catch {} button.disabled=false; } });
$('#recover-cart').addEventListener('click', async () => { cart=[]; $('#recover-cart').hidden=true; $('#retry-cart').hidden=true; $('#cart-status').textContent='Recovered with an empty cart.'; document.querySelectorAll('[data-cart-add]').forEach(button => button.disabled = false); renderCart(); }); $('#retry-cart').addEventListener('click', () => location.reload());
restore().finally(render); render();`;

const recoveryButtons = '<button id="recover-cart" type="button" hidden>Recover with empty cart</button><button id="retry-cart" type="button" hidden>Retry saved cart</button>';
const catalogOnly = baseHead + `<h1>Cedar &amp; Thread</h1><nav id="shop-nav" aria-label="Shop navigation"><a data-route="catalog" href="#/catalog">Catalog</a></nav><section id="catalog-grid" class="grid" aria-label="Catalog"></section><p id="results-status" role="status" aria-live="polite"></p>` + close;
const catalogApp = String.raw`import { products } from './catalog.js'; const grid=document.querySelector('#catalog-grid'); for(const item of products){const card=document.createElement('article'),title=document.createElement('h2'),description=document.createElement('p'),price=document.createElement('p'); card.className='card';card.dataset.productId=item.id;title.textContent=item.name;description.textContent=item.description;price.className='price';price.textContent='$'+(item.priceCents/100).toFixed(2);card.append(title,description,price);grid.append(card)} document.querySelector('#results-status').textContent=products.length+' products shown.';`;
const detailOnly = catalogOnly.replace('<p id="results-status" role="status" aria-live="polite"></p>', '<p id="results-status" role="status" aria-live="polite"></p><section id="product-detail"></section>');
const detailApp = String.raw`import { products } from './catalog.js'; const grid=document.querySelector('#catalog-grid'), detail=document.querySelector('#product-detail'); const draw=(parent,item,link=false)=>{const card=document.createElement('article'),title=document.createElement('h2'),copy=document.createElement('p');card.className='card';card.dataset.productId=item.id;if(link){const a=document.createElement('a');a.href='#/product/'+item.id;a.textContent=item.name;title.append(a)}else title.textContent=item.name;copy.textContent=item.description;card.append(title,copy);parent.append(card)}; function render(){const hash=location.hash||'#/catalog', id=hash.replace('#/product/',''), item=products.find(row=>row.id===id); grid.replaceChildren(...products.map(row=>{const host=document.createElement('div');draw(host,row,true);return host.firstChild})); detail.replaceChildren();if(hash.startsWith('#/product/')){if(item){const node=document.createElement('article');node.dataset.productDetail=item.id;draw(node,item);detail.append(node)}else{const note=document.createElement('p');note.id='product-not-found';note.setAttribute('role','alert');note.textContent='Product not found.';detail.append(note)}} document.querySelector('#results-status').textContent=products.length+' products shown.';} window.addEventListener('hashchange',render);render();`;
const filterOnly = detailOnly.replace('<section id="catalog-grid"', '<section class="controls"><label>Search <input id="shop-search"></label><label>Category <select id="category-filter"><option value="all">All</option><option value="table">Table</option><option value="paper">Paper</option><option value="textile">Textile</option><option value="home">Home</option></select></label><label>Maximum price <select id="price-filter"><option value="all">Any</option><option value="25">$25</option><option value="70">$70</option></select></label></section><p id="empty-results" aria-live="polite"></p><section id="catalog-grid"');
const filterApp = String.raw`import { products } from './catalog.js'; const $=s=>document.querySelector(s),grid=$('#catalog-grid'),detail=$('#product-detail'); function card(item){const node=document.createElement('article'),title=document.createElement('h2'),link=document.createElement('a'),price=document.createElement('p');node.className='card';node.dataset.productId=item.id;link.href='#/product/'+item.id;link.textContent=item.name;title.append(link);price.textContent='$'+(item.priceCents/100).toFixed(2);node.append(title,price);return node} function render(){const q=$('#shop-search').value.trim().toLowerCase(), category=$('#category-filter').value, maximum=$('#price-filter').value,items=products.filter(item=>(!q||(item.name+' '+item.description).toLowerCase().includes(q))&&(category==='all'||item.category===category)&&(maximum==='all'||item.priceCents<=Number(maximum)*100)); grid.replaceChildren(...items.map(card)); $('#results-status').textContent=items.length+' products shown.'; $('#empty-results').textContent=items.length?'':'No products match these filters.'; const hash=location.hash||'#/catalog',item=products.find(row=>row.id===hash.replace('#/product/','')); detail.replaceChildren();if(hash.startsWith('#/product/')){if(item){const node=document.createElement('article'),title=document.createElement('h2'),copy=document.createElement('p');node.dataset.productDetail=item.id;title.textContent=item.name;copy.textContent=item.description;node.append(title,copy);detail.append(node)}else{const note=document.createElement('p');note.id='product-not-found';note.setAttribute('role','alert');note.textContent='Product not found.';detail.append(note)}}} ['input','change'].forEach(type=>['#shop-search','#category-filter','#price-filter'].forEach(s=>$(s).addEventListener(type,render)));window.addEventListener('hashchange',render);render();`;
const durableApp = String.raw`import { products } from './catalog.js'; import { restoreCart, saveCart } from './cartStorage.js';
const $=s=>document.querySelector(s), money=c=>'$'+(c/100).toFixed(2); let cart=[], ready=false, wishes=new Set(), writes=Promise.resolve(), checkout=0, smoke=false;
const item=id=>products.find(p=>p.id===id), count=()=>cart.reduce((n,row)=>n+row.quantity,0), total=()=>cart.reduce((n,row)=>n+item(row.productId).priceCents*row.quantity,0);
function card(product){const node=document.createElement('article'),heading=document.createElement('h2'),link=document.createElement('a'),copy=document.createElement('p'),price=document.createElement('p'),add=document.createElement('button'),wish=document.createElement('button');node.className='card';node.dataset.productId=product.id;link.href='#/product/'+product.id;link.textContent=product.name;heading.append(link);copy.textContent=product.description;price.className='price';price.textContent=money(product.priceCents);add.type='button';add.dataset.cartAdd=product.id;add.textContent='Add to cart';wish.type='button';wish.dataset.wishlistToggle=product.id;wish.textContent=wishes.has(product.id)?'Remove wish':'Save wish';node.append(heading,copy,price,add,wish);return node}
function render(){const query=$('#shop-search').value.trim().toLowerCase(),category=$('#category-filter').value,limit=$('#price-filter').value,shown=products.filter(p=>(!query||(p.name+' '+p.description).toLowerCase().includes(query))&&(category==='all'||p.category===category)&&(limit==='all'||p.priceCents<=Number(limit)*100));$('#catalog-grid').replaceChildren(...shown.map(card));$('#results-status').textContent=shown.length+' products shown.';$('#empty-results').textContent=shown.length?'':'No products match these filters.';const list=$('#cart-list');list.replaceChildren(...cart.map(row=>{const p=item(row.productId),li=document.createElement('li'),input=document.createElement('input'),remove=document.createElement('button');li.dataset.cartRow=p.id;li.append(document.createTextNode(p.name+' '));input.type='number';input.min='1';input.max=String(p.stock);input.value=String(row.quantity);input.dataset.cartQuantity=p.id;input.setAttribute('aria-label','Quantity for '+p.name);remove.type='button';remove.dataset.cartRemove=p.id;remove.textContent='Remove';li.append(input,remove);return li}));$('#cart-count').textContent=String(count());$('#cart-total').textContent='Total: '+money(total());$('#wishlist-count').textContent=String(wishes.size);const hash=location.hash||'#/catalog';for(const id of ['catalog-grid','cart-panel','checkout-panel','product-detail']) $('#'+id).hidden=true;if(hash==='#/cart')$('#cart-panel').hidden=false;else if(hash==='#/checkout')$('#checkout-panel').hidden=false;else if(hash.startsWith('#/product/')){const p=item(hash.slice(10)),area=$('#product-detail');area.hidden=false;area.replaceChildren();const n=document.createElement('p');n.id=p?'product-detail-title':'product-not-found';n.textContent=p?p.name:'Product not found.';area.append(n)}else $('#catalog-grid').hidden=false}
async function persist(next){const prior=cart;cart=next;render();writes=writes.catch(()=>undefined).then(()=>saveCart(cart));try{await writes;$('#cart-status').textContent='Cart saved locally.'}catch{cart=prior;render();$('#cart-status').textContent='Could not save cart; cart remains unchanged.'}}
document.addEventListener('click',async e=>{const t=e.target;if(!(t instanceof HTMLElement)||!ready)return;if(t.dataset.cartAdd){const p=item(t.dataset.cartAdd),row=cart.find(r=>r.productId===p.id),quantity=(row?.quantity||0)+1;if(quantity>p.stock){$('#cart-status').textContent='That item has reached its fixture stock limit.';return}await persist(row?cart.map(r=>r.productId===p.id?{...r,quantity}:r):[...cart,{productId:p.id,quantity:1}])}if(t.dataset.cartRemove)await persist(cart.filter(r=>r.productId!==t.dataset.cartRemove));if(t.dataset.wishlistToggle){wishes.has(t.dataset.wishlistToggle)?wishes.delete(t.dataset.wishlistToggle):wishes.add(t.dataset.wishlistToggle);$('#wishlist-status').textContent='Wishlist is in memory for this session only.';render()}});
document.addEventListener('change',async e=>{const t=e.target;if(t instanceof HTMLInputElement&&t.dataset.cartQuantity){const p=item(t.dataset.cartQuantity),q=Number(t.value);if(Number.isInteger(q)&&q>0&&q<=p.stock)await persist(cart.map(r=>r.productId===p.id?{...r,quantity:q}:r))}});['input','change'].forEach(type=>['#shop-search','#category-filter','#price-filter'].forEach(s=>$(s).addEventListener(type,render)));window.addEventListener('hashchange',render);
$('#checkout-form').addEventListener('submit',e=>{e.preventDefault();const run=++checkout;if(!cart.length){$('#checkout-status').textContent='Add a fixture item before checkout.';return}if(!$('#checkout-delivery').value||!$('#checkout-consent').checked){$('#checkout-status').textContent='Choose a fictional delivery route and confirm the simulation.';return}$('#checkout-submit').disabled=true;$('#checkout-status').textContent='Checking simulated order…';setTimeout(async()=>{if(run!==checkout)return;if($('#checkout-outcome').value==='decline'){$('#checkout-status').textContent='Simulation declined. Your cart is still available.';$('#checkout-submit').disabled=false;return}const before=cart;try{await persist([]);if(cart.length)throw new Error('save');$('#checkout-status').textContent='Simulation approved.';$('#checkout-confirmation').textContent='Demo order confirmed.'}catch{cart=before;render();$('#checkout-status').textContent='Could not save confirmation; your cart was retained.'}finally{$('#checkout-submit').disabled=false}},20)});
$('#run-shop-smoke').addEventListener('click',async()=>{if(smoke||!ready)return;smoke=true;const button=$('#run-shop-smoke'),raw=await trainingStorage.getItem('cart').catch(()=>undefined),snapshot={cart:JSON.stringify(cart),hash:location.hash,q:$('#shop-search').value,c:$('#category-filter').value,p:$('#price-filter').value,w:[...wishes]};if(raw===undefined){$('#shop-smoke-status').textContent='Smoke test failed: saved cart could not be read.';smoke=false;return}button.disabled=true;let failure='';try{location.hash='#/catalog';render();document.querySelector('[data-cart-add="ember-mug"]').click();if(!$('#cart-list').textContent.includes('Ember Mug'))throw Error('add not observed');document.querySelector('[data-cart-quantity="ember-mug"]').dispatchEvent(new Event('change',{bubbles:true}));}catch{failure='Smoke test failed.'}finally{cart=JSON.parse(snapshot.cart);wishes=new Set(snapshot.w);location.hash=snapshot.hash;$('#shop-search').value=snapshot.q;$('#category-filter').value=snapshot.c;$('#price-filter').value=snapshot.p;render();try{if(raw===null)await trainingStorage.removeItem('cart');else await trainingStorage.setItem('cart',raw)}catch{failure='Smoke test failed: cleanup could not restore saved cart.'}button.disabled=false;smoke=false;$('#shop-smoke-status').textContent=failure||'Smoke test passed: DOM add and cart behavior observed.'}});
$('#recover-cart').addEventListener('click',async()=>{await persist([]);ready=true;$('#recover-cart').hidden=true;render()});$('#retry-cart').addEventListener('click',()=>location.reload());restoreCart(products).then(value=>{cart=value;ready=true;$('#cart-status').textContent='Saved cart restored.'},()=>{$('#cart-status').textContent='Saved cart is unavailable. Recover or retry before editing.';$('#recover-cart').hidden=false;$('#retry-cart').hidden=false}).finally(render);render();`;
function shopFiles(stage: number): Files {
  if (stage === 1) return { 'index.html': scopeFull, 'styles.css': css, 'main.js': '' };
  if (stage === 2) return { 'index.html': stackFull, 'styles.css': css, 'main.js': '' };
  if (stage === 3) return { 'index.html': catalogOnly, 'styles.css': css, 'main.js': catalogApp, 'catalog.js': products };
  if (stage === 4) return { 'index.html': detailOnly, 'styles.css': css, 'main.js': detailApp, 'catalog.js': products };
  if (stage === 5) return { 'index.html': filterOnly, 'styles.css': css, 'main.js': filterApp, 'catalog.js': products };
  const html = shell.replace('<section id="cart-panel">', recoveryButtons + '<section id="cart-panel">');
  const files: Files = { 'index.html': html, 'styles.css': css, 'main.js': durableApp, 'catalog.js': products };
  if (stage >= 6) files['cartStorage.js'] = String.raw`const KEY='cart', VERSION=1;
export function validCart(value, products) { return value && value.version === VERSION && Array.isArray(value.items) && value.items.every(row => row && typeof row.productId === 'string' && Number.isInteger(row.quantity) && row.quantity > 0 && products.some(product => product.id === row.productId && row.quantity <= product.stock)) && new Set(value.items.map(row => row.productId)).size === value.items.length; }
export async function restoreCart(products) { const raw = await trainingStorage.getItem(KEY); if (raw === null) return []; const snapshot = JSON.parse(raw); if (!validCart(snapshot, products)) throw new Error('Saved cart is unavailable.'); return snapshot.items.map(row => ({...row})); }
export async function saveCart(items) { await trainingStorage.setItem(KEY, JSON.stringify({ version: VERSION, items })); }
export async function clearCart() { await trainingStorage.setItem(KEY, JSON.stringify({ version: VERSION, items: [] })); }`;
  return files;
}

const ids = ['shop-scope-catalog-and-originality','shop-stack-data-and-route-plan','shop-setup-navigation-and-catalog','shop-product-details-and-client-server-boundaries','shop-product-search-and-filters','shop-cart-quantity-and-persistence','shop-checkout-validation-and-failure-states','shop-testing-export-and-handoff'];
export const ecommerceReferenceByTopic: Record<string, Files> = Object.fromEntries(ids.map((id, index) => [id, shopFiles(index + 1)]));
/** The final storefront snapshot is used by export tests and includes the independent wishlist milestone. */
export const testFiles: Files = ecommerceReferenceByTopic['shop-testing-export-and-handoff'];
export const ecommerceBasicReferenceByTopic: Record<string, Files> = Object.fromEntries(ids.map((id, index) => {
  const full = ecommerceReferenceByTopic[id];
  if (index === 0) return [id, { ...full, 'index.html': scopeBasic }];
  if (index === 1) return [id, { ...full, 'index.html': stackBasic }];
  if (index === 2) return [id, { ...full, 'main.js': full['main.js'].replace("price.textContent='$'+(item.priceCents/100).toFixed(2)", "price.textContent=''" ) }];
  if (index === 3) return [id, { ...full, 'main.js': full['main.js'].replace("note.id='product-not-found'", "note.id='missing-product'") }];
  if (index === 4) return [id, { ...full, 'main.js': full['main.js'].replace("item.priceCents<=Number(maximum)*100", 'true') }];
  if (index === 5) return [id, { ...full, 'main.js': full['main.js'].replace("await trainingStorage.setItem('cart', JSON.stringify({ version: 1, items: cart }));", "return;") }];
  if (index === 6) return [id, { ...full, 'main.js': full['main.js'].replace("if (outcome === 'decline')", "if (false)") }];
  if (index === 7) return [id, { ...full, 'index.html': full['index.html'].replace('id="shop-export-handoff"', 'id="shop-handoff"') }];
  return [id, full];
}));
function copy(files: Files): Files { return Object.fromEntries(Object.entries(files).map(([name, text]) => [name, text])); }
export function ecommerceStarter(topicId: string, kind: 'apply' | 'debug' | 'combine'): Files {
  const files = copy(ecommerceReferenceByTopic[topicId] ?? {}); if (!files['index.html']) throw new Error('Unknown ecommerce topic: ' + topicId);
  if (topicId === ids[0]) files['index.html'] = files['index.html'].replace(kind === 'apply' ? 'original catalog' : kind === 'debug' ? 'Catalog</li>' : 'original/local fixtures', kind === 'apply' ? 'catalog' : kind === 'debug' ? 'Browse</li>' : 'copied marketplace fixtures');
  else if (topicId === ids[1]) files['index.html'] = files['index.html'].replace(kind === 'apply' ? 'vanilla modules' : kind === 'debug' ? '#/product/:id' : 'databases, inventory, authentication and payments', kind === 'apply' ? 'an unspecified stack' : kind === 'debug' ? '#/product' : 'browser only');
  else if (topicId === ids[2]) files['main.js'] = files['main.js'].replace(kind === 'apply' ? 'data-product-id' : kind === 'debug' ? 'data-route="catalog"' : '#catalog-grid', kind === 'apply' ? 'data-card' : kind === 'debug' ? 'data-route="home"' : '#missing-grid');
  else if (topicId === ids[3]) files['main.js'] = files['main.js'].replace(kind === 'apply' ? "'# /catalog'" : kind === 'debug' ? 'id="product-not-found"' : "route().startsWith('#/product/')", kind === 'apply' ? "'# /broken'" : kind === 'debug' ? 'id="missing-product"' : 'false');
  else if (topicId === ids[4]) files['main.js'] = files['main.js'].replace(kind === 'apply' ? 'No products match these filters.' : kind === 'debug' ? "item.category === category" : "$('#shop-search').value.trim().toLowerCase()", kind === 'apply' ? '' : kind === 'debug' ? 'true' : "''");
  else if (topicId === ids[5]) files['main.js'] = files['main.js'].replace(kind === 'apply' ? "data-cart-quantity" : kind === 'debug' ? 'new Set(value.items.map(row => row.productId)).size !== value.items.length' : "await save(); $('#cart-status').textContent = 'Cart saved locally.';", kind === 'apply' ? 'data-quantity' : kind === 'debug' ? 'false' : "$('#cart-status').textContent = 'Cart saved locally.';");
  else if (topicId === ids[6]) files['main.js'] = files['main.js'].replace(kind === 'apply' ? "if (!delivery || !consent)" : kind === 'debug' ? "if (outcome === 'decline')" : "await save(); $('#checkout-status').textContent = 'Simulation approved.';", kind === 'apply' ? 'if (false)' : kind === 'debug' ? 'if (false)' : "$('#checkout-status').textContent = 'Simulation approved.';");
  else files['main.js'] = files['main.js'].replace(kind === 'apply' ? "id=\"run-shop-smoke\"" : kind === 'debug' ? "if (!$('#cart-list').textContent.includes('Ember Mug'))" : 'data-wishlist-toggle', kind === 'apply' ? 'id="missing-smoke"' : kind === 'debug' ? 'if (false)' : 'data-wish');
  return files;
}
export type EcommerceStorageScenario = { mode: 'valid'|'reload'|'missing'|'malformed'|'invalid-shape'|'duplicate-product'|'read-failure'|'save-failure'; seed: string | null; failWrites?: boolean };
export const ecommerceStorageScenarios: EcommerceStorageScenario[] = [
  { mode:'valid', seed: JSON.stringify({version:1,items:[{productId:'ember-mug',quantity:2}]}) },
  { mode:'reload', seed: JSON.stringify({version:1,items:[{productId:'field-notebook',quantity:1}]}) },
  { mode:'missing', seed:null }, { mode:'malformed', seed:'{bad' }, { mode:'invalid-shape', seed:JSON.stringify({version:1,items:[{productId:'none',quantity:0}]}) },
  { mode:'duplicate-product', seed:JSON.stringify({version:1,items:[{productId:'ember-mug',quantity:1},{productId:'ember-mug',quantity:2}]}) },
  { mode:'read-failure', seed:JSON.stringify({version:1,items:[]}) }, { mode:'save-failure', seed:JSON.stringify({version:1,items:[{productId:'ember-mug',quantity:1}]}), failWrites:true },
];
