import type { Activity, Blank, Challenge, Topic } from './schema';
import { ecommerceQuestions } from './ecommerceQuestions';
import { ecommerceReferenceByTopic, ecommerceBasicReferenceByTopic, ecommerceStarter } from './ecommerceReferences';

const projectId = 'amazon-inspired-ecommerce'; // Saved outline identity, independent of the original storefront brand.
type Detail = { id: string; title: string; summary: string; readings: [string,string,string]; steps: [string[],string[]]; checks: [string,string]; blanks: [string,string,string,string] };
const details: Detail[] = [
  {
    id:'shop-scope-catalog-and-originality', title:'Scope, catalog, and originality', summary:'Specify Cedar & Thread: an original local storefront with a bounded catalog and honest simulated checkout.',
    readings:[
      'Start with shopper outcomes before choosing code: browse a catalog, inspect one product, narrow results, change a cart, and try a simulated checkout. Cedar & Thread is our original home-and-stationery shop. Write original product names, descriptions and styling; do not copy another marketplace’s logos, assets, listings or trade dress. Fixed local fixtures are examples written into this project, not live prices or inventory. The first increment is an HTML specification, not a working store. Name the scope in #shop-scope, the brand in #catalog-identity and the fixture/simulation boundary in #originality-boundary.',
      'A product record needs a stable id, name, category, integer price in cents and stock limit. An id identifies the record even when its name changes; priceCents avoids accumulating binary decimal rounding while adding money. A cart line later stores productId and quantity, not a trusted copied price. Plan browse → detail → cart → simulated checkout, with a way back at every step. List empty search, unknown product, invalid quantity, saved-data failure, declined simulation and confirmation states. These are requirements now; implementation arrives in order. Use semantic headings and meaningful link/button labels so the plan includes keyboard and screen-reader users.',
      'A local simulation cannot reserve stock, charge money, fulfill an order or authenticate a customer. Exclude real payment and personal information, accounts, server fulfillment and copied marketplace assets explicitly. A wishlist will be a later independent local feature. Keep source drafts, course mastery and storefront cart data conceptually separate: saving your editor does not mean the preview has a backend. A useful scope review traces one successful shopper flow and one failure/recovery flow without inventing server capabilities.'
    ],
    steps:[['Write #shop-scope naming browse, product detail, search/filter, cart and simulated checkout.','Add #catalog-identity with Cedar & Thread and #originality-boundary explaining original local fixtures and simulation.'],['Add #flow-map showing catalog → detail → cart → checkout and the return/recovery paths.','Add #scope-exclusions excluding copied marketplace branding/assets, accounts, server fulfillment, real payment and personal data.']],
    checks:['The rendered specification names the original store, core shopper flows and local simulation boundary.','The full plan maps the flow and states explicit exclusions without presenting a real marketplace.'],
    blanks:['Does a local checkout confirmation prove that money was charged? Answer yes or no.','no','Complete the object field for a stable product identity: { ____: "ember-mug", name: "Ember Mug" }','id']
  },
  {
    id:'shop-stack-data-and-route-plan',title:'Stack, data, and route plan',summary:'Choose vanilla modules and map browser routes, data owners and future server responsibilities before navigation code.',
    readings:[
      'Compare three reasonable stacks: plain JavaScript modules have the smallest dependency surface for this local store; Vite React adds a build and component/state conventions useful for a larger interface; a full-stack framework adds server conventions but does not itself supply secure commerce. Choose vanilla modules here to reuse the DOM, event, async and storage foundations already practiced. The course host compiles files for its preview; that does not mean your storefront runs a server. Record the comparison and choice in #shop-stack-plan and the deterministic local catalog in #data-plan.',
      'A route is a mapping from a URL state to a view. A hash such as #/product/ember-mug stays in the browser and is not sent as a server path. Read location.hash at startup and on hashchange, then derive the view; a link with href="#/catalog" uses normal keyboard navigation and browser history. Plan #/catalog, #/product/:id, #/cart and #/checkout, with search/filter state in the catalog view. The :id token describes a variable segment, not a literal product. Parse a known route shape and look up a stable id; unknown paths and products need a visible recovery state. Hash routes avoid claiming server rewrites or installed router packages.',
      'Separate index.html (semantic shell), styles.css (layout), main.js (events and rendering), catalog.js (local product fixtures) and cartStorage.js (later async cart serialization). An ES module uses export const products = [...] and import { products } from "./catalog.js"; relative paths belong to your own files. Catalog data owns names and prices; cart state owns quantities; filters derive a view without replacing products. Keep database, authoritative inventory/pricing, authorization and payment responsibilities in a future server column. Browser storage is local and editable, never a source of authorization. Detailed trust boundaries follow after setup.'
    ],
    steps:[['Render #shop-stack-plan comparing plain JavaScript, Vite React and a full-stack framework, choosing vanilla modules.','Render #data-plan explaining deterministic local product fixtures and separate cart quantities.'],['Render #route-plan with all four hash routes and explicit not-found recovery.','Add #file-plan with index.html, styles.css, main.js, catalog.js and future cartStorage.js responsibilities; add #boundary-plan distinguishing local fixtures/storage from future database, inventory, auth and payment services.']],
    checks:['The plan compares three stacks and chooses local vanilla modules and fixtures.','The complete plan maps hash routes, file responsibilities and client/server ownership.'],
    blanks:['Is the URL fragment after # sent as a server request path? Answer yes or no.','no','Complete the browser event name used when a fragment changes: window.addEventListener("____", render);','hashchange']
  },
  {
    id:'shop-setup-navigation-and-catalog',title:'Setup, navigation, and catalog',summary:'Build a responsive semantic storefront and render deterministic local cards through module imports.',
    readings:[
      'Create a document with lang="en", a descriptive title and viewport metadata. Use a header, a named nav#shop-nav and main#shop-app. Load main.js with a module script and link styles.css. Import the products array from catalog.js. For each record, create a card carrying data-product-id, a heading, category and formatted price; render names/descriptions with textContent, not innerHTML. A literal HTML-looking fixture must stay text. Store priceCents as an integer; format dollars with (priceCents / 100).toFixed(2). A visual card is a projection of the fixture, not another product record.',
      'Use real links with href hashes and data-route values, labelled controls and a logical heading hierarchy. A responsive grid can use repeat(auto-fit, minmax(min(100%, 14rem), 1fr)); give children min-width: 0 and long text overflow-wrap: anywhere. Keep visible :focus-visible outlines and adequate contrast, and avoid fixed widths wider than the viewport. Place the card collection in #catalog-grid and announce the count in #results-status using role="status" and aria-live="polite". Decorative graphics need empty alt text; meaningful product illustrations need concise descriptions. Original text-only cards are also valid and need no external image downloads.',
      'Run after each small edit: verify the heading, module imports, all local fixture cards and catalog navigation before implementing product behavior. The fixture catalog is synchronous; do not pretend a network request is loading. If a future data source loads asynchronously, its loading/error states will need real transitions. At this stage product, cart and checkout routes may explain that their features come later. Test keyboard Tab/Enter and a 390px viewport. Saving restores source without automatically executing it; continue your existing project and retain planning notes.'
    ],
    steps:[['Build index.html, styles.css, catalog.js and main.js with local module imports.','Render the Cedar & Thread heading, #shop-nav and #catalog-grid with fixture cards identified by data-product-id.'],['Add meaningful product links, category/price text and accessible #results-status.','Check responsive cards, focus outlines, keyboard navigation and literal text; preserve the earlier scope and route plan.']],
    checks:['The original storefront mounts its local catalog and catalog navigation.','The complete shell exposes semantic navigation, predictable card fields and accessible catalog feedback.'],
    blanks:['Which DOM property displays product text without parsing it as HTML?','textContent','Complete price formatting: (priceCents / 100).____(2)','toFixed']
  },
  {
    id:'shop-product-details-and-client-server-boundaries',title:'Product details and client/server boundaries',summary:'Resolve product hash routes and not-found recovery while distinguishing browser demonstrations from trusted services.',
    readings:[
      'Read the hash on startup as well as hashchange so a copied detail link works. Match #/product/:id, extract the id and find its record with products.find(product => product.id === id). A match renders #product-detail using literal name, category, price and description; an unknown id renders #product-not-found with a link back to #/catalog. Unknown routes need similar recovery. Never assume a list position is a product id or dereference an undefined record. Detail views should agree with their catalog card. Add a heading/focus destination after a route change so keyboard users can locate the new view.',
      'An API is an agreed request/response interface; calling a local lookup function is not a remote API deployment. A server receives requests and can enforce checks outside the shopper’s editable browser. A database stores/query records durably under its server access rules. Authentication asks who a caller is; authorization asks which action that caller may perform. A hidden button or an isAdmin flag in browser storage proves neither. This phase has no login, passwords, database, server runtime or remote product API. Label catalog lookups and checkout outcomes as deterministic local simulations in the visible boundary explanation.',
      'A future purchase service must re-read authoritative product prices/stock, validate quantities, authorize the buyer and safely process payment through an appropriate provider. Client validation improves feedback but cannot enforce those properties. Never place a secret or pretend credential in learner files; exported source is visible. Keep the browser-to-server seam explicit without implementing it: the current detail lookup returns a fixture, while Phase 7 will decide the real API/auth/database contracts. Verify missing products and browser Back/Forward instead of silently showing a different item.'
    ],
    steps:[['Resolve #/product/ember-mug and render that fixture in #product-detail.','Provide a catalog return link and a visible explanation of the local fixture boundary.'],['Handle direct hash entry, unknown product ids and unknown routes without throwing; show #product-not-found with recovery.','Explain client, server, API, database, authentication and authorization responsibilities; do not add durable auth or backend code.']],
    checks:['A valid product route renders the matching local record and explains the client boundary.','Direct routes and not-found recovery work; the app does not claim server inventory, auth or payment capabilities.'],
    blanks:['Which term means deciding whether an identified caller may perform an action: authentication or authorization?','authorization','Complete stable lookup: products.find(product => product.____ === id)','id']
  },
  {
    id:'shop-product-search-and-filters',title:'Product search and filters',summary:'Derive reversible catalog projections from normalized queries and intersecting filters.',
    readings:[
      'A search query is view state, separate from product data. Normalize it with trim().toLowerCase() and compare against the declared searchable name fields using includes. Array.filter returns a new projection; keep the original products array unchanged. Listen for input on #shop-search and rerender only the result area so typing retains focus. A blank query means all names match. The results count must describe the visible projection, not the whole catalog. Describe the matching rule so shoppers can predict the result.',
      'Add labelled #category-filter and #price-filter controls. Compose predicates with &&: the name must match, the category must match unless All is selected, and priceCents must be within the selected maximum unless unbounded. Convert a numeric select value deliberately and compare integer cents; do not accidentally compare display strings. Selecting an inexpensive category with no matching products should show #empty-results, not delete catalog entries. Clearing filters restores every fixture in deterministic order. Preserve filters while opening a detail and returning to the catalog where practical.',
      'Test a trimmed mixed-case query, an intersection that has one match, a combination with no matches and a reset back to the complete catalog. Announce results through #results-status and leave the labelled input usable by keyboard. No matches differs from an unavailable service: these fixtures are local and a query miss is not a fetch error. Search does not create a database index or a server search endpoint; those require a later architecture. Keep cart identity based on product ids when filtered positions change.'
    ],
    steps:[['Add labelled #shop-search and derive visible cards from name matches without mutating products.','Update #results-status and show #empty-results for a query with no matches.'],['Add #category-filter and #price-filter and combine predicates as an intersection.','Verify trimming/case folding, exact cents comparisons and reset restoring the complete catalog; retain input focus.']],
    checks:['Search changes the visible catalog and announces no-match results.','Query, category and maximum-price filters intersect predictably and reset without losing fixture records.'],
    blanks:['Should filtering replace the original product array? Answer yes or no.','no','Complete the intersection: nameMatches ____ categoryMatches && priceMatches','&&']
  },
  {
    id:'shop-cart-quantity-and-persistence',title:'Cart, quantities, and persistence',summary:'Maintain stable cart lines and totals, then restore and save them through scoped asynchronous storage with explicit recovery.',
    readings:[
      'A cart line stores {productId, quantity}. Adding the same product increments that line; different ids remain independent even when labels match. Validate positive integer quantities against the fixture stock limit, reject NaN/fractions/out-of-range values, and use an explicit Remove action for deletion. Derive item count and total cents from the current lines joined to the catalog, never from a formatted label or an untrusted saved price. Use data-cart-add, data-cart-quantity and data-cart-remove to identify the action’s product id. Keep #cart-list, #cart-count, #cart-total and live #cart-status consistent after each accepted action.',
      'The earlier projects introduced Promise-returning trainingStorage. Use only key "cart" in this workspace: await trainingStorage.getItem("cart") before enabling edits, JSON.parse inside try/catch, then validate {version:1,items:[...]}, known product ids, unique lines and legal integer quantities. Missing data is an empty cart; malformed JSON, unsupported versions and invalid lines are errors, not permission to overwrite the saved record. Show #recover-cart for explicit discard/recovery and #retry-cart for another read. Queue writes in order with a Promise chain so an older update cannot finish last. Report write rejection honestly while retaining visible changes.',
      'Preview storage belongs only to the selected project or challenge. It is not ordinary frame localStorage, synced account data or a stock reservation. A fresh Run restores the saved cart only if the app requests it; editor source and course-session schema 1 remain a separate concern. Test reload with two different products, changing one quantity, removing one line, invalid quantities, corrupt/duplicate/unknown saved records and read/write failures. Preserve bad data until the learner chooses recovery. A retry must remain usable, and queued writes must settle before checkout or tests take a snapshot.'
    ],
    steps:[['Implement add, quantity validation and remove by product id, with derived count and integer-cents total.','Merge repeated adds into one line; show accessible feedback for invalid quantities.'],['Implement guarded startup restore and ordered saves for the cart envelope; retain edits on failed writes.','Add explicit corrupt-data recovery/read retry, validate the whole payload and verify a fresh Run restores quantities.']],
    checks:['Cart additions, quantity changes, removals and derived totals respect stable ids and bounds.','The full cart restores before edits, saves in order and preserves invalid data or visible changes through storage failures.'],
    blanks:['May a failed JSON read silently overwrite a saved cart with an empty one? Answer yes or no.','no','Complete integer validation: Number.____(quantity)','isInteger']
  },
  {
    id:'shop-checkout-validation-and-failure-states',title:'Checkout validation and failure states',summary:'Validate a fictional checkout and model pending, declined and confirmed outcomes without collecting personal or payment data.',
    readings:[
      'This checkout is a local state machine, not a purchase. Use #checkout-delivery with an empty choice, pickup-demo and post-demo; #checkout-consent acknowledges the simulation; #checkout-outcome selects deterministic success or decline. Collect no name, email, address, card number or payment credentials. On form submit call preventDefault, reject an empty cart, missing delivery or unchecked consent with visible #checkout-status feedback, and keep the cart intact. Native constraints can help people, but the submit handler must validate too because code can dispatch an event without native validation.',
      'After validation, snapshot the requested cart and choices, enter Pending and guard repeated submissions until the local delayed result finishes. A Promise resolved with setTimeout simulates waiting without making a network request. Decline reports a recoverable failure and retains the cart for retry. Success may show #checkout-confirmation only after the simulated result succeeds and the empty cart is saved successfully; failed persistence must not falsely confirm or lose the original cart. Disable conflicting cart edits during the attempt or retire outdated callbacks with a generation token. New intent must never accept a stale success.',
      'Test missing consent, absent delivery, empty cart, repeated submit, decline then retry, success and a failed storage clear. The review total must agree with the current cart. Announce pending/errors/confirmation and make recovery keyboard reachable. No test requires real personal information. A future backend must revalidate price/inventory and authorization and handle idempotency for repeated real requests; the local pending guard cannot provide those guarantees. Phase 7 owns durable accounts/auth/backend decisions; this phase stops at an honest simulation.'
    ],
    steps:[['Build #checkout-form with only the two demo selects and simulation checkbox, plus #checkout-submit and live #checkout-status.','Validate cart, delivery and consent in the submit handler without clearing the cart or confirming invalid input.'],['Add deterministic delayed success/decline with a pending/duplicate-submit guard.','Preserve cart on decline or failed save, confirm only after successful simulated completion, and verify retry plus stale-intent protection.']],
    checks:['Invalid fictional checkout input is rejected accessibly without confirmation or cart loss.','Pending, decline, save failure, retry and success are distinct and never claim a real payment or order.'],
    blanks:['Should a declined simulation keep the cart for retry? Answer yes or no.','yes','Complete submit navigation prevention: event.____();','preventDefault']
  },
  {
    id:'shop-testing-export-and-handoff',title:'Testing, export, and independent feature',summary:'Prove repeatable storefront behavior, export a runnable snapshot and independently integrate an in-memory wishlist.',
    readings:[
      'A smoke test performs observable actions and asserts results; printing Passed does not verify an app. Use the actual add/quantity/form controls and deterministic fixtures to exercise cart and validation. Snapshot cart, route, query, filters, demo choices and saved storage before modifying anything. Refuse overlapping smoke runs, pending restore or checkout. If the initial snapshot read fails, report failure without writing/removing stored data. Restore successful snapshots in finally, drain queued writes and report completion only after cleanup. #run-shop-smoke triggers the workflow; #shop-smoke-status announces the result. An intentionally broken interaction must make the test fail.',
      'Repeat tests with existing cart data and unfinished input. Then select Export runnable ZIP in the host: root index.html is the compiled runnable snapshot, source/ contains exact editable originals, and README.md explains a static HTTP server such as python -m http.server 8080. Editing source/ alone does not rebuild root; return to Project Code and export again. Run the extracted output independently, follow routes, reload the cart and inspect keyboard/narrow-screen behavior. The archive contains no course session, mastery, checkpoint or saved preview cart snapshot. This prepares deployment but does not publish or supply accounts.',
      'Independent milestone: design and implement a wishlist in the combine challenge, using the state/events/rendering techniques already taught. A Set stores unique values: new Set() starts empty, has(id) tests membership, add(id) inserts, delete(id) removes and size gives the count; it does not persist by itself. Before coding, specify stable-id toggles, a count, an empty message, removal and independence from the cart. Provide data-wishlist-toggle controls, #wishlist-count and #wishlist-status. Two toggles restore the prior membership; filtering/reordering cannot move membership to a different product; adding to the wishlist never changes cart quantities. Label it in-memory: it resets on Run/reload and is not an account wishlist. Write and run a test sequence with two different products before consulting the reference. Keep this feature within the existing storefront and retain all earlier behavior.'
    ],
    steps:[['Implement a real interaction/assertion smoke workflow with #run-shop-smoke and #shop-smoke-status.','Snapshot before changes and restore in finally; fail on incorrect behavior and leave the current cart intact.'],['Verify repeated runs and snapshot/write failure cleanup; explain original files, compiled root, static serving and re-export in #shop-export-handoff.','Export and independently run catalog/detail/filter/cart/simulated checkout at desktop and narrow widths.']],
    checks:['The smoke workflow drives real interactions and assertions while restoring prior cart and control state.','Repeatable tests and a concrete runnable export handoff preserve existing work; the independent combine milestone adds a correctly isolated wishlist.'],
    blanks:['Does changing source/main.js alone rebuild the compiled exported root? Answer yes or no.','no','Complete guaranteed test cleanup: try { await testFlow(); } ____ { await restoreSnapshot(); }','finally']
  }
];
const partPath = (topic:string,part:string,id:string) => `projects/${projectId}/topics/${topic}/${part}/${id}`;
export const ecommerceTopics: Topic[] = details.map((detail,index) => {
  const id=detail.id, full=ecommerceReferenceByTopic[id], basic=ecommerceBasicReferenceByTopic[id];
  const activities: Activity[] = detail.readings.flatMap((explanation,n) => {
    const readId=`${id}-read-${n+1}`;
    const reading: Activity={id:readId,path:partPath(id,'activities',readId),title:`${detail.title}: ${['understand','extend carefully','verify independently'][n]}`,kind:'reading',order:n*2+1,objective:detail.summary,outline:explanation,explanation,instructions:['Trace the described input, state change and visible result before editing.','Identify which behavior is local and which responsibility needs a future server.'],hints:['Compare the familiar DOM, async and storage patterns from earlier projects.'],estimatedMinutes:8};
    if(n===2)return [reading];
    const guidedId=`${id}-guided-${n+1}`;
    return [reading,{id:guidedId,path:partPath(id,'activities',guidedId),title:`${detail.title}: ${n===0?'first increment':'complete the behavior'}`,kind:'guided-coding' as const,order:n*2+2,objective:detail.checks[n],outline:explanation,explanation,instructions:['Continue your saved ecommerce project: merge this increment, retaining working features and your notes.',...detail.steps[n],'Run, observe and Check. References are read-only comparisons; navigation never replaces your source.'],starterFiles:ecommerceStarter(id,n===0?'apply':'debug'),referenceSolution:n===0?basic:full,validation:{observable:detail.checks[n],checks:detail.checks.slice(0,n+1)},hints:['Use the documented selector contract, not a particular function spelling.','Trace the first failing interaction before altering unrelated code.'],estimatedMinutes:25}];
  });
  const blanks: Blank[] = (['conceptual','code'] as const).map((kind,n)=>({id:`${id}-blank-${n+1}`,path:partPath(id,'blanks',`${id}-blank-${n+1}`),kind,prompt:detail.blanks[n*2],acceptedAnswers:[detail.blanks[n*2+1]],explanation:detail.readings[n],normalization:{trim:true,collapseWhitespace:kind==='conceptual',caseSensitive:kind==='code',lineEndings:'lf'}}));
  const challenges: Challenge[] = (['apply','debug','combine'] as const).map((kind,n)=>({id:`${id}-${kind}`,path:partPath(id,'challenges',`${id}-${kind}`),title:index===7&&n===2?'Independent milestone: a local wishlist':['Apply the first increment','Debug a behavior regression','Combine independently'][n],order:n+1,objective:n===0?detail.checks[0]:detail.summary,starterFiles:ecommerceStarter(id,kind),instructions:[n===1?'Locate and repair the seeded behavioral defect.':n===2?'Plan and implement the complete topic contract in this separate workspace.':'Implement the first taught increment in this separate workspace.',...detail.steps[n===0?0:1],...(index===7&&n===2?['Write your wishlist acceptance plan before coding: stable-id add/remove, independent count, empty state and no cart side effects.','Implement data-wishlist-toggle, #wishlist-count and #wishlist-status; explicitly label in-memory reset on reload.','Test two products, toggle twice, filter and return; ensure the cart is unchanged.']:[]),'Use the observed checks and examples; a revealed reference is a comparison to understand.'],examples:[detail.checks[0],...(n===0?[]:[detail.checks[1]]),...(index===7&&n===2?['Save two different products: count 2. Toggle the first again: count 1, second remains saved, cart unchanged.']:[])],behaviorValidation:{observable:n===0?detail.checks[0]:detail.summary,checks:[...detail.checks.slice(0,n===0?1:2),...(index===7&&n===2?['Wishlist toggles are keyed by product id, reversible, counted and isolated from the cart.']:[])]},hints:['Trace the action’s stable identity and current state.','Inspect the relevant reading after a concrete attempt; merge a fix rather than discarding your draft.'],reference:activities.map(a=>a.id),referenceSolution:n===0?basic:full}));
  return {id,path:`projects/${projectId}/topics/${id}`,projectId,title:detail.title,order:index+1,status:'published',summary:detail.summary,prerequisiteTopicIds:index?[details[index-1].id]:[],activities,blanks,assessmentQuestions:ecommerceQuestions[id],challenges,gate:{type:'topic-gate',guidedActivityIds:activities.filter(a=>a.kind==='guided-coding').map(a=>a.id),requiredChallengeIds:challenges.map(c=>c.id),minimumDistinctCorrectQuestionIds:10,revealedAnswerEarnsCredit:false,requiresFreshEquivalentAfterReveal:true,wrongAnswerResetsProgress:false,retryPolicy:'exhaust-unseen-before-missed'}};
});
