import type { Activity, Blank, Challenge, Topic } from './schema';
import { reactQuestions } from './reactQuestions';
import { reactReferenceByTopic, reactBasicReferenceByTopic, reactStarter } from './reactReferences';

const projectId = 'react-task-dashboard';
type Detail = { id: string; title: string; summary: string; readings: [string,string,string]; steps: [string[],string[]]; checks: [string,string]; blanks: [string,string,string,string] };
const details: Detail[] = [
  {
    id:'react-dashboard-scope-and-component-map', title:'Scope and component map', summary:'Plan a small task dashboard with explicit component responsibilities, shared state ownership and deliberate stack tradeoffs.',
    readings:[
      'Start from the familiar Todo flows: add a trimmed label, complete or delete one stable task, and filter a view without losing hidden tasks. Define success, blank-input feedback and an empty list before code. A component is a named UI responsibility, not necessarily one HTML tag. App will coordinate the dashboard; TaskForm will collect input; TaskList will arrange rows; TaskRow will show one task. In this first topic, express the plan as ordinary HTML. No React syntax is required yet.',
      'Compare three choices. Plain JavaScript has few dependencies and is sufficient for this small app, but you maintain DOM synchronization yourself. React with a browser build adds JSX transformation and dependencies while making repeated components and state-driven rendering easier to coordinate. A full-stack framework adds routing/server conventions useful for a larger product; this local dashboard does not need a server. We choose React to practice component composition, not because every Todo needs it. Props are inputs from a parent. A callback prop is a function a child can call to request a change. These are planning terms now; the next two topics implement them.',
      'App owns the task array and selected filter because the list, totals and controls all depend on them. Keep temporary typing close to TaskForm unless another component needs it. Derive visible rows and counts from tasks rather than storing duplicate copies. TaskRow receives one task and callbacks carrying its stable ID. Two tasks may share a label. Plan loading, empty and error feedback and a local-only save boundary. Accounts, shared teams and payments are outside this project. Keep existing Weather and Todo work in their own projects.'
    ],
    steps:[['Render #dashboard-scope with add, complete, delete, filter, empty and invalid-input requirements.','Render #component-map with App, TaskForm, TaskList and TaskRow responsibilities.'],['Extend the plan with tasks/filter ownership and explicit props/callback direction.','Compare plain JavaScript, Vite with React and a full-stack framework; explain the local React choice and excluded server features.']],
    checks:['The rendered scope and component map identify the dashboard flows and separate responsibilities.','The complete plan explains shared state ownership, data/callback direction and stack tradeoffs.'],
    blanks:['Which common ancestor owns tasks shared by the list and counts?','App','Complete a conceptual callback invocation that identifies task 7: onToggle(____);','7']
  },
  {
    id:'react-stack-and-project-setup',title:'React stack and project setup',summary:'Mount a real React component through an explicit JSX entry and explain the browser build boundary.',
    readings:[
      'An ES module exports a value with export default and imports it with import App from "./App.jsx". A React component is a capitalized function returning JSX. JSX resembles HTML but is JavaScript syntax that must be transformed; use className for a CSS class, close tags, and put JavaScript expressions in braces. A component returns one parent element or a fragment <>...</>. main.jsx imports createRoot from react-dom/client, finds #root in index.html and calls createRoot(root).render(<App />). Teach this mount path before adding hooks or interactions.',
      'index.html supplies the root and module entry; main.jsx connects React to that root; App.jsx describes the view; styles.css owns presentation. Named imports use braces, for example import { createRoot } from "react-dom/client"; default imports do not. Relative paths refer to your own files. The course compiler supplies only its documented React imports; it does not run arbitrary npm packages in the preview. Outside this host, Vite is one way to transform JSX and bundle dependencies. No terminal or dependency installation is needed inside this lesson.',
      'Keep your component plan visible as you replace the static shell with React. Read compile errors before browser errors: an unresolved file path or JSX syntax error prevents the mount. Do not put script side effects in component rendering; rendering may repeat. Run explicitly, check the heading and styles, and use Stop to recover. Saving source is distinct from executing it. Reload restores the draft without running it. Runnable export later packages a compiled browser snapshot; source JSX alone is not directly runnable HTML.'
    ],
    steps:[['Create index.html with #root and the main.jsx module entry.','Import createRoot and App, mount the component and render a dashboard heading.'],['Separate App.jsx and styles.css while retaining the component plan.','Render #stack-plan with the chosen React build, file responsibilities and alternatives; verify imports and styles in Run.']],
    checks:['A real React root mounts a dashboard heading.','The mounted view retains the component/file plan and explains React build dependencies and alternatives.'],
    blanks:['Which transformable syntax lets a component return markup-like JavaScript?','JSX','Complete the named import: import { ____ } from "react-dom/client";','createRoot']
  },
  {
    id:'react-components-props-and-layout',title:'Components, props, and layout',summary:'Compose accessible presentational components with explicit read-only inputs before adding mutable task state.',
    readings:[
      'A parent supplies props in JSX: <TaskRow task={task} onToggle={handleToggle} />. The child receives them as a function parameter, often destructured: function TaskRow({ task, onToggle }) { ... }. Destructuring names fields from an object; it does not create independent task state. Treat props as read-only. Pass a callback, such as onClick={() => onToggle(task.id)}, rather than calling it during render. Array.map returns one row per item. React key={task.id} identifies the row across reordering; key is not an ordinary prop, so pass task or id separately.',
      'Build a main landmark, h1, native form and list. JSX uses htmlFor to associate a visible label with input id="task-input". Use a submit button for Add and type="button" for filters/delete. A checkbox gets an accessible name from its task label. Use literal {task.text}; never parse learner task text as HTML. #task-count and #empty-state use aria-live="polite"; #input-error uses role="alert". This stage can use supplied static tasks and read-only checkboxes. Controlled mutable inputs and hooks are introduced in the next topic.',
      'Data moves down through props and events request changes upward through callbacks. TaskList should not mutate the incoming array. A component can derive a label or count while rendering; no effect is needed. The children prop contains content written between component tags: function Panel({ children }) { return <section>{children}</section>; }. Test layout with a long task label and keyboard navigation. Avoid color-only completion indicators and clipped narrow layouts. Keep IDs stable for the lesson checks, but component function names are explanatory choices, not a source-spelling grading requirement.'
    ],
    steps:[['Render the form, label, count and list through separate presentational components.','Pass task objects to rows and render their text literally.'],['Add the named checkbox/delete and non-submit filter controls.','Add polite count/empty regions and an alert error region; verify keyboard order and a narrow viewport.']],
    checks:['The rendered form/list exposes labelled controls and data supplied to rows.','The complete layout includes accessible feedback, literal labels and independent row controls.'],
    blanks:['Are props read-only inputs or a child-owned mutable store? Answer read-only inputs or mutable store.','read-only inputs','Complete the JSX label attribute: <label ____="task-input">New task</label>','htmlFor']
  },
  {
    id:'react-task-state-and-interactions',title:'Task state and interactions',summary:'Implement validated add, independent toggle/delete and derived filters using React state updates.',
    readings:[
      'Call useState at the top level of a component: const [tasks, setTasks] = useState([]). The pair contains this render’s snapshot and a setter that schedules another render. Do not call hooks conditionally or inside event handlers. A controlled input uses value={text} and onChange={event => setText(event.target.value)}. Prevent form navigation; trim on submit, reject blank input with visible feedback, and clear the field only after a valid add. Keep text typed by the learner as literal data.',
      'Use setTasks(previous => [...previous, newTask]) when the next value depends on the previous one. The updater receives pending state, so queued changes compose. Make a stable ID in the event handler before entering the pure updater. Toggle with map and an ID comparison, returning a new changed record; delete with filter. Never mutate the prior array with push/splice or identify rows by label. Two Same labels remain independent records. Render keys from saved task IDs, not list positions or a newly random value on each render.',
      'Store tasks and the selected filter, then derive visibleTasks and completed count during rendering. Active/Completed are projections; switching views must not delete hidden records. Distinguish No tasks yet from No tasks match. A failed review must not erase earned course mastery. Preview task state resets on Run until the next topic adds persistence; saved editor source and challenge drafts already persist independently. Test duplicate labels, toggling twice, deleting a filtered row and clearing the last task.'
    ],
    steps:[['Add top-level task/input state and validated form submission.','Use a functional updater to preserve multiple adds, including duplicate labels and literal markup-looking text.'],['Implement ID-based toggle/delete and All/Active/Completed without changing the source array.','Derive counts and both empty states; verify toggling twice and deletion while filtered.']],
    checks:['Valid additions accumulate; whitespace is rejected and successful input clears.','Duplicate identities, toggles, deletes, counts and reversible filters behave correctly.'],
    blanks:['Should a filtered view replace the source tasks array? Answer yes or no.','no','Complete the functional update: setTasks(previous => [...____, newTask]);','previous']
  },
  {
    id:'react-effects-persistence-and-errors',title:'Effects, persistence, and errors',summary:'Restore and migrate local task data, recover errors, and clean up asynchronous effects without accepting stale work.',
    readings:[
      'An effect synchronizes a committed view with an external system. Import useEffect and call it at the top level. Its dependency array lists reactive values read by that effect; React runs cleanup before replacing an effect and when the component unmounts. Do not make the effect callback async: define an async function inside and return an ordinary cleanup function. useRef keeps a mutable value across renders without itself causing a render; it can track request generation or an ordered Promise write queue. Promise.then chains work after the previous operation settles; catch handles rejection. Derived filters remain plain render calculations.',
      'The course supplies asynchronous trainingStorage.getItem/setItem/removeItem for only this workspace. JSON.parse can throw, and valid JSON can have the wrong shape. Validate unique safe IDs, string labels and boolean done values. Migrate a legacy task array into the current {version:2,tasks} envelope, preserving IDs and completion. Reject unsupported versions instead of guessing. Hold edits/saves until restore finishes; never overwrite saved tasks with the initial empty render. Communicate Loading, Empty and Could not restore/save in accessible regions. Retain in-memory edits on save failure; offer an explicit recovery path and retry. Serialize writes so an older write cannot finish last.',
      'Practice async effects with local deterministic task fixtures; they are simulated data, not a live service or account sync. Slow and SlowError complete after Fast. Use an AbortController, pass its signal, abort in cleanup, and also ignore callbacks from a retired effect because cancellation is not always honored. Guard both success and error paths. On a new selection clear old output and announce loading; empty and failure need distinct messages. Unmount/remount must clean up pending work. Keep fixture results separate from the learner’s saved tasks. Host reload, project navigation and schema-1 migration preserve source/checkpoints/mastery; app task-envelope migration is a separate concern.'
    ],
    steps:[['Add guarded startup restore with shape validation and legacy-array migration.','Save a version-2 envelope only after initialization; preserve edits on failed writes and provide recovery feedback.'],['Add the deterministic async fixture panel with loading, empty and error states.','Clean up the effect, retire old callbacks and test Slow→Fast, SlowError→Fast, and hiding the pending panel.','Verify ordered saves, retry/recovery and a fresh Run restoring the same IDs.']],
    checks:['Valid saved tasks restore and additions persist without overwriting startup data.','Legacy migration, invalid/read/write recovery and stale async success/error cleanup preserve the latest intent.'],
    blanks:['Which effect function runs before replacement and on unmount?','cleanup','Complete cleanup cancellation: controller.____();','abort']
  },
  {
    id:'react-testing-and-export',title:'Testing and export',summary:'Run repeatable behavioral smoke tests and export the React dashboard as an independently runnable static snapshot.',
    readings:[
      'A useful smoke test performs an action and asserts visible behavior; printing Passed proves nothing. Use native form and control events, then wait for the expected React commit or async status. Verify literal add, blank rejection, toggle/filter identity and errors. Fixtures make outcomes repeatable; current live data would make these assertions unreliable. A test should fail when a deliberately incorrect implementation drops an add or reports a wrong result. Compilation proves syntax and imports, not task behavior.',
      'Tests temporarily change the dashboard, so save the task state, filter, typed input and persisted snapshot first. Restore them in finally, even if an assertion fails. Block a second smoke run while one is active and avoid interrupting a pending restore or async operation. Wait for cleanup and queued writes before reporting completion. Repeating the test twice must leave the same user data. Report failures in an accessible status and leave the app usable for debugging. Test both a successful storage write and a rejected one without claiming cloud durability.',
      'Use the host Export runnable ZIP action on the selected React project. The root index.html contains compiled React and local assets; source/ contains exact editable originals and README.md explains serving them. Extract and run a static HTTP server, such as python -m http.server 8080, then open localhost:8080. Source JSX files alone do not rebuild the compiled root: continue in Project Code and export again. Test the exported page independently, including reload persistence and narrow layout. The export contains no course session, mastery, saved training map or host credentials. This is preparation for static deployment, not publication or account synchronization.'
    ],
    steps:[['Implement #run-react-smoke with real interaction/assertion checks and accessible #react-smoke-status.','Make a wrong result fail instead of reporting success unconditionally.'],['Restore task/input/filter/storage state in finally and verify two repeat runs.','Describe source/ versus compiled root, use Export runnable ZIP, serve the extracted archive and verify add/filter/reload independently.']],
    checks:['Smoke runs actual observable assertions and reports failures for incorrect behavior.','Repeat runs restore prior data and the handoff explains how to serve and rebuild the runnable React export.'],
    blanks:['Does editing source/App.jsx alone rebuild exported root index.html? Answer yes or no.','no','Complete unconditional cleanup: try { await runChecks(); } ____ { await restore(); }','finally']
  }
];
const partPath = (topic:string,part:string,id:string) => `projects/${projectId}/topics/${topic}/${part}/${id}`;
export const reactTopics: Topic[] = details.map((detail,index) => {
  const id=detail.id, full=reactReferenceByTopic[id], basic=reactBasicReferenceByTopic[id];
  const activities: Activity[] = detail.readings.flatMap((explanation,n) => {
    const readId=`${id}-read-${n+1}`;
    const reading: Activity={id:readId,path:partPath(id,'activities',readId),title:`${detail.title}: ${['understand','trace the change','verify independently'][n]}`,kind:'reading',order:n*2+1,objective:detail.summary,outline:explanation,explanation,instructions:['Trace the described flow before editing.','Explain which value owns the visible result.'],hints:['Use the previous project to compare the same user requirement.'],estimatedMinutes:8};
    if(n===2)return [reading];
    const guidedId=`${id}-guided-${n+1}`;
    return [reading,{id:guidedId,path:partPath(id,'activities',guidedId),title:`${detail.title}: ${n===0?'first increment':'complete the behavior'}`,kind:'guided-coding' as const,order:n*2+2,objective:detail.checks[n],outline:explanation,explanation,instructions:['Continue your existing React project; merge the new increment and preserve your notes and working features.',...detail.steps[n],'Run and inspect the stated behavior, then Check. References are comparisons, not automatic replacements.'],starterFiles:reactStarter(id,n===0?'apply':'debug'),referenceSolution:n===0?basic:full,validation:{observable:detail.checks[n],checks:detail.checks.slice(0,n+1)},hints:['Keep the stated selector contract so behavior is observable.','Inspect the first failing behavior before changing unrelated code.'],estimatedMinutes:20}];
  });
  const blanks: Blank[] = (['conceptual','code'] as const).map((kind,n)=>({id:`${id}-blank-${n+1}`,path:partPath(id,'blanks',`${id}-blank-${n+1}`),kind,prompt:detail.blanks[n*2],acceptedAnswers:[detail.blanks[n*2+1]],explanation:n===0?detail.readings[0]:detail.readings[1],normalization:{trim:true,collapseWhitespace:kind==='conceptual',caseSensitive:kind==='code',lineEndings:'lf'}}));
  const challenges: Challenge[] = (['apply','debug','combine'] as const).map((kind,n)=>({id:`${id}-${kind}`,path:partPath(id,'challenges',`${id}-${kind}`),title:['Apply the first increment','Repair a behavior regression','Combine independently'][n],order:n+1,objective:n===0?detail.checks[0]:detail.summary,starterFiles:reactStarter(id,kind),instructions:[n===1?'Find and repair the seeded defect; use the visible failure to locate its cause.':n===2?'Implement the complete topic contract in this independent workspace.':'Complete the first taught increment in this independent workspace.',...detail.steps[n===0?0:1],'Check the examples and run the behavior grader.'],examples:[detail.checks[0],...(n===0?[]:[detail.checks[1]])],behaviorValidation:{observable:n===0?detail.checks[0]:detail.summary,checks:detail.checks.slice(0,n===0?1:2)},hints:['Trace one interaction and inspect the current state.','Compare the relevant reading and reference only after a concrete attempt.'],reference:activities.map(a=>a.id),referenceSolution:n===0?basic:full}));
  return {id,path:`projects/${projectId}/topics/${id}`,projectId,title:detail.title,order:index+1,status:'published',summary:detail.summary,prerequisiteTopicIds:index?[details[index-1].id]:[],activities,blanks,assessmentQuestions:reactQuestions(id),challenges,gate:{type:'topic-gate',guidedActivityIds:activities.filter(a=>a.kind==='guided-coding').map(a=>a.id),requiredChallengeIds:challenges.map(c=>c.id),minimumDistinctCorrectQuestionIds:10,revealedAnswerEarnsCredit:false,requiresFreshEquivalentAfterReveal:true,wrongAnswerResetsProgress:false,retryPolicy:'exhaust-unseen-before-missed'}};
});
