import type { Files } from '../contracts';
import type { Activity, Blank, Challenge, Topic } from './schema';
import { todoPhase3Questions } from './todoPhase3Questions';
import { filterStarter, fullFiles, layoutFiles, planningFiles, stackFiles, storageFiles, storageStarter, testExportFiles, testExportStarter } from './todoPhase3References';

const projectId = 'vanilla-todo';
const conceptual = { trim: true as const, collapseWhitespace: true, caseSensitive: false, lineEndings: 'lf' as const };
const code = { trim: true as const, collapseWhitespace: false, caseSensitive: true, lineEndings: 'lf' as const };
type Source = { reference: Files; starter: Files; observable: string; checks: string[] };
const source: Record<string, Source> = {
  'todo-scope-and-user-flows': { reference: planningFiles, starter: { ...planningFiles, 'main.js': `document.querySelector('#flow-summary').textContent = 'Plan the user flow.';` }, observable: 'A concise user-flow plan names the core task actions and failure states.', checks: ['#flow-summary names add, complete, delete, empty, and filter behavior.', '#flow-list separately describes add, complete by id, and delete by id.', 'Original add, toggle, delete and duplicate-label identity behavior still works.'] },
  'todo-web-stack-and-file-plan': { reference: stackFiles, starter: { ...stackFiles, 'index.html': stackFiles['index.html'].replace('<ul id="file-plan"><li>index.html: semantic structure</li><li>styles.css: visual rules</li><li>model.js: task data operations</li><li>main.js: DOM events and rendering</li></ul>', '<ul id="file-plan"><li>Files go here.</li></ul>') }, observable: 'The selected vanilla stack has an explicit file responsibility map.', checks: ['#file-plan contains index.html, styles.css, model.js, and main.js.', 'Each file entry explains its own distinct responsibility.', 'Original add, toggle, delete and duplicate-label behavior survives the file refactor.'] },
  'todo-setup-and-static-layout': { reference: layoutFiles, starter: { ...layoutFiles, 'index.html': fullFiles['index.html'].replace('id="task-list"', 'id="tasks"') }, observable: 'An accessible static Todo shell exposes the selectors used by later behavior.', checks: ['form#todo-form, input#task-input, ul#task-list, and #task-count exist.', 'Submitting the empty shell does not navigate away.', 'The initial count is 0 of 0 complete.', 'The visible label connects to task-input; error and count/empty regions have their stated alert/live semantics.', 'Filter controls are non-submit buttons and original CRUD still works. Review narrow layout manually.'] },
  'todo-filter-empty-and-input-errors': { reference: fullFiles, starter: filterStarter, observable: 'Filters derive visible rows from current tasks and communicate empty or invalid input.', checks: ['Whitespace input creates no row and shows #input-error.', 'All, active, and completed controls filter without deleting hidden tasks.', '#empty-state distinguishes no tasks from no matching tasks.'] },
  'todo-storage-and-recovery': { reference: storageFiles, starter: storageStarter, observable: 'Tasks save through the asynchronous training-storage adapter and recover safely.', checks: ['Reads and writes use await window.trainingStorage with the tasks key.', 'A saved task returns after a simulated reload.', 'Missing, malformed, and failed storage leave a usable empty list with a status message.'] },
  'todo-testing-and-export': { reference: testExportFiles, starter: testExportStarter, observable: 'A learner can run a visible smoke check and receive an accurate vanilla-module export handoff.', checks: ['#run-smoke-test produces a passing result in #test-results.', '#prepare-export explains keeping the four relative-module files together.', 'The message names a local static server requirement for browser modules.'] },
};
const topicBlanks: Record<string, Array<Omit<Blank, 'path'>>> = {
  'todo-scope-and-user-flows': [{ id: 'scope-observable-contract', kind: 'conceptual', prompt: 'A user flow should end with what kind of result: an observable page state or an internal implementation detail?', acceptedAnswers: ['observable page state', 'an observable page state'], explanation: 'A flow is testable when it ends in a user-visible result such as a row, count, or message.', normalization: conceptual }, { id: 'scope-filter-state', kind: 'code', prompt: 'Select the Completed view without changing tasks: filter = ____;', acceptedAnswers: ["'completed'", '"completed"'], explanation: 'The filter is a view choice; it does not remove task records.', normalization: code }],
  'todo-web-stack-and-file-plan': [{ id: 'stack-module-boundary', kind: 'conceptual', prompt: 'Which file owns pure task-array operations in this file plan?', acceptedAnswers: ['model.js', 'model'], explanation: 'model.js can transform task data without reaching into the DOM.', normalization: conceptual }, { id: 'stack-relative-import', kind: 'code', prompt: 'main.js and model.js are siblings. Complete: import { addTask } from ____;', acceptedAnswers: ["'./model.js'", '"./model.js"'], explanation: 'The leading ./ makes model.js a relative file beside main.js.', normalization: code }],
  'todo-setup-and-static-layout': [{ id: 'layout-label-purpose', kind: 'conceptual', prompt: 'Complete the attribute name that connects a label to input#task-input: label ____ equals task-input.', acceptedAnswers: ['for'], explanation: 'A label for="task-input" names the control whose id is task-input.', normalization: conceptual }, { id: 'layout-prevent-submit', kind: 'code', prompt: 'Complete the form handler: event.____();', acceptedAnswers: ['preventDefault'], explanation: 'The handler prevents browser navigation so the Todo can validate and render.', normalization: code }],
  'todo-filter-empty-and-input-errors': [{ id: 'filter-derived-view', kind: 'conceptual', prompt: 'Should an Active filter delete completed tasks from the main array?', acceptedAnswers: ['no', 'no it should not'], explanation: 'Filtering derives a displayed subset while preserving all task records.', normalization: conceptual }, { id: 'filter-empty-predicate', kind: 'code', prompt: 'Complete the active predicate: tasks.filter(task => ____);', acceptedAnswers: ['!task.done'], explanation: 'Active tasks have done: false, so logical negation selects them.', normalization: code }],
  'todo-storage-and-recovery': [{ id: 'storage-missing-value', kind: 'conceptual', prompt: 'What can await window.trainingStorage.getItem("tasks") return when no value was saved?', acceptedAnswers: ['null'], explanation: 'The adapter returns a string for a saved value or null when the key is missing.', normalization: conceptual }, { id: 'storage-serialize', kind: 'code', prompt: 'Complete the save payload: JSON.____(tasks)', acceptedAnswers: ['stringify'], explanation: 'stringify produces the bounded text value accepted by the storage adapter.', normalization: code }],
  'todo-testing-and-export': [{ id: 'test-observed-behavior', kind: 'conceptual', prompt: 'A behavior test should check what a user can observe after an interaction. True or false?', acceptedAnswers: ['true'], explanation: 'Observed DOM states and messages are stronger evidence than a source-text match.', normalization: conceptual }, { id: 'export-file-map', kind: 'code', prompt: 'Complete the relative module filename: import { addTask } from "./____";', acceptedAnswers: ['model.js'], explanation: 'The exported main.js must keep its relative reference to model.js.', normalization: code }],
};
function path(topic: string, part: 'activities' | 'blanks' | 'challenges', id: string) { return `projects/${projectId}/topics/${topic}/${part}/${id}`; }
function guided(topicId: string, id: string, title: string, objective: string, text: string, value: Source): Activity { return { id, path: path(topicId, 'activities', id), title, kind: 'guided-coding', order: 0, objective, outline: text, estimatedMinutes: 14, explanation: text, instructions: ['Open the project files already saved from the previous topic and add this behavior without resetting compatible work.', 'Keep the listed DOM ids and file names as contracts; later steps and tests rely on them.', 'Run the preview, perform the stated visible interaction, then use Check to observe the same behavior in a fresh frame.'], starterFiles: value.starter, validation: { observable: value.observable, checks: value.checks }, hints: ['Work from current state to the DOM rather than treating rendered rows as your source of truth.', 'Make the smallest change that produces a visible, testable result.'], referenceSolution: value.reference }; }
function reading(topicId: string, id: string, title: string, objective: string, explanation: string): Activity { return { id, path: path(topicId, 'activities', id), title, kind: 'reading', order: 0, objective, outline: explanation, estimatedMinutes: 7, explanation, instructions: ['Read the contract and trace one user action from input through state to the visible result.', 'Name one failure state before implementation so its message can be checked rather than guessed.', 'Keep this plan beside the current project draft; do not replace working files to begin a later step.'], hints: ['A contract says what can be observed, not how the code must be spelled.', 'Keep responsibilities small: data operation, event handling, rendering, and persistence are separate jobs.'] }; }
function debugStarter(topicId: string, files: Files): Files {
  const next = { ...files };
  if (topicId.includes('scope')) next['index.html'] = next['index.html'].replace(/empty, invalid-input, and filtered results\./, 'only normal results.');
  else if (topicId.includes('web-stack')) next['index.html'] = next['index.html'].replace('model.js: task data operations', 'model.js: visual styles');
  else if (topicId.includes('static-layout')) next['index.html'] = next['index.html'].replace('for="task-input"', 'for="wrong-input"');
  else if (topicId.includes('filter-empty')) next['main.js'] = next['main.js'].replace('const shown = filteredTasks(tasks, filter);', 'const shown = tasks = filteredTasks(tasks, filter);');
  else if (topicId.includes('storage')) next['main.js'] = next['main.js'].replace('restoreTasks(JSON.parse(raw))', 'JSON.parse(raw)');
  else next['main.js'] = next['main.js'].replace("results.textContent = 'Smoke test passed:", "results.textContent = 'Smoke test failed:");
  return next;
}
function challenges(topicId: string, value: Source): Challenge[] {
  const titles = ['Apply the first increment', 'Repair a regression', 'Combine the complete feature'];
  return ['apply', 'debug', 'combine'].map((suffix, index) => ({
    id: `${topicId}-${suffix}`, path: path(topicId, 'challenges', `${topicId}-${suffix}`), title: titles[index], order: index + 1,
    objective: index === 0 ? lessonDetails[topicId].objectives[0] : index === 1 ? lessonDetails[topicId].debug : value.observable,
    starterFiles: index === 0 ? value.starter : index === 1 ? debugStarter(topicId, value.reference) : { ...value.reference, 'main.js': '// Implement the feature independently using the supplied HTML and model module.\n' },
    instructions: [index === 0 ? 'Apply the first guided increment in this separate draft.' : index === 1 ? lessonDetails[topicId].debug : 'Implement the full contract independently. Preserve add, toggle, delete and duplicate-label behavior while combining this feature.', ...lessonDetails[topicId].steps[index === 0 ? 0 : 1], 'Use Run to reproduce the example, then Check challenge. Your project draft remains separate.'],
    examples: index === 0 ? lessonDetails[topicId].examples.slice(0, 1) : lessonDetails[topicId].examples,
    behaviorValidation: { observable: index === 0 ? lessonDetails[topicId].objectives[0] : value.observable, checks: index === 0 ? lessonDetails[topicId].basicChecks : value.checks },
    hints: [index === 1 ? 'Locate the first state or DOM value that differs from the expected example. Repair the cause rather than changing the expected result.' : lessonDetails[topicId].hints[0], lessonDetails[topicId].hints[1]],
    reference: [`${topicId}-read-1`, `${topicId}-guided-1`, `${topicId}-read-2`, `${topicId}-guided-2`, `${topicId}-read-3`], referenceSolution: value.reference,
  }));
}
function topic(id: string, title: string, order: number, prerequisiteTopicIds: string[], summary: string): Topic {
  const detail = lessonDetails[id]; const readings = detail.readings;
  const value = source[id]; const repairStep: Source = { ...value, starter: debugStarter(id, value.reference) }; const activities = [reading(id, `${id}-read-1`, `${title}: decide the contract`, 'Make the learner-visible contract explicit before writing code.', readings[0]), guided(id, `${id}-guided-1`, `${title}: guided first increment`, 'Add the smallest observable increment while preserving the continuing Todo draft.', readings[0], value), reading(id, `${id}-read-2`, `${title}: inspect the transition`, 'Explain why the first increment works and identify its edge cases.', readings[1]), guided(id, `${id}-guided-2`, `${title}: guided verification and repair`, 'Repair a focused regression and verify its negative case.', readings[1], repairStep), reading(id, `${id}-read-3`, `${title}: prepare independent work`, 'Plan the apply, debugging, and combination challenges.', readings[2])].map((activity, index) => ({ ...activity, order: index + 1, ...(activity.kind === 'guided-coding' ? { objective: detail.objectives[index === 1 ? 0 : 1], instructions: ['Continue your existing project files. Save a checkpoint before changing working behavior.', ...detail.steps[index === 1 ? 0 : 1], 'Use Check guided code to verify this increment in an isolated copy.'], hints: detail.hints, validation: { observable: value.observable, checks: index === 1 ? detail.basicChecks : value.checks } } : { instructions: ['Trace the example against your current files.', 'Write down the expected state and visible result before continuing.'] }) }));
  const blanks = topicBlanks[id].map(blank => ({ ...blank, path: path(id, 'blanks', blank.id) }));
  return { id, path: `projects/${projectId}/topics/${id}`, projectId, title, order, status: 'published', summary, prerequisiteTopicIds, activities, blanks, assessmentQuestions: todoPhase3Questions(id), challenges: challenges(id, value), gate: { type: 'topic-gate', guidedActivityIds: [`${id}-guided-1`, `${id}-guided-2`], requiredChallengeIds: [`${id}-apply`, `${id}-debug`, `${id}-combine`], minimumDistinctCorrectQuestionIds: 10, revealedAnswerEarnsCredit: false, requiresFreshEquivalentAfterReveal: true, wrongAnswerResetsProgress: false, retryPolicy: 'exhaust-unseen-before-missed' } };
}

type LessonDetail = { readings: [string, string, string]; objectives: [string, string]; steps: [string[], string[]]; examples: string[]; basicChecks: string[]; debug: string; hints: string[] };
const lessonDetails: Record<string, LessonDetail> = {
  'todo-scope-and-user-flows': {
    readings: [
      'The pilot already adds, toggles, and deletes tasks. Now turn that working experiment into a small product plan. Our user wants to capture a task, see unfinished work, mark one task complete, and remove a task. Scope is a boundary: local browser data and a single person are enough here; accounts, collaboration, and payments would introduce a server and are deferred.\n\nA user flow is action → state transition → visible result. Example: submit "  Read  " → append one {id, text: "Read", done: false} record → show Read and 0 of 1 complete. Pressing Enter and clicking Add must take the same submit path. A good acceptance example states both the starting state and the expected result.',
      'Plan failure paths before adding more code. Whitespace submission should keep the existing task array and show a correction message. An empty source list means "No tasks yet"; a nonempty list with no matching filter means "No tasks match this filter". Clicking Active changes a separate filter variable; it must not mutate done flags or delete hidden records.\n\nPut a visible planning section beside the working app: p#flow-summary names add, complete, delete, empty, invalid-input, and filtering; ul#flow-list gives three action → result examples. This is a reviewable specification, not an automatically generated claim about correctness. The combine check also exercises your original CRUD behavior.',
      'Decompose implementation into small acceptance steps: preserve CRUD, add semantic feedback regions, derive filters, restore validated storage, then test and export. Keep a happy path and a counterexample for every feature. Duplicate labels are allowed, so deleting one "Read" must preserve the other record by id. A filtering plan is incomplete if it says nothing about hidden tasks.\n\nBefore the challenges, read your plan as another developer: can they predict what happens when input is blank, a duplicate is toggled, or the last task is removed? Keep those examples visible rather than replacing your working app with a planning-only page.'
    ],
    objectives: ['Add a readable flow summary alongside the existing Todo.', 'Specify invalid, empty, and filtered outcomes with concrete action/result examples.'],
    steps: [['In index.html add a section with h2, p#flow-summary and ul#flow-list; keep the existing form/list and module script.', 'Describe add, complete, and delete in #flow-summary. Add list items with the action and its result.'], ['Extend #flow-summary to distinguish empty, invalid-input and filtered states.', 'Ensure #flow-list separately describes adding trimmed text, completing one record by id, and deleting one record by id.', 'Run the existing Todo: add two matching labels, toggle only one, then delete the other. Keep both your plan and working behavior.']],
    examples: ['Submit Read once: one record, 0 of 1 complete.', 'Submit whitespace: no new record; Active with only completed records: no matching tasks.'], basicChecks: ['The summary and list describe add, complete and delete.'], debug: 'The supplied summary only describes normal outcomes. Restore its missing empty, invalid-input and filter requirements while keeping CRUD working.', hints: ['Use textContent or literal HTML prose for the plan; the plan must remain visible alongside the app.', 'A flow names a trigger, the state that changes, and an observable result.'],
  },
  'todo-web-stack-and-file-plan': {
    readings: [
      'Compare three choices against this product. Plain HTML/CSS/JavaScript modules need little setup and expose each state transition. Vite with vanilla JavaScript adds a local development server and a production bundler, useful for imports and assets. React adds components, JSX and a framework state model that can help a larger repeated UI but adds concepts here. Choose vanilla for this Todo; the course host already supplies compilation, so no npm command runs inside the preview.\n\nVite is a build tool, not a database or account backend. JSX needs a transformation step; a plain browser script cannot parse it directly. Our current project has no server endpoints, CDN imports, or secret keys.',
      'Keep index.html for semantic markup, styles.css for presentation, model.js for task-array operations, and main.js for current state, event wiring and rendering. Another valid design can split state and render modules further, but one clear owner per responsibility avoids circular update loops. Add ul#file-plan with one li per file and its responsibility. Keep the earlier flow plan.\n\nUse export function addTask(...) in model.js and import { addTask } from "./model.js" in its sibling main.js. Named imports must match the exported names; import { addTask as createTask } gives an export a local alias using as. Paths resolve from the importing file: src/dom/render.js reaches src/state.js with ../state.js. In index.html use a script with type="module" and a relative src. Browser module scripts wait for markup to be parsed.',
      'Debug a file boundary before rewriting a feature. A missing-module error usually points to a path or filename; a missing-export error points to a name. A wrong task transition belongs in the model, while an absent message belongs in render. A stylesheet selector must match the HTML exactly.\n\nThe project is statically deployable because its runtime needs browser files only. A Vite build would deploy generated output, not an arbitrary src folder. Later this course exports a compiled index.html plus original source files. Keep local module paths portable and preserve the pilot source while documenting decisions.'
    ],
    objectives: ['Document the four file responsibilities in the continuing app.', 'Verify module boundaries and retain a working CRUD app beside the file plan.'],
    steps: [['Add ul#file-plan to index.html, keeping the flow section and Todo controls.', 'Use one li each: index.html semantic structure; styles.css visual rules; model.js task data operations; main.js DOM events and rendering.'], ['Inspect or create model.js using New file. Move reusable task-array operations there without moving DOM queries into it.', 'Import the named operations from ./model.js in main.js. Keep one submit handler and a module script in index.html.', 'Run add/toggle/delete after the refactor; the visible behavior must remain unchanged.']],
    examples: ['model.js: task data operations; main.js: DOM events and rendering.', 'Move a model function: the same add/toggle/delete sequence should still work.'], basicChecks: ['The four filenames appear in their own file-plan entries.'], debug: 'The supplied model.js entry wrongly assigns visual styling to the data module. Repair that responsibility and check all four entries against the running project.', hints: ['Exported identifiers are case sensitive; import braces name the exact exports.', 'Keep the direction clear: event handler → state operation → render.'],
  },
  'todo-setup-and-static-layout': {
    readings: [
      'Setup means proving the structure before adding the next feature. In this browser editor use New file for missing paths; Save checkpoint protects the current source. Keep the working CRUD from the pilot. The source consists of index.html, styles.css, model.js and main.js. The module script in index.html loads main.js after markup. The host Run button compiles this project; there is no terminal inside the learner frame.\n\nAudit the stable contract: form#todo-form, input#task-input, ul#task-list, p#task-count. Add p#input-error, p#empty-state and div#filter-controls with buttons whose data-filter values are all, active and completed. These empty regions prepare later behavior rather than pretending it already exists.',
      'A visible label with for="task-input" connects to the input id. Keep ids unique across the whole document. Clicking it should focus the field. A button inside a form defaults to submit, so filter and delete controls need type="button". Handle adding on form submit and call event.preventDefault(); this supports Enter and click without navigating.\n\nUse li children in the task ul. Give validation feedback role="alert" and counts/empty feedback aria-live="polite" so changes can be announced without moving focus. Keep messages visible in text rather than using color alone. Keep the input focused for the next task after a successful add.',
      'Separate presentation from state. In styles.css use a bounded main width, padding and flexible rows; flex-wrap: wrap lets controls move to a new line at narrow widths. Long task labels should wrap rather than force horizontal scrolling. Preserve browser focus outlines so keyboard users can see where they are.\n\nRun the page, click the label, press Tab through input and buttons, add via Enter, and shrink the preview. Initial source state is empty, so the count is 0 of 0 complete. The guided second check verifies labels and live regions; the combined challenge also rechecks add/toggle/delete.'
    ],
    objectives: ['Audit the Todo selector and form contract without removing CRUD.', 'Add accessible labels, live feedback regions and non-submit filter controls.'],
    steps: [['Keep the existing Todo script. Verify form#todo-form, input#task-input, ul#task-list and p#task-count match the JavaScript queries.', 'Confirm a submit handler prevents navigation and the empty initial count is 0 of 0 complete.'], ['Associate the visible New task label with task-input; use role="alert" on #input-error and aria-live="polite" on #task-count and #empty-state.', 'Add filter controls with type="button" and data-filter="all", "active", "completed". Keep them separate from add submission.', 'In styles.css allow controls and long labels to wrap; test keyboard focus and a narrow preview.']],
    examples: ['Click New task: the input receives focus.', 'Press Enter after typing Read: one row is added without navigation.'], basicChecks: ['Required selectors and initial count exist; submit does not navigate.'], debug: 'The label points at wrong-input rather than task-input. Reproduce the broken label click and fix the association without changing its visible text.', hints: ['for and id values must be identical; a placeholder does not replace a label.', 'Use flex-wrap and overflow-wrap for responsive content instead of a fixed page width.'],
  },
  'todo-filter-empty-and-input-errors': {
    readings: [
      'Keep one tasks array and a separate filter string initialized to "all". Derive shown rows on each render: all → tasks, active → tasks.filter(task => !task.done), completed → tasks.filter(task => task.done). Array.filter returns a new array; never assign the filtered projection back to tasks. That would destroy hidden records.\n\nUse #filter-controls buttons with data-filter="all", "active", "completed". Their click handler reads button.dataset.filter, updates only filter, then calls render. Complete and delete handlers still operate on stable task ids, not positions in the filtered list.',
      'Validate input before changing state: const text = input.value.trim(); if (!text) { show an error; return; }. Invalid input preserves existing records and keeps the field available for correction. A valid add clears #input-error and the input field. textContent renders labels literally, so typed tags remain text.\n\nRender #empty-state from two conditions in order. If tasks.length is zero, show "No tasks yet. Add one above." Otherwise if shown.length is zero, show "No tasks match this filter." Otherwise clear the message. The total count always describes all records, not only visible ones.',
      'Trace an edge sequence: add One and Two, complete One, select Active (Two), select Completed (One), delete One, then return to All (Two). The count is 0 of 1 complete. If changing filters loses Two, find where the projection overwrote source state. If an old error remains after a valid add, clear it in the success path.\n\nYour independently combined feature must preserve duplicate-label identity and rerender counts/messages after every add, toggle, delete and filter change. Use the first failing observable result to locate the wrong transition before editing multiple functions.'
    ],
    objectives: ['Add invalid-input feedback and a non-destructive Active view.', 'Complete All/Completed filters, contextual empty messages and filtered deletion.'],
    steps: [['Add the filter controls and feedback regions from the layout lesson if missing.', 'Track filter separately; render active rows with !task.done. Reject whitespace and show #input-error without adding a record.'], ['Implement All and Completed and clear a prior input error after a valid add.', 'Render initial-empty and no-match messages from source size then visible size.', 'Delete and toggle by id within a filtered view, derive the total completed count from all tasks, and rerender on each transition.']],
    examples: ['Add One and Two; complete One; Active shows Two.', 'Completed shows One; delete it; All still shows Two and 0 of 1 complete.'], basicChecks: ['Whitespace shows an error without adding a task; Active shows only incomplete rows.'], debug: 'The supplied render function assigns the visible projection back to tasks. Switching filters loses hidden records. Repair the destructive assignment and verify filtered deletion.', hints: ['const shown = filteredTasks(tasks, filter) computes a projection without replacing tasks.', 'Keep the empty-state check in render so every transition updates it.'],
  },
  'todo-storage-and-recovery': {
    readings: [
      'Source autosave and Todo data persistence are different. The editor saves your program; variables inside a fresh Run start again. The opaque iframe cannot use host localStorage. It receives only window.trainingStorage with getItem, setItem and removeItem. Each method returns a Promise: a future value or failure. An async function can await that Promise; try/catch around await handles rejection. getItem("tasks") resolves to a string or null.\n\nSerialize arrays with JSON.stringify(tasks). Parse stored strings with JSON.parse(raw), then validate them: valid JSON syntax does not guarantee valid task records. For null, use an empty array directly. JSON.parse(null) returns null, which still is not an array. Never assume parsing proves shape.',
      'Restore before enabling edits. Disable the input and Add button until the awaited read and validation finish, otherwise a late read can overwrite a newly added task. In model.js validate an array of records with unique positive safe integer ids, nonblank string text and boolean done. Set the next id above the largest restored id so a fresh task cannot collide with saved ones. Catch malformed JSON, invalid shapes and read failures; show #storage-status and retain a usable empty app.\n\nAfter add/toggle/delete, render current state immediately, capture a JSON snapshot and queue writes in order using a Promise chain. Await each setItem before saying Saved. On failure keep the visible task list and say it was not saved. This small queue prevents an older write from finishing after a newer one.',
      'The host storage capability is scoped to this project or challenge: at most 32 keys, 16,384 characters per value, 65,536 serialized characters total and 30 requests per second. The tasks key is enough here. Unsupported keys, quota/conflict errors and timeouts reject; nothing is cloud synced. Clear preview data resets only this workspace storage and asks first. JSON session backups include training data; runnable exports start with empty data on their own origin.\n\nVerify Run → add → wait for Saved → Run again, then reload the host and Run. Check malformed text, valid JSON of the wrong shape, duplicate ids, and write failure using separate fixtures. Do not silently erase a corrupt stored value on load; let the user recover and save a new valid state deliberately.'
    ],
    objectives: ['Restore valid tasks and persist new state through awaited scoped storage.', 'Recover invalid data and failed saves while preserving current work and identity.'],
    steps: [['Add #storage-status and import a restoreTasks validator from model.js. Await getItem("tasks") inside async restore(). Handle null separately.', 'Validate ids/text/done, advance the id counter, and render restored tasks. Disable input until restore finishes.', 'On add/toggle/delete, capture JSON.stringify(tasks), queue setItem("tasks", snapshot), and report success only after it resolves.'], ['Wrap parsing, shape validation and reads in try/catch; recover to empty state with an honest status message.', 'Catch writes without deleting in-memory tasks. Keep the write queue usable after failure.', 'Run twice with duplicate labels and restored ids; toggle/delete just one. Reload the host, verify saved source does not autorun, then Run to restore tasks.']],
    examples: ['Saved id 7 returns on Run; the next added task has a different id.', 'Malformed JSON yields an empty usable app; a rejected write leaves the new task visible and reports not saved.'], basicChecks: ['Valid data restores; an add writes tasks using the same key.'], debug: 'The supplied restore bypasses the validated restoreTasks function. Wrong-shaped JSON reaches rendering and restored ids can collide. Restore validation and identity initialization.', hints: ['A Promise is not the stored string: await the operation inside an async function.', 'Capture each snapshot before queuing its write, and keep render independent of save success.'],
  },
  'todo-testing-and-export': {
    readings: [
      'A smoke test is a small set of assertions on real behavior. Printing "passed" proves nothing. Define assert(condition, message) to throw Error(message) when false; run actions inside try/catch and report failure from the caught error. A test library may spell the same idea expect(actual).toBe(expected), but this project can use ordinary JavaScript.\n\nBegin with a known state, submit a unique text through the actual form, inspect rendered labels and live checkbox.checked properties, and await persistence before inspecting saved data. A test that reads only a private tasks variable can miss a broken renderer. Test cleanup must restore the prior task state, filter and storage so testing never destroys user work.',
      'Add #run-smoke-test and #test-results. Disable repeated test runs while one is active. Assert that valid add changes the row count, toggle changes only the selected record, and the saved snapshot contains the transition. Requery the DOM after render; a detached checkbox still remembers values but no longer proves the visible app is correct. Keep a failure message if a save fails instead of falsely reporting success.\n\nRegression tests reuse the earlier cases: blank input, literal text, duplicate labels, filtered deletion, empty view, malformed data and reload. A fixture is a known starting state for one test. Reset fixtures in isolated test frames rather than assuming whatever the prior run left behind.',
      'Use Export runnable ZIP in the host footer. It compiles a copy of your current draft into a self-contained root index.html and includes exact originals under source/ plus README.md. The ZIP contains no learner progress or saved tasks. Extract it; with Python installed, run python -m http.server 8080 in the extracted folder and open http://localhost:8080. Any static HTTP server works. The course does not execute a terminal for you.\n\nThe export adapter uses namespaced browser localStorage on the exported site origin. For edits, continue the original files in this editor and export again; changing source/ alone does not rebuild index.html. Deployment preparation means serving the root bundle on a static host and checking the actual URL: assets, add/filter/error flows, keyboard layout, console, and reload persistence. No website is published in this phase. A successful compilation is not a behavior-test pass.'
    ],
    objectives: ['Run actual smoke assertions against the working persisted Todo.', 'Add an accurate export handoff and prove tests detect a regression without losing work.'],
    steps: [['Keep the storage app. Add #run-smoke-test and #test-results to index.html.', 'Capture prior tasks/filter/storage, run real add and toggle interactions, await writes, and assert visible and saved results.', 'Report passed only after all assertions; report errors honestly and restore captured state in finally.'], ['Add #prepare-export and #export-status with the four source filenames and a local static server instruction.', 'Run the smoke check twice with existing data and a selected filter; original user work should remain.', 'Use the host Export runnable ZIP, extract, serve and verify the bundle. Keep source files and JSON session backup for different purposes.']],
    examples: ['A functioning app reports passed after add/toggle/save assertions and restores its prior data.', 'Break add behavior: the smoke test reports failed. The exported root index.html runs on a separate static origin.'], basicChecks: ['Clicking the smoke control performs actual assertions and reports their result.'], debug: 'The supplied smoke result labels successful assertions as failed. Trace whether the assertions or the reporting branch is wrong; repair the status and verify a genuinely broken add still fails.', hints: ['Await state writes before testing storage, and requery the current rendered row after every render.', 'The host creates the runnable ZIP; the learner export control explains the handoff and does not itself download or publish a site.'],
  },
};

export const todoPhase3Topics: Topic[] = [
  topic('todo-scope-and-user-flows', 'Scope and user flows', 2, ['todo-dom-events-and-task-state'], 'Turn the CRUD pilot into a precise product plan with observable outcomes and scope boundaries.'),
  topic('todo-web-stack-and-file-plan', 'Web stack and file plan', 3, ['todo-scope-and-user-flows'], 'Choose vanilla modules deliberately and separate markup, styles, task operations and DOM wiring.'),
  topic('todo-setup-and-static-layout', 'Setup and static layout', 4, ['todo-web-stack-and-file-plan'], 'Prepare accessible, responsive controls and feedback regions while preserving working CRUD.'),
  topic('todo-filter-empty-and-input-errors', 'Filters, empty states, and input errors', 5, ['todo-setup-and-static-layout'], 'Derive reversible views and explain invalid input and empty results.'),
  topic('todo-storage-and-recovery', 'Storage and recovery', 6, ['todo-filter-empty-and-input-errors'], 'Use scoped asynchronous storage with validated restoration and honest failure recovery.'),
  topic('todo-testing-and-export', 'Testing and export', 7, ['todo-storage-and-recovery'], 'Run real behavior checks, preserve test state and prepare a runnable static project handoff.'),
];
