import type { AssessmentQuestion } from './schema';

type Category = AssessmentQuestion['reasoningCategory'];
type Kind = AssessmentQuestion['kind'];

type Spec = {
  slug: string;
  category: Category;
  group: string;
  kind: Kind;
  prompt: string;
  answers: string[];
  feedback: string;
};

function makeQuestion(topicId: string, spec: Spec): AssessmentQuestion {
  const id = `todo-phase3-${topicId.replace(/^todo-/, '')}-q-${spec.slug}`;
  return {
    id,
    identity: id,
    path: `projects/vanilla-todo/topics/${topicId}/questions/${id}`,
    prompt: spec.prompt,
    kind: spec.kind,
    reasoningCategory: spec.category,
    equivalenceGroup: spec.group,
    acceptedAnswers: spec.answers,
    misconceptionFeedback: spec.feedback,
    reviewed: true,
  };
}

function bank(topicId: string, specs: Spec[]): AssessmentQuestion[] {
  return specs.map(spec => makeQuestion(topicId, spec));
}

const scopeQuestions: Spec[] = [
  { slug: 'empty-add-count', category: 'prediction', group: 'scope-add-flow', kind: 'conceptual', prompt: 'The initial task list is empty. The user submits “Buy milk” once, then submits three spaces. How many task records should exist?', answers: ['1', 'one'], feedback: 'The valid submission creates one record; the whitespace-only submission is rejected without changing the list.' },
  { slug: 'toggle-then-filter', category: 'prediction', group: 'scope-filter-flow', kind: 'conceptual', prompt: 'A, B, and C start incomplete. The user marks B complete and selects Active. Which labels should remain visible, in order?', answers: ['A, C', 'A and C'], feedback: 'Active is a view of incomplete records, so B is hidden while A and C retain their source order.' },
  { slug: 'delete-visible-id', category: 'prediction', group: 'scope-delete-flow', kind: 'conceptual', prompt: 'The source records are A(id 7), B(id 9), and C(id 12). A Completed filter shows only B, and the user deletes it. Which ids remain in source state?', answers: ['7, 12', '7 and 12'], feedback: 'Deleting a visible record removes id 9 from source state; the hidden records are retained.' },
  { slug: 'all-view-after-toggle', category: 'prediction', group: 'scope-filter-flow', kind: 'conceptual', prompt: 'A is incomplete and B is complete. The user selects All, toggles A complete, and stays on All. How many rows should be visible?', answers: ['2', 'two'], feedback: 'All includes both records regardless of completion status.' },
  { slug: 'last-delete-empty', category: 'prediction', group: 'scope-empty-flow', kind: 'conceptual', prompt: 'The source contains exactly one task, which is visible under Active. The user completes it, then selects Completed and deletes it. Should the final list show an empty-state message?', answers: ['yes'], feedback: 'The only source record was deleted, so the empty list state is shown.' },
  { slug: 'invalid-preserves-flow', category: 'prediction', group: 'scope-validation-flow', kind: 'conceptual', prompt: 'There are two tasks. A submission contains only tabs and spaces. Which requirement is satisfied? A) reject invalid input while preserving existing tasks; B) create a blank task so the user can edit it later.', answers: ['A'], feedback: 'Invalid input is a no-op on task state; the user can correct the field without losing prior records.' },
  { slug: 'debug-blank-requirement', category: 'debugging', group: 'scope-validation-flow', kind: 'conceptual', prompt: 'A draft app appends a record before trimming the input, so a spaces-only submission creates a blank row. Choose the repair: A) trim and reject before append; B) append first and hide blank rows.', answers: ['A'], feedback: 'Validation belongs at the input boundary before a record enters state; hiding an invalid record leaves state incorrect.' },
  { slug: 'debug-filter-index', category: 'debugging', group: 'scope-delete-flow', kind: 'conceptual', prompt: 'A filtered view contains B at visible index 0, but deleting index 0 removes A from the source array. Choose the repair: A) delete source index 0; B) delete by the row’s stable id.', answers: ['B'], feedback: 'A filtered index is a position in a projection, not a source identity. Pass the stable record id to deletion.' },
  { slug: 'debug-toggle-all', category: 'debugging', group: 'scope-toggle-flow', kind: 'conceptual', prompt: 'Clicking B’s checkbox marks every task complete. Which implementation is the likely repair? A) map and change only the matching id; B) set every done flag to the clicked value.', answers: ['A'], feedback: 'A toggle transition must target the record whose id came from the clicked row.' },
  { slug: 'debug-empty-derived', category: 'debugging', group: 'scope-empty-flow', kind: 'conceptual', prompt: 'After deleting the last row, the app shows “No tasks yet” only after a page refresh. Choose the repair: A) show it only in the delete handler; B) derive empty-state visibility during render.', answers: ['B'], feedback: 'Render runs after every state transition, so it can consistently derive whether the current visible list is empty.' },
  { slug: 'debug-double-submit', category: 'debugging', group: 'scope-add-flow', kind: 'conceptual', prompt: 'One click creates two identical tasks because both a button click handler and the form submit handler add a record. Choose the repair: A) make submit the single add boundary; B) keep both handlers and deduplicate by text.', answers: ['A'], feedback: 'One form submission path prevents duplicate transitions and keeps keyboard submission equivalent to clicking.' },
  { slug: 'debug-filter-state', category: 'debugging', group: 'scope-filter-flow', kind: 'conceptual', prompt: 'The selected filter changes visually, but rows never change. Which missing transition is most likely? A) store the selected filter and render from it; B) mutate each task’s done flag when a filter button is clicked.', answers: ['A'], feedback: 'A filter is view state. It changes which rows are projected, not the task records themselves.' },
  { slug: 'explain-source-view', category: 'explanation', group: 'scope-filter-flow', kind: 'conceptual', prompt: 'Why keep the full task array while computing a filtered visible array? A) hidden tasks should be deleted to simplify rendering; B) filters are views and should be reversible.', answers: ['B'], feedback: 'Keeping source state lets the user switch filters without losing hidden tasks.' },
  { slug: 'explain-stable-id', category: 'explanation', group: 'scope-delete-flow', kind: 'conceptual', prompt: 'Why does the user flow require a stable id for every task? A) duplicate labels can exist; B) ids automatically sort tasks alphabetically.', answers: ['A'], feedback: 'A stable id identifies one record even when two records have the same label.' },
  { slug: 'explain-invalid-noop', category: 'explanation', group: 'scope-validation-flow', kind: 'conceptual', prompt: 'Why should invalid input leave state unchanged? A) it makes the input value impossible to edit; B) it preserves a predictable transition and existing work.', answers: ['B'], feedback: 'A rejected transition should not create a malformed record or discard valid records.' },
  { slug: 'explain-empty-vs-filter', category: 'explanation', group: 'scope-empty-flow', kind: 'conceptual', prompt: 'Why distinguish “No tasks yet” from “No active tasks”? A) the first describes empty source state and the second describes an empty filtered view; B) the messages are interchangeable decoration.', answers: ['A'], feedback: 'The two messages tell the user whether they need to add a task or change the current filter.' },
  { slug: 'explain-acceptance', category: 'explanation', group: 'scope-test-flow', kind: 'conceptual', prompt: 'Why write a sequence such as add → complete → filter → delete before coding? A) it defines observable transitions to implement and test; B) it chooses CSS colors without discussing behavior.', answers: ['A'], feedback: 'A user flow turns requirements into observable state and view changes.' },
  { slug: 'explain-filter-no-mutation', category: 'explanation', group: 'scope-toggle-flow', kind: 'conceptual', prompt: 'Why should clicking Active avoid changing any task’s done flag? A) Active means every task must become incomplete; B) filtering selects records; toggling is a separate user action.', answers: ['B'], feedback: 'A view control must not silently perform a data mutation.' },
  { slug: 'apply-visible-filter', category: 'application', group: 'scope-filter-flow', kind: 'code', prompt: 'Complete the view projection for an Active filter: const visible = tasks.filter(task => filter === \'all\' ? true : ____); Answer with the expression.', answers: ['!task.done', 'task.done === false', 'task.done===false'], feedback: 'Active shows tasks whose done flag is false.' },
  { slug: 'apply-delete-by-id', category: 'application', group: 'scope-delete-flow', kind: 'code', prompt: 'Use a strict comparison to complete the transition that removes one selected record: const next = tasks.filter(task => task.id ____ id);', answers: ['!=='], feedback: 'Keep every record whose stable id does not equal the selected id.' },
  { slug: 'apply-empty-check', category: 'application', group: 'scope-empty-flow', kind: 'code', prompt: 'Assume `visible` is the already-filtered array passed to render. Complete the empty-state condition: const showEmpty = ____ === 0;', answers: ['visible.length'], feedback: 'The message should follow the number of rows in the current visible projection.' },
  { slug: 'apply-submit-boundary', category: 'application', group: 'scope-add-flow', kind: 'code', prompt: 'Complete the native form guard in the submit handler: event.____();', answers: ['preventDefault'], feedback: 'Prevent the browser navigation so the planned JavaScript transition can run.' },
  { slug: 'apply-toggle-match', category: 'application', group: 'scope-toggle-flow', kind: 'code', prompt: 'Complete the one-record toggle branch: task.id === id ? { ...task, done: ____ } : task', answers: ['!task.done', 'task.done === false', 'task.done===false'], feedback: 'Negating the matching record’s existing flag toggles it while preserving every other field.' },
  { slug: 'apply-flow-count', category: 'application', group: 'scope-test-flow', kind: 'conceptual', prompt: 'A flow test adds A and B, completes A, then selects Completed. How many visible rows should the test expect?', answers: ['1', 'one'], feedback: 'Only A satisfies the Completed filter after that sequence.' },
];

const stackQuestions: Spec[] = [
  { slug: 'module-script', category: 'prediction', group: 'stack-modules', kind: 'conceptual', prompt: 'index.html contains <script type="module" src="./src/main.js"></script>. What happens to main.js? A) the browser parses it as an ES module; B) the browser treats it as a classic script with no import/export support.', answers: ['A'], feedback: 'The module script enables import/export and resolves the source relative to index.html.' },
  { slug: 'relative-import', category: 'prediction', group: 'stack-paths', kind: 'code', prompt: 'main.js is in src/ and state.js is in src/model/. What exact relative specifier imports state.js?', answers: ['./model/state.js'], feedback: 'From src/main.js, descend into the model directory: ./model/state.js.' },
  { slug: 'react-jsx-browser', category: 'prediction', group: 'stack-tradeoffs', kind: 'conceptual', prompt: 'A plain browser page loads app.jsx directly with no build step. Will JSX syntax run as written?', answers: ['no'], feedback: 'JSX needs a transform/runtime setup; plain browser files can use regular JavaScript directly.' },
  { slug: 'vite-role', category: 'prediction', group: 'stack-vite', kind: 'conceptual', prompt: 'A Vite vanilla project is built for deployment. Which artifact should a static host receive? A) the generated build output; B) the unbuilt source tree only.', answers: ['A'], feedback: 'The build output contains browser-ready assets and should be the deployed static site.' },
  { slug: 'storage-boundary', category: 'prediction', group: 'stack-boundary', kind: 'conceptual', prompt: 'A browser-only Todo app calls a server endpoint to save a task. Is that within this project’s chosen capability boundary?', answers: ['no'], feedback: 'This project is scoped to local browser execution; server endpoints and real APIs are outside the boundary.' },
  { slug: 'file-responsibility', category: 'prediction', group: 'stack-files', kind: 'conceptual', prompt: 'In a plan that separates state.js, render.js, and main.js, which file should own the current task array? A) render.js; B) state.js.', answers: ['B'], feedback: 'State belongs in the state module; rendering reads it and main wires user events.' },
  { slug: 'debug-import-directory', category: 'debugging', group: 'stack-paths', kind: 'code', prompt: 'render.js is at src/dom/render.js and state.js is at src/state/state.js. Complete the specifier: import { getTasks } from \'____\';', answers: ['../state/state.js'], feedback: 'From src/dom/render.js, move up to src, then enter state/state.js.' },
  { slug: 'debug-jsx-plain', category: 'debugging', group: 'stack-tradeoffs', kind: 'conceptual', prompt: 'The browser reports “Unexpected token <” in app.jsx loaded as a normal script. Choose the repair: A) add a JSX build/transformation setup; B) add more CSS.', answers: ['A'], feedback: 'The parser error comes from JSX in a runtime that expects JavaScript; CSS cannot transform it.' },
  { slug: 'debug-css-relative', category: 'debugging', group: 'stack-paths', kind: 'conceptual', prompt: 'index.html moved into public/ and the stylesheet link still says href="styles.css" while styles.css is in src/. Choose the repair: A) correct the relative path from public/index.html; B) add a second stylesheet with any name.', answers: ['A'], feedback: 'The reference location changed; asset links must point from index.html to the actual stylesheet location.' },
  { slug: 'debug-vite-source-host', category: 'debugging', group: 'stack-vite', kind: 'conceptual', prompt: 'A static host serves Vite’s src/index.html and shows unresolved module code. Choose the repair: A) deploy the generated build directory; B) rename the HTML heading.', answers: ['A'], feedback: 'Vite transforms and bundles source during its build; the host needs that generated output.' },
  { slug: 'debug-circular-ownership', category: 'debugging', group: 'stack-files', kind: 'conceptual', prompt: 'state.js imports render.js to redraw, and render.js imports state.js to read tasks. Which design repair fits the plan? A) let event wiring call the state transition, then render; B) keep both imports and add a third redraw call.', answers: ['A'], feedback: 'State should expose transitions; the event wiring can call the transition and then render without a state/render cycle.' },
  { slug: 'debug-external-package', category: 'debugging', group: 'stack-boundary', kind: 'conceptual', prompt: 'A starter imports a package from a public CDN, but the runtime forbids external network requests. Choose the repair: A) use the planned local files and bundled choices; B) add three more CDN URLs.', answers: ['A'], feedback: 'The bounded lesson cannot rely on external packages or network access.' },
  { slug: 'explain-plain-choice', category: 'explanation', group: 'stack-tradeoffs', kind: 'conceptual', prompt: 'Why is plain HTML/CSS/JavaScript a suitable choice for this small Todo? A) it keeps the runtime and file plan small; B) it provides server routing automatically.', answers: ['A'], feedback: 'Plain files fit a small browser app; they do not provide server routing.' },
  { slug: 'explain-vite-choice', category: 'explanation', group: 'stack-vite', kind: 'conceptual', prompt: 'What does Vite add to a vanilla project? A) a database and account system; B) a development/build workflow.', answers: ['B'], feedback: 'Vite improves local development and produces deployable assets; it does not add a backend.' },
  { slug: 'explain-react-tradeoff', category: 'explanation', group: 'stack-tradeoffs', kind: 'conceptual', prompt: 'What is a real tradeoff of choosing React for this small app? A) component conventions and tooling add setup; B) React removes the need to understand state transitions.', answers: ['A'], feedback: 'React can help at larger UI scale, but its build/runtime choices add concepts for this small browser app.' },
  { slug: 'explain-relative', category: 'explanation', group: 'stack-paths', kind: 'conceptual', prompt: 'Why should module imports use paths relative to the importing file? A) relative paths upload files to a server; B) the browser resolves those files from the module location.', answers: ['B'], feedback: 'A relative specifier describes the file relationship in the project; it does not imply a server upload.' },
  { slug: 'explain-separation', category: 'explanation', group: 'stack-files', kind: 'conceptual', prompt: 'Why separate state, DOM rendering, and event wiring into modules? A) each boundary has a clear responsibility; B) separate files make every function asynchronous.', answers: ['A'], feedback: 'Clear module boundaries make transitions and rendering easier to reason about and test.' },
  { slug: 'explain-static-boundary', category: 'explanation', group: 'stack-boundary', kind: 'conceptual', prompt: 'Why record “static browser app” in the project plan? A) it guarantees every browser has the same screen size; B) it prevents accidental dependence on servers, APIs, or accounts.', answers: ['B'], feedback: 'An explicit boundary keeps implementation and deployment expectations aligned.' },
  { slug: 'apply-export', category: 'application', group: 'stack-modules', kind: 'code', prompt: 'Complete the declaration so another file can import the transition: ____ function addTask(tasks, text) { return tasks; }', answers: ['export'], feedback: 'The export keyword makes the named function available to another module.' },
  { slug: 'apply-import-path', category: 'application', group: 'stack-modules', kind: 'code', prompt: 'model.js exports function addTask, but main.js needs to call it as createTask. Complete the named-import alias: import { addTask ____ createTask } from \'./model.js\';', answers: ['as'], feedback: 'The as keyword aliases a named export locally without changing the exported name.' },
  { slug: 'apply-module-script', category: 'application', group: 'stack-modules', kind: 'code', prompt: 'Complete the HTML script tag needed for import/export: <script ____ src="./src/main.js"></script>', answers: ['type="module"', "type='module'"], feedback: 'type="module" tells the browser to parse the file as an ES module.' },
  { slug: 'apply-file-boundary', category: 'application', group: 'stack-files', kind: 'conceptual', prompt: 'A click handler needs to update tasks and redraw. Which module sequence fits the plan? A) render writes source state directly; B) main calls state transition, then render.', answers: ['B'], feedback: 'Event wiring coordinates state transitions and rendering; render should project state.' },
  { slug: 'apply-static-choice', category: 'application', group: 'stack-boundary', kind: 'conceptual', prompt: 'A learner asks where to deploy this browser-only app. Which answer matches the plan? A) a static host serving HTML, CSS, JavaScript, and assets; B) a payment server with a database.', answers: ['A'], feedback: 'The app needs static files only within the current scope.' },
  { slug: 'apply-react-scope', category: 'application', group: 'stack-tradeoffs', kind: 'conceptual', prompt: 'A requirement is “one small Todo page with no shared component library.” Which stack choice best matches the stated scope? A) plain HTML, CSS, and JavaScript; B) React plus a component library and router.', answers: ['A'], feedback: 'Plain browser files meet this narrow scope with the fewest setup dependencies.' },
];

const setupQuestions: Spec[] = [
  { slug: 'label-association', category: 'prediction', group: 'setup-accessibility', kind: 'conceptual', prompt: 'A label has for="task-input" and the input has id="task-input". Clicking the label focuses the input: yes or no?', answers: ['yes'], feedback: 'Matching label for and input id values create the accessible association and click target.' },
  { slug: 'form-submit', category: 'prediction', group: 'setup-form', kind: 'conceptual', prompt: 'The add control is a submit button inside a form. When the user presses Enter in the input, should the form submit handler run?', answers: ['yes'], feedback: 'A semantic form supports keyboard submission through its submit event.' },
  { slug: 'button-default', category: 'prediction', group: 'setup-form', kind: 'conceptual', prompt: 'A “Clear filter” button inside the add form has no type attribute. What native behavior may occur when clicked? A) form submission; B) no form behavior in every browser.', answers: ['A'], feedback: 'A button inside a form defaults to submit unless its type is explicitly button.' },
  { slug: 'live-status', category: 'prediction', group: 'setup-feedback', kind: 'conceptual', prompt: 'A feedback element has role="status" and aria-live="polite". When its text changes, should assistive technology be notified?', answers: ['yes'], feedback: 'The live region communicates dynamic feedback without moving keyboard focus.' },
  { slug: 'list-semantics', category: 'prediction', group: 'setup-layout', kind: 'conceptual', prompt: 'The task collection contains three rows, each represented by an li inside a ul. How many list items should the DOM contain?', answers: ['3', 'three'], feedback: 'Each task maps to one li, so the list contains three items.' },
  { slug: 'flex-wrap', category: 'prediction', group: 'setup-layout', kind: 'conceptual', prompt: 'A filter toolbar uses display:flex and flex-wrap:wrap. On a narrow viewport, may its controls move onto another line instead of overflowing?', answers: ['yes'], feedback: 'flex-wrap permits flex items to move to additional lines when the row becomes too narrow.' },
  { slug: 'debug-label-id', category: 'debugging', group: 'setup-accessibility', kind: 'conceptual', prompt: 'Clicking the “Task” label does not focus the field because label for="task" while input id="task-input". Choose the repair: A) make both values task-input; B) add a second heading.', answers: ['A'], feedback: 'The label’s for value must exactly match the input id.' },
  { slug: 'debug-button-submit', category: 'debugging', group: 'setup-form', kind: 'conceptual', prompt: 'Clicking a filter button reloads the page. Which repair is appropriate when it sits inside the add form? A) set type="button"; B) set type="submit".', answers: ['A'], feedback: 'A filter control is not an add submission, so type="button" prevents native submission.' },
  { slug: 'debug-script-path', category: 'debugging', group: 'setup-files', kind: 'code', prompt: 'index.html is at the project root and main.js is in src/. Complete the tag: <script type="module" src="____"></script>', answers: ['./src/main.js'], feedback: 'The module path is relative to the root HTML file.' },
  { slug: 'debug-hidden-feedback', category: 'debugging', group: 'setup-feedback', kind: 'conceptual', prompt: 'Invalid input sets error.textContent but the error is never announced because the element remains aria-hidden="true". Choose the repair: A) remove or toggle aria-hidden when an error exists; B) leave it hidden and rely on color alone.', answers: ['A'], feedback: 'Visible, meaningful error feedback must be exposed to assistive technology.' },
  { slug: 'debug-list-wrapper', category: 'debugging', group: 'setup-layout', kind: 'conceptual', prompt: 'The renderer appends li elements directly to a div, while CSS and keyboard expectations target a ul. Which repair fits the layout contract? A) render the li elements inside a ul; B) keep the div and add more margin.', answers: ['A'], feedback: 'The DOM structure and semantic element must match the planned list contract.' },
  { slug: 'debug-css-selector', category: 'debugging', group: 'setup-layout', kind: 'conceptual', prompt: 'The stylesheet defines .task-list but the HTML uses class="tasks-list". Why is the list style missing? A) the class names do not match; B) the browser delays every class rule until JavaScript runs.', answers: ['A'], feedback: 'CSS class selectors are exact; the HTML and stylesheet must use the same class name.' },
  { slug: 'explain-semantic-form', category: 'explanation', group: 'setup-form', kind: 'conceptual', prompt: 'Why use a form around task input and add controls? A) it forces the browser to call a remote server; B) it gives submit behavior and keyboard support.', answers: ['B'], feedback: 'A form is a useful semantic interaction boundary; preventDefault keeps this flow in the browser.' },
  { slug: 'explain-label', category: 'explanation', group: 'setup-accessibility', kind: 'conceptual', prompt: 'Why pair a visible label with the task input? A) users and assistive technology can identify the control; B) labels automatically save tasks.', answers: ['A'], feedback: 'A label communicates purpose and enlarges the click target; it does not persist data.' },
  { slug: 'explain-heading', category: 'explanation', group: 'setup-layout', kind: 'conceptual', prompt: 'Why establish a heading hierarchy before styling? A) heading levels set JavaScript variable scope; B) it gives the page structure and a navigable outline.', answers: ['B'], feedback: 'Semantic headings organize the page for scanning and assistive navigation.' },
  { slug: 'explain-live-region', category: 'explanation', group: 'setup-feedback', kind: 'conceptual', prompt: 'Why use a live region for an input error? A) the changed message can be announced without forcing focus away; B) it makes invalid input valid.', answers: ['A'], feedback: 'A live region communicates dynamic status while preserving the user’s position in the form.' },
  { slug: 'explain-layout-css', category: 'explanation', group: 'setup-layout', kind: 'conceptual', prompt: 'Why keep layout in CSS instead of calculating pixel positions in event handlers? A) CSS can call storage APIs; B) layout remains declarative and responsive.', answers: ['B'], feedback: 'CSS expresses presentation across viewport sizes; event handlers should manage behavior.' },
  { slug: 'explain-focus', category: 'explanation', group: 'setup-accessibility', kind: 'conceptual', prompt: 'Why avoid moving focus after every successful add? A) the user can continue editing predictably; B) focus movement is required to create a list item.', answers: ['A'], feedback: 'Focus should move only when the interaction needs it; unnecessary movement disrupts keyboard users.' },
  { slug: 'apply-label-for', category: 'application', group: 'setup-accessibility', kind: 'code', prompt: 'Complete the association: <label ____="task-input">Task</label>', answers: ['for'], feedback: 'The label uses the for attribute to point at the input id.' },
  { slug: 'apply-input-id', category: 'application', group: 'setup-accessibility', kind: 'conceptual', prompt: 'Two separate forms both use id=task-input and label for=task-input. Choose a repair: A) give each input a unique id and update its own label for value; B) keep duplicate ids and change only the label text.', answers: ['A'], feedback: 'A for association identifies an element by id; unique ids avoid two labels pointing at the same control.' },
  { slug: 'apply-live-aria', category: 'application', group: 'setup-feedback', kind: 'code', prompt: 'The requirement is to announce the task count without interrupting current speech. Complete: <p id="task-count" aria-live="____"></p>', answers: ['polite'], feedback: 'polite queues the update without the interruption behavior of assertive.' },
  { slug: 'apply-button-type', category: 'application', group: 'setup-form', kind: 'code', prompt: 'Complete the filter control so it cannot submit the add form: <button type="____">Active</button>', answers: ['button'], feedback: 'type="button" gives this control button behavior rather than submit behavior.' },
  { slug: 'apply-list-element', category: 'application', group: 'setup-layout', kind: 'code', prompt: 'Complete the unordered semantic task container: <____ id="task-list"></____>', answers: ['ul'], feedback: 'A ul is the container for a collection of unordered task items.' },
  { slug: 'apply-module-src', category: 'application', group: 'setup-files', kind: 'conceptual', prompt: 'A module script appears in the document head and immediately queries the form that follows in the body. Which statement is correct? A) module scripts are deferred until HTML parsing is complete; B) module scripts always run before the body is parsed.', answers: ['A'], feedback: 'Module scripts are deferred by default, so the parsed body is available when the module executes.' },
];

const filterQuestions: Spec[] = [
  { slug: 'active-visible', category: 'prediction', group: 'filter-projection', kind: 'conceptual', prompt: 'Tasks are A(done false), B(done true), and C(done false). Under Active, how many rows render?', answers: ['2', 'two'], feedback: 'Active includes records with done false, so A and C render.' },
  { slug: 'completed-visible', category: 'prediction', group: 'filter-projection', kind: 'conceptual', prompt: 'Tasks are A(done false), B(done true), and C(done true). Under Completed, which labels render in order?', answers: ['B, C', 'B and C'], feedback: 'Completed selects done true and preserves source order.' },
  { slug: 'spaces-rejected', category: 'prediction', group: 'filter-validation', kind: 'conceptual', prompt: 'The raw input is "  \t ". After trim(), is it valid task text?', answers: ['no', 'invalid'], feedback: 'Trimming yields an empty string, so the submission is invalid.' },
  { slug: 'no-match-message', category: 'prediction', group: 'filter-empty', kind: 'conceptual', prompt: 'Two tasks exist, both completed, and Active is selected. Should the message say “No tasks yet” or “No active tasks”?', answers: ['No active tasks'], feedback: 'Source state is nonempty; only the Active projection is empty.' },
  { slug: 'error-cleared-valid', category: 'prediction', group: 'filter-feedback', kind: 'conceptual', prompt: 'An invalid submission displays an error. The next submission is valid. Should the old error message remain visible?', answers: ['no'], feedback: 'A successful submission clears stale validation feedback.' },
  { slug: 'filter-delete-source', category: 'prediction', group: 'filter-mutation', kind: 'conceptual', prompt: 'Under Completed, the user deletes B while A is hidden as Active. After deletion, should A still exist in source state?', answers: ['yes'], feedback: 'Deleting one selected record must preserve unrelated hidden records.' },
  { slug: 'debug-untrimmed', category: 'debugging', group: 'filter-validation', kind: 'conceptual', prompt: 'A spaces-only task is accepted because code tests if (!rawText) before trimming. Choose the repair: A) trim first, then test; B) trim only after creating the record.', answers: ['A'], feedback: 'Whitespace must be normalized before the empty check.' },
  { slug: 'debug-inverted-filter', category: 'debugging', group: 'filter-projection', kind: 'conceptual', prompt: 'The Active filter displays completed rows. Which predicate repairs it? A) !task.done; B) task.done.', answers: ['A'], feedback: 'Active means not done, so the predicate is !task.done.' },
  { slug: 'debug-stale-error', category: 'debugging', group: 'filter-feedback', kind: 'conceptual', prompt: 'The error remains after a valid add because code only assigns error.textContent in the invalid branch. What operation is missing in the valid branch?', answers: ['clear the error', 'set error.textContent to an empty string', 'error.textContent = \'\''], feedback: 'Successful validation should clear the prior message.' },
  { slug: 'debug-filter-mutation', category: 'debugging', group: 'filter-mutation', kind: 'conceptual', prompt: 'Clicking Completed changes every task’s done flag to true. Choose the repair: A) store filter separately and derive visible rows; B) mutate tasks when selecting a filter.', answers: ['A'], feedback: 'Filter selection is view state and must not mutate task completion.' },
  { slug: 'debug-empty-source', category: 'debugging', group: 'filter-empty', kind: 'conceptual', prompt: 'The app says “No active tasks” on first load even though there are zero source tasks. Which distinction is missing?', answers: ['check source emptiness before no-match emptiness', 'distinguish empty source from empty filtered view'], feedback: 'An empty source list deserves the initial empty message; a no-match message assumes records exist.' },
  { slug: 'debug-filtered-delete', category: 'debugging', group: 'filter-mutation', kind: 'conceptual', prompt: 'A delete handler calls tasks.splice(visibleIndex, 1) under a filter. What should it use instead?', answers: ['the matching stable id', 'delete by id'], feedback: 'The visible index does not identify the same position in source state after filtering.' },
  { slug: 'explain-derived', category: 'explanation', group: 'filter-projection', kind: 'conceptual', prompt: 'Why derive visible tasks on every render? A) it permanently removes hidden tasks; B) it stays synchronized with the latest task and filter state.', answers: ['B'], feedback: 'A derived projection updates after every transition without discarding source records.' },
  { slug: 'explain-empty', category: 'explanation', group: 'filter-empty', kind: 'conceptual', prompt: 'Why give an empty filtered view its own message? A) it indicates storage is broken; B) it explains why no rows appear and what the user can change.', answers: ['B'], feedback: '“No active tasks” gives context about the selected view.' },
  { slug: 'explain-validation', category: 'explanation', group: 'filter-validation', kind: 'conceptual', prompt: 'Why trim before validation and storage? A) labels should not be created from accidental outer spaces; B) trim encrypts the task text.', answers: ['A'], feedback: 'Trimming normalizes accidental outer whitespace while preserving meaningful text inside.' },
  { slug: 'explain-error', category: 'explanation', group: 'filter-feedback', kind: 'conceptual', prompt: 'Why keep an error message in UI state or a controlled render path? A) errors should remain forever for debugging; B) it should appear and clear with the validation result.', answers: ['B'], feedback: 'Feedback describes the current validation result and should not become stale.' },
  { slug: 'explain-filter-control', category: 'explanation', group: 'filter-mutation', kind: 'conceptual', prompt: 'Why is filter selection separate from task records? A) the same records can be viewed as All, Active, or Completed; B) each filter needs a duplicate task array.', answers: ['A'], feedback: 'One source of truth supports reversible views and avoids duplicated task state.' },
  { slug: 'explain-invalid-preserve', category: 'explanation', group: 'filter-validation', kind: 'conceptual', prompt: 'Why preserve the prior task array after invalid input? A) invalid input should clear all completed work; B) a failed validation has no valid state transition.', answers: ['B'], feedback: 'Rejecting input should leave valid records and their completion state intact.' },
  { slug: 'apply-trim', category: 'application', group: 'filter-validation', kind: 'code', prompt: 'Complete the candidate normalization: const text = rawText.____();', answers: ['trim'], feedback: 'Trim outer whitespace before checking the candidate.' },
  { slug: 'apply-active', category: 'application', group: 'filter-projection', kind: 'code', prompt: 'Complete the Active predicate: const active = tasks.filter(task => ____);', answers: ['!task.done', 'task.done === false', 'task.done===false'], feedback: 'Active rows are incomplete records.' },
  { slug: 'apply-completed', category: 'application', group: 'filter-projection', kind: 'code', prompt: 'Complete the Completed predicate: const completed = tasks.filter(task => task.____);', answers: ['done'], feedback: 'Completed rows are records whose done flag is true.' },
  { slug: 'apply-error-clear', category: 'application', group: 'filter-feedback', kind: 'code', prompt: 'Complete the successful branch to clear a prior message: error.textContent = ____;', answers: ['\'\'', '""'], feedback: 'An empty string removes stale visible error text.' },
  { slug: 'apply-no-match', category: 'application', group: 'filter-empty', kind: 'conceptual', prompt: 'There are four source tasks but the selected projection contains none. Which message is correct? A) No tasks yet; B) No tasks match this filter.', answers: ['B'], feedback: 'The source is nonempty, so the message should describe the current filter having no matches.' },
  { slug: 'apply-preserve-source', category: 'application', group: 'filter-mutation', kind: 'code', prompt: 'Use a strict comparison to complete the immutable deletion predicate: const next = tasks.filter(task => task.id ____ selectedId);', answers: ['!=='], feedback: 'Keep all records except the one whose stable id was selected.' },
];

const storageQuestions: Spec[] = [
  { slug: 'missing-get', category: 'prediction', group: 'storage-read', kind: 'conceptual', prompt: 'await trainingStorage.getItem("tasks") produces null because no record exists. Should recovery use an empty task array?', answers: ['yes'], feedback: 'A missing local record is a normal first-run case and recovers to an empty array.' },
  { slug: 'valid-json', category: 'prediction', group: 'storage-json', kind: 'conceptual', prompt: 'The stored string is "[{\\"id\\":1,\\"text\\":\\"A\\",\\"done\\":false}]". After JSON.parse, is the result an array?', answers: ['yes'], feedback: 'The outer JSON value is an array, which can then undergo shape validation.' },
  { slug: 'malformed-json', category: 'prediction', group: 'storage-recovery', kind: 'conceptual', prompt: 'getItem returns "{broken". If parsing is inside try/catch, should the app keep running with an empty task array?', answers: ['yes'], feedback: 'Malformed saved text is a recoverable load failure; catch it and use a safe default.' },
  { slug: 'set-string', category: 'prediction', group: 'storage-write', kind: 'conceptual', prompt: 'Two saved snapshots are queued in order: first [A], then [A, B]. Both writes succeed and the second waits for the first. Which snapshot is stored at the end? A) [A]; B) [A, B].', answers: ['B'], feedback: 'Serializing writes preserves snapshot order, so the later [A, B] snapshot is stored last.' },
  { slug: 'remove-result', category: 'prediction', group: 'storage-write', kind: 'conceptual', prompt: 'After await trainingStorage.removeItem("tasks"), should the next getItem for that key return null?', answers: ['yes'], feedback: 'Removing the key makes the subsequent read report no saved value.' },
  { slug: 'local-scope', category: 'prediction', group: 'storage-boundary', kind: 'conceptual', prompt: 'A learner saves tasks with trainingStorage and opens the same lesson on another device. Should the data automatically appear there?', answers: ['no'], feedback: 'This capability is local to the browser training environment; it does not sync to an account or cloud.' },
  { slug: 'debug-parse-null', category: 'debugging', group: 'storage-read', kind: 'conceptual', prompt: 'loadTasks calls JSON.parse(await trainingStorage.getItem(key)) and later crashes when the read returns null because the result is not an array. Choose the repair: A) test for null before parsing; B) call .map on the parsed null value and ignore the error.', answers: ['A'], feedback: 'JSON.parse(null) returns null in JavaScript; guard the missing value before code expects an array.' },
  { slug: 'debug-uncaught-parse', category: 'debugging', group: 'storage-recovery', kind: 'conceptual', prompt: 'A malformed saved string breaks startup because JSON.parse is outside try/catch. Choose the repair: A) keep parse and validation outside recovery; B) put parse and shape validation inside try/catch.', answers: ['B'], feedback: 'Both parsing and shape validation can fail and should be contained by the recovery boundary.' },
  { slug: 'debug-shape', category: 'debugging', group: 'storage-json', kind: 'conceptual', prompt: 'Parsed data is { tasks: [...] }, but the renderer expects an array. Choose the validation: A) require Array.isArray(data); B) assume every parsed object is a task array.', answers: ['A'], feedback: 'Validate the top-level shape before treating the parsed value as the task array.' },
  { slug: 'debug-await-write', category: 'debugging', group: 'storage-write', kind: 'conceptual', prompt: 'The app calls trainingStorage.setItem(key, JSON.stringify(tasks)) without await, then immediately reports “Saved.” Choose the repair: A) await the storage promise before reporting success; B) report success immediately because the call was made.', answers: ['A'], feedback: 'Await the bounded storage operation before claiming the write completed.' },
  { slug: 'debug-cloud-claim', category: 'debugging', group: 'storage-boundary', kind: 'conceptual', prompt: 'A UI says “Synced to your account” after a trainingStorage write. Choose the repair: A) keep the sync claim; B) say the tasks were saved locally in this browser.', answers: ['B'], feedback: 'The capability is local and browser-only; it does not provide accounts or cloud synchronization.' },
  { slug: 'debug-wrong-key', category: 'debugging', group: 'storage-write', kind: 'conceptual', prompt: 'The writer uses key "tasks" while the loader uses "todo-tasks", so every reload appears empty. Choose the repair: A) use one stable key for reads and writes; B) use a random key on every load.', answers: ['A'], feedback: 'Reads, writes, and removal must use the same stable key.' },
  { slug: 'explain-boundary', category: 'explanation', group: 'storage-boundary', kind: 'conceptual', prompt: 'Why use trainingStorage instead of exposing the host app’s storage directly? A) it grants access to credentials and unrelated data; B) it gives learner code a narrow controlled capability.', answers: ['B'], feedback: 'The wrapper limits the surface available to learner code and keeps host storage isolated.' },
  { slug: 'explain-json', category: 'explanation', group: 'storage-json', kind: 'conceptual', prompt: 'Why call JSON.stringify before setItem? A) the boundary stores strings; B) stringify encrypts tasks for a server.', answers: ['A'], feedback: 'JSON serialization converts the array into the string form accepted by storage.' },
  { slug: 'explain-parse', category: 'explanation', group: 'storage-recovery', kind: 'conceptual', prompt: 'Why catch JSON parse and shape errors together? A) every parse error means the network is offline; B) saved data can be missing, malformed, or structurally wrong.', answers: ['B'], feedback: 'Recovery must handle local data problems without inventing a network dependency.' },
  { slug: 'explain-shape', category: 'explanation', group: 'storage-json', kind: 'conceptual', prompt: 'Why validate each task’s fields after Array.isArray? A) valid JSON can still contain the wrong data shape; B) arrays are always safe task records.', answers: ['A'], feedback: 'Parsing only proves syntax; field checks prove the value matches the application contract.' },
  { slug: 'explain-missing', category: 'explanation', group: 'storage-read', kind: 'conceptual', prompt: 'Why treat null from getItem as a normal first-run state? A) null means the learner typed invalid JSON; B) no saved record is expected before the first save.', answers: ['B'], feedback: 'Missing storage is distinct from malformed storage and should start an empty list.' },
  { slug: 'explain-recovery', category: 'explanation', group: 'storage-recovery', kind: 'conceptual', prompt: 'Why preserve a safe empty state after a load failure? A) the app remains usable and can replace bad saved data; B) the malformed value should be rendered as a task.', answers: ['A'], feedback: 'A recoverable fallback lets the learner continue while avoiding unsafe assumptions about saved data.' },
  { slug: 'apply-get', category: 'application', group: 'storage-read', kind: 'code', prompt: 'Complete the asynchronous read: const raw = ____ trainingStorage.getItem(KEY);', answers: ['await'], feedback: 'The bounded capability is asynchronous, so await its returned promise.' },
  { slug: 'apply-null', category: 'application', group: 'storage-read', kind: 'code', prompt: 'Complete the missing-value branch. The function must return a JavaScript array of task records: if (raw === null) return ____;', answers: ['[]'], feedback: 'A missing key recovers to the empty array value [].' },
  { slug: 'apply-parse', category: 'application', group: 'storage-json', kind: 'code', prompt: 'Complete the conversion from stored text: const data = JSON.____(raw);', answers: ['parse'], feedback: 'JSON.parse turns the stored string into a JavaScript value for validation.' },
  { slug: 'apply-array-check', category: 'application', group: 'storage-json', kind: 'code', prompt: 'Complete the top-level shape guard: if (!____(data)) return [];', answers: ['Array.isArray'], feedback: 'The persisted top-level value must be an array before task validation.' },
  { slug: 'apply-write', category: 'application', group: 'storage-write', kind: 'code', prompt: 'Complete the local save call: await trainingStorage.setItem(KEY, JSON.____(tasks));', answers: ['stringify'], feedback: 'Serialize the current task array to the string accepted by setItem.' },
  { slug: 'apply-remove', category: 'application', group: 'storage-write', kind: 'code', prompt: 'Complete the clear operation: await trainingStorage.____(KEY);', answers: ['removeItem'], feedback: 'removeItem deletes the saved local value for the stable key.' },
];

const testingQuestions: Spec[] = [
  { slug: 'add-test-result', category: 'prediction', group: 'testing-behavior', kind: 'conceptual', prompt: 'A behavior test starts empty, submits “A”, and reads the rendered list. What row count should it observe?', answers: ['1', 'one'], feedback: 'A valid add should produce one observable rendered row.' },
  { slug: 'invalid-test-result', category: 'prediction', group: 'testing-validation', kind: 'conceptual', prompt: 'A test has one existing task, submits whitespace, then reads the list. What count should it observe?', answers: ['1', 'one'], feedback: 'Invalid input must preserve the existing task and create no new row.' },
  { slug: 'toggle-test-result', category: 'prediction', group: 'testing-behavior', kind: 'conceptual', prompt: 'A test clicks the checkbox for an incomplete task once and then reads its checked property. What should it be?', answers: ['true'], feedback: 'One toggle changes the record from incomplete to complete and render reflects that state.' },
  { slug: 'relative-export', category: 'prediction', group: 'testing-export', kind: 'conceptual', prompt: 'The preserved source/index.html references ./main.js and source/main.js is included. Does moving the whole source folder preserve that relative file relationship?', answers: ['yes'], feedback: 'Relative paths travel with the project files and do not depend on the original folder.' },
  { slug: 'static-server', category: 'prediction', group: 'testing-deploy', kind: 'conceptual', prompt: 'The Todo uses only browser files and trainingStorage. Does its static deployment need a database server?', answers: ['no'], feedback: 'The scoped app has no server or database requirement; it can be served as static files.' },
  { slug: 'zip-entry', category: 'prediction', group: 'testing-export', kind: 'conceptual', prompt: 'A learner extracts the runnable project ZIP. Which file should be the obvious browser entry point?', answers: ['index.html'], feedback: 'A root index.html gives the exported static project a clear starting page.' },
  { slug: 'debug-implementation-test', category: 'debugging', group: 'testing-behavior', kind: 'conceptual', prompt: 'A test passes because it inspects a private variable, but the rendered row is missing. Choose the repair: A) assert observable DOM behavior; B) keep testing the private variable.', answers: ['A'], feedback: 'Behavior tests should verify what a user can observe, such as rows, labels, and checked properties.' },
  { slug: 'debug-selector-test', category: 'debugging', group: 'testing-behavior', kind: 'conceptual', prompt: 'The app renders li inside #task-list, but a test queries .task-item and reports zero rows. Choose the repair: A) make the test selector match the DOM contract; B) change the task text so the old selector finds it.', answers: ['A'], feedback: 'The test and implementation must agree on the explicitly planned observable selector.' },
  { slug: 'debug-await-test', category: 'debugging', group: 'testing-fixtures', kind: 'conceptual', prompt: 'A persistence test checks storage immediately after clicking Save, before the async write settles. Choose the repair: A) read storage immediately; B) await the save promise before asserting.', answers: ['B'], feedback: 'Await the async behavior before reading its result.' },
  { slug: 'debug-export-missing', category: 'debugging', group: 'testing-export', kind: 'conceptual', prompt: 'An editable source tree is exported without model.js. Which repair matches the export contract? A) include every original file under source/; B) omit imported source files because root index.html is compiled.', answers: ['A'], feedback: 'The root bundle can run alone, while source/ must preserve every original file for continued editing.' },
  { slug: 'debug-server-assumption', category: 'debugging', group: 'testing-deploy', kind: 'conceptual', prompt: 'Deployment instructions say to start a Node server, but the project has no server code and is scoped as static. Choose the repair: A) require a Node backend anyway; B) serve the generated static files with a static HTTP server.', answers: ['B'], feedback: 'Deployment instructions should match the browser-only artifact and its actual runtime needs.' },
  { slug: 'debug-flaky-test', category: 'debugging', group: 'testing-fixtures', kind: 'conceptual', prompt: 'A test relies on whichever tasks a previous test left in storage, so its count changes between runs. Choose the repair: A) reset to a known fixture before each case; B) accept either count.', answers: ['A'], feedback: 'Independent tests need deterministic starting data and should not inherit mutable state.' },
  { slug: 'explain-behavior', category: 'explanation', group: 'testing-behavior', kind: 'conceptual', prompt: 'Why test add, toggle, delete, and filter through the UI? A) clicking the UI proves every internal line executed; B) these are user-visible contracts.', answers: ['B'], feedback: 'Behavior tests protect observable requirements without coupling to private implementation details.' },
  { slug: 'explain-invalid-test', category: 'explanation', group: 'testing-validation', kind: 'conceptual', prompt: 'Why include a whitespace-only submission in the test plan? A) it checks whether CSS centers the form; B) it verifies the invalid-input boundary and preservation rule.', answers: ['B'], feedback: 'Invalid input is a defined behavior and should be protected by a regression test.' },
  { slug: 'explain-fixture', category: 'explanation', group: 'testing-fixtures', kind: 'conceptual', prompt: 'Why reset a deterministic fixture before each storage test? A) prior data should not change the result; B) fixtures make browser storage cloud-synced.', answers: ['A'], feedback: 'Known starting data makes failures reproducible and meaningful.' },
  { slug: 'explain-static', category: 'explanation', group: 'testing-deploy', kind: 'conceptual', prompt: 'Why can this project use static deployment? A) static hosting supplies a hidden database; B) HTML, CSS, JavaScript, and scoped local storage run in the browser.', answers: ['B'], feedback: 'The current scope has no server, payment, account, or real API dependency.' },
  { slug: 'explain-zip', category: 'explanation', group: 'testing-export', kind: 'conceptual', prompt: 'Why preserve relative paths in a runnable ZIP? A) extraction can happen in any folder while references still resolve; B) relative paths contact a remote package registry.', answers: ['A'], feedback: 'Relative references keep the exported file tree portable.' },
  { slug: 'explain-regression', category: 'explanation', group: 'testing-behavior', kind: 'conceptual', prompt: 'Why rerun earlier behavior checks after a later filter or storage change? A) a passing old test prevents all future bugs; B) shared transitions can regress.', answers: ['B'], feedback: 'A later feature can affect existing flows, so the earlier contract needs regression coverage.' },
  { slug: 'apply-count-test', category: 'application', group: 'testing-behavior', kind: 'code', prompt: 'Assume the tiny test helper `expect(actual).toBe(expected)` compares values. Complete the observable assertion after adding one task: expect(document.querySelectorAll(\'#task-list li\').____).toBe(1);', answers: ['length'], feedback: 'querySelectorAll returns a collection whose length is the rendered row count.' },
  { slug: 'apply-invalid-test', category: 'application', group: 'testing-validation', kind: 'code', prompt: 'Assume `expect(actual).toBe(expected)` compares values. Complete the preservation assertion after a whitespace submission: expect(document.querySelectorAll(\'#task-list li\').____).toBe(1);', answers: ['length'], feedback: 'The existing row remains and no blank row is created, so the rendered collection length stays one.' },
  { slug: 'apply-checkbox-test', category: 'application', group: 'testing-behavior', kind: 'code', prompt: 'Assume `expect(actual).toBe(expected)` compares values. After toggling the first visible task complete, observe its current checkbox: expect(document.querySelector(\'#task-list input[type="checkbox"]\').____).toBe(true);', answers: ['checked'], feedback: 'The checked property reports the current live checkbox state.' },
  { slug: 'apply-reset-fixture', category: 'application', group: 'testing-fixtures', kind: 'code', prompt: 'Complete the setup operation that removes saved test data: await trainingStorage.____(TEST_KEY);', answers: ['removeItem'], feedback: 'Clear the known key before the test so it begins from a deterministic state.' },
  { slug: 'apply-export-files', category: 'application', group: 'testing-export', kind: 'conceptual', prompt: 'This exporter writes a compiled runnable bundle at root index.html, preserves originals under source/, and adds README.md. Which ZIP contents match that contract? A) root index.html plus source/ originals and README.md; B) source/ originals only, with no runnable root page.', answers: ['A'], feedback: 'The root index.html is the compiled standalone bundle; source/ preserves editable originals for continued work.' },
  { slug: 'apply-static-check', category: 'application', group: 'testing-deploy', kind: 'conceptual', prompt: 'Before static deployment, which check best matches the scope? A) test payment credentials; B) open the built or exported index and exercise add, filter, persistence recovery, and reload.', answers: ['B'], feedback: 'Deployment verification should exercise the browser behaviors in scope.' },
];

const banks: Record<string, Spec[]> = {
  'todo-scope-and-user-flows': scopeQuestions,
  'todo-web-stack-and-file-plan': stackQuestions,
  'todo-setup-and-static-layout': setupQuestions,
  'todo-filter-empty-and-input-errors': filterQuestions,
  'todo-storage-and-recovery': storageQuestions,
  'todo-testing-and-export': testingQuestions,
};

/** Phase 3 Astra-reviewed banks: six distinct items in each reasoning category per topic. */
export function todoPhase3Questions(topicId: string): AssessmentQuestion[] {
  return bank(topicId, banks[topicId] ?? []);
}
