import type { Files } from '../contracts';
import type { Activity, Blank, Challenge, Topic } from './schema';
import { weatherQuestions } from './weatherQuestions';
import { weatherReferenceByTopic } from './weatherReferences';

const projectId = 'async-weather';
const conceptual = { trim: true as const, collapseWhitespace: true, caseSensitive: false, lineEndings: 'lf' as const };
const code = { trim: true as const, collapseWhitespace: false, caseSensitive: true, lineEndings: 'lf' as const };
type Detail = { title: string; summary: string; readings: [string, string, string]; objectives: [string, string]; steps: [string[], string[]]; examples: string[]; checks: string[]; debug: string; hints: string[] };

const details: Record<string, Detail> = {
  'weather-scope-and-data-contract': { title:'Scope and data contract', summary:'Define the weather lookup’s visible inputs, outcomes, and bounded fixture data before implementation.', readings:[
    'A weather lookup begins with a boundary. This app accepts one city, shows a city name, Celsius temperature, and condition, then explains why a lookup cannot produce a result. It does not silently invent weather, retain a search history, or need a secret key. A fixture is a known local response that makes the same action repeatable while you learn the interface contract.\n\nWrite the request as a trimmed city string of 2 to 80 characters. Write the successful response as { city, temperatureC, condition }. An unknown city becomes null; a service response can be unsuccessful; a network-like problem rejects. These distinctions give the renderer honest choices.',
    'A data contract describes the edge values too. Empty is a valid absence of weather, while malformed is an invalid response shape. Neither should be rendered as if it were successful. A response object has ok, status, and json(); json() is asynchronous because its body may still be read.\n\nName visible outcomes before code: invalid input leaves no old result, loading says work is underway, success shows all three fields, and failure gives a recovery-oriented message. Those sentences become behavior checks later.',
    'The fixture contract is deliberately reproducible: London is 18°C and Cloudy; Paris is 22°C and Clear. Error yields an HTTP-style 503 response, Offline rejects, and Empty or an unknown city resolves to null. The host blocks iframe networking, so a live service is an explicit capability choice rather than an accidental fetch.\n\nA good scope document says what the user can observe and what the app intentionally defers. That keeps the next module work focused.' ], objectives:['Publish the city and response contract beside the search shell.','Describe empty, error, malformed, and offline outcomes without pretending they are successes.'], steps:[['Add the lookup contract with one request rule and the three success fields.','Keep form#weather-form, input#city-input, p#weather-status, and div#weather-result visible.'],['Add the no-match, service-error, malformed-data, and offline cases to the contract.','Submit the form once and confirm it prevents browser navigation.']], examples:['London → London, 18°C, Cloudy.','An unknown city → a no-match message, not invented data.'], checks:['#weather-scope describes a bounded lookup and deterministic fixtures.','#weather-data-contract names city, temperatureC, and condition.'], debug:'The supplied plan loses the deterministic fixture boundary. Restore it and retain distinct no-match and failure outcomes.', hints:['A null response means “no record found”; it is not the same as a rejected Promise.','Write the visible result before deciding how a function will be named.'] },
  'weather-modules-and-request-stack': { title:'Modules and request stack', summary:'Separate markup, request normalization, and UI orchestration before connecting asynchronous data.', readings:[
    'For this small app, plain browser modules are the clearest default: index.html owns semantics, styles.css owns presentation, weather.js owns request and response normalization, and main.js owns DOM events and rendering. Vite with vanilla JavaScript provides a development and build workflow when the project needs it. React provides components and a state model that become useful for a larger shared interface, but adds JSX and tooling here.\n\nChoose plain modules for the learner app. The course host already compiles the files, so no package installation or terminal is required inside the preview.',
    'A request module should return normalized weather or throw a meaningful error. It should not query DOM nodes. main.js can call that module after a submit, update a loading message, then render the returned value. That direction avoids a circular dependency where a data helper tries to repaint the page.\n\nNamed imports form a stable boundary: export requestWeather from weather.js and import it with a relative path from main.js. Paths are resolved from the importing file, not from the page URL. Match filename case and include .js. A named alias uses import { requestWeather as lookup } from "./weather.js"; the exported name stays requestWeather.',
    'Debug boundaries one at a time. A missing export means a name mismatch; a missing module usually means the relative path is wrong. If an HTTP response has ok false, handle it before calling json. If normalized data is malformed, the module should reject it so the UI can state that the result cannot be trusted.\n\nAsynchrony comes next. Keep this topic about boundaries, not about a real request yet.' ], objectives:['Map semantic, visual, request, and rendering responsibilities to separate files.','Normalize a response-shaped value without moving DOM work into the request module.'], steps:[['Create weather.js for normalizeWeather and record the four file responsibilities.','Import the normalizer in main.js with a sibling relative path.'],['Keep all querySelector and event code in main.js.','Make malformed city, temperatureC, or condition values throw from weather.js.']], examples:['weather.js returns normalized data; main.js decides where it appears.','A missing ./weather.js path is fixed at the import, not with CSS.'], checks:['#weather-file-plan gives each of the four files its own responsibility.','weather.js exports a normalization boundary.'], debug:'The supplied file plan assigns visual styles to main.js. Restore its event and rendering responsibility.', hints:['Modules are a design boundary, not an excuse to split every line into a new file.','Keep the request module reusable by returning data instead of DOM nodes.'] },
  'weather-setup-and-search-form': { title:'Setup and search form', summary:'Build an accessible search shell and explicit fixture/live controls before requests are enabled.', readings:[
    'A form makes both Enter and the button use one submit path. Use label for="city-input" with input#city-input, form#weather-form, p#weather-status, and div#weather-result. Prevent the native submit because this browser app handles the result in place. A role=status and aria-live="polite" lets status changes be announced without moving focus.\n\nThe initial page can say “Enter a city to start.” It should not claim to be loading before the learner starts a lookup.',
    'The input rule belongs at the edge: trim whitespace, then accept only 2 through 80 characters. Invalid input keeps the form usable, clears any stale result, and explains the correction in #weather-status. A visible label is more reliable than using a placeholder as the only name.\n\nKeep result and status regions separate: status says what the app is doing; result holds the weather content.',
    'Fixture and live data require an explicit user choice. The app starts in fixture mode. A learner first checks the live opt-in control, then can choose Live in the select. If the host has not enabled a provider, setMode("live") rejects and the UI returns to Fixture with a useful note. The grader always injects fixtures and never permits a live request.\n\nThis is an accessibility and consent decision, not a networking workaround.' ], objectives:['Add the accessible search selector contract and input validation.','Make fixture the default and gate the live selection behind an explicit opt-in.'], steps:[['Add the label, form, status, and result regions with the required ids.','Prevent submit navigation and reject trimmed strings outside 2–80 characters.'],['Add a fixture/live select disabled until the learner checks an opt-in box.','Verify Fixture is selected initially and the mode selector enables only after opt-in; request wiring arrives in the fetch topic.']], examples:['Submitting “ L ” shows an input correction.','Fixture is selected until the learner chooses otherwise.'], checks:['The required form/input/status/result selectors exist and submit is prevented.','#weather-status is an accessible live status region.'], debug:'The supplied handler allows native form navigation. Prevent it while keeping the input validation.', hints:['A select value is not consent by itself; keep the opt-in action visible.','Use text content for feedback so it remains available to assistive technology.'] },
  'weather-promises-and-async-control-flow': { title:'Promises and async control flow', summary:'Trace pending, fulfilled, and rejected work with async/await before connecting fetch-like data.', readings:[
    'A Promise is a future result. It begins pending, then settles once as fulfilled or rejected. async/await makes that timeline readable: await pauses only the async function, not the whole page. Put await inside try/catch when a rejection needs a visible recovery path.\n\nBefore calling weatherApi, practice with a delayed local Promise. Set Loading before await, then render a preview value after fulfillment. This teaches the transition without introducing response objects yet.',
    'Do not place Loading after await: by then the work has already settled. Do not call a Promise’s properties as if it were weather data. Await the Promise, then use its value. A catch belongs around the awaited operation; it can say the preview failed and preserve a usable form.\n\nEach submit starts a new asynchronous job. The stale-response rule arrives later, so this topic only proves a single pending → fulfilled or rejected path.',
    'Trace one example: submit Paris; the status changes to Loading preview; the delayed Promise resolves; the result says Paris, 18°C, Preview; status says Preview loaded. The preview number is intentionally local, not an API claim.\n\nAn async function returns a Promise; return its value so callers can await it. Calling two helpers before awaiting starts both jobs; awaiting the first before calling the second makes them sequential. finally runs cleanup on either outcome and should not accidentally return a replacement value.\n\nWhen this timeline feels concrete, response.ok and response.json() are easier to place in the next topic.' ], objectives:['Show pending and fulfilled states around an awaited local Promise.','Handle a rejected Promise with a clear status rather than an uncaught error.'], steps:[['Create delayedPreview(city) with new Promise and a short timeout.','Set Loading before await and render only after it resolves.'],['Wrap await delayedPreview(city) in try/catch.','Keep 2–80 input validation before creating the Promise.']], examples:['Paris → Loading preview → Paris: 18°C, Preview.','A rejected preview → Preview failed.'], checks:['A valid submit visibly enters a loading state before rendering a preview.','Invalid input creates no preview result.'], debug:'The supplied code reports loaded while the Promise is pending. Restore Loading before the asynchronous boundary.', hints:['await produces the fulfilled value; it does not make every later line asynchronous.','Keep the status message close to the state transition it describes.'] },
  'weather-fetch-and-render': { title:'Fetch and render', summary:'Use the injected fetch-like API, check response status, normalize JSON, and render a successful weather result.', readings:[
    'weatherApi.fetch(city) is the bounded fetch-like contract for this app. It returns a Promise of a Response-like object with ok, status, and async json(). First await fetch. Then check response.ok. Only a successful response should proceed to await response.json().\n\nThe host’s Fixture mode returns London and Paris deterministically. That makes a successful rendering test repeatable without an external account or a key.',
    'json() is another asynchronous boundary. Normalize its returned value before rendering, then write city, temperatureC, and condition into #weather-result. Use textContent, not HTML injection, because data should be displayed literally. Validate temperatureC with Number.isFinite; zero Celsius is valid and must not be rejected by a truthiness check. Status can change from Loading to Weather loaded for London.\n\nError response handling and null results are introduced next; this increment focuses on a good response and its fields.',
    'Keep the code in the request module narrow: await weatherApi.fetch, reject !ok, await json, normalize. main.js starts the request and owns loading/render messages. This keeps the browser UI testable while the host supplies the deterministic capability.\n\nA real provider may use a different endpoint and schema. It must still be adapted to this same shape before the renderer sees it.' ], objectives:['Fetch fixture data through the request module and render London’s fields.','Reject a non-ok response before attempting to treat it as weather JSON.'], steps:[['Call window.weatherApi.fetch(city) in weather.js and await the response.','Throw for !response.ok; await json only for successful responses.'],['Normalize city, temperatureC, and condition.','Render London as 18°C and Cloudy after a loading status.']], examples:['London → “London: 18°C, Cloudy”.','A response with ok false is not a successful weather value.'], checks:['London produces its three visible weather fields.','The request boundary checks response.ok before using the body.'], debug:'The supplied request skips response.ok and renders a 503 as data. Restore the status check before json().', hints:['Fetching and reading JSON are two awaits.','Render the normalized object, not the raw response.'] },
  'weather-loading-empty-and-error-states': { title:'Loading, empty, and error states', summary:'Make loading, no-match, failed response, malformed data, and offline outcomes understandable.', readings:[
    'An async app is judged during waiting and failure as much as during success. Clear the old result and set Loading when each valid lookup begins. When the response normalizes to null, say no weather match was found. That is a valid empty result, so it should not use the same wording as a broken service.\n\nKeep the form active; a message should give the user a reason to try another city.',
    'Error is a resolved response with ok false and status 503. Offline is a rejected fetch Promise. Malformed is a successful response whose JSON cannot meet the contract. Catch these paths after normalization and show a clear unavailable or connection message. The UI should never render undefined°C or a guessed condition.\n\nClear #weather-result on a new request so stale content does not masquerade as current loading data.',
    'Fixtures make each state safe to practice: Empty returns null, Error returns 503, Offline rejects, and Malformed resolves the wrong shape. They are deliberately not interchangeable. Use one test city at a time and read the status after it settles.\n\nThe next topic addresses a different failure: an older request that finishes after a newer one.' ], objectives:['Render distinct loading, empty, response-error, malformed, and offline messages.','Prevent invalid or unavailable values from appearing as a successful result.'], steps:[['Clear the result and announce Loading before each valid request.','Render null as no match rather than an error.'],['Catch Error, Offline, and Malformed with a useful unavailable message.','Keep the form ready for the next city.']], examples:['Empty → “No weather match was found”.','Offline → “Weather could not load. Check your connection and try again.”'], checks:['Empty, Error, Malformed, and Offline leave no successful result text.','A loading message appears before a settled state.'], debug:'The supplied normalizer invents successful weather for null. Restore the no-match outcome.', hints:['Null is an expected result; a rejected Promise is an operation failure.','Clear old output at the start of a valid lookup.'] },
  'weather-stale-responses-and-validation': { title:'Stale responses and validation', summary:'Validate input without letting old work overwrite the latest visible state.', readings:[
    'A user can submit twice before the first Promise finishes. If Slow begins first and Fast begins second, Fast should remain on screen even when Slow finishes later. Keep a monotonically increasing request number. Capture it for each submit and render only if it still equals the newest request number.\n\nThis small rule solves a visible race without cancelling the old Promise. The old work may settle, but it no longer owns the page.',
    'Increment the request token before validating a submission. An invalid entry still creates no fetch, but it retires any earlier pending request so that a Slow completion cannot replace the visible correction. Trim, require 2 through 80 characters, clear old output, and explain the rule.\n\nUse the same newest-request guard in both try and catch. An older SlowError must not overwrite a newer Fast success with an error message.',
    'Exercise the fixture timeline: submit Slow (80 ms), immediately submit Fast (5 ms), then wait. The result must say Fast, 25°C, Clear. Repeat with SlowError then Fast: the later success must survive.\n\nA mode change also increments newest and clears pending UI. If you add finally cleanup, guard it with the same captured request identity.\n\nThe final topic turns these fixture cases into a compact smoke check and export handoff.' ], objectives:['Validate city input before issuing a request.','Keep Slow or SlowError from replacing the later Fast result.'], steps:[['Increment a request token before checking trimmed input, so an invalid submission retires old pending work.','Reject trimmed values below 2 or above 80 without calling weatherApi.fetch.'],['Capture the token and compare it after await in success and catch paths.','Test Slow → Fast, SlowError → Fast, and Slow → invalid input.']], examples:['Slow then Fast ends at Fast: 25°C, Clear.','“ x ” changes status but adds no API call and retires Slow.'], checks:['Invalid input makes no request.','A later Fast result survives a prior Slow or SlowError completion.'], debug:'The supplied code lacks the success-path request guard. Restore it so Slow cannot replace Fast, and retain the catch guard.', hints:['The “latest” value belongs to the UI, not the network.','Compare the captured token after every await that can settle late.'] },
  'weather-testing-and-export': { title:'Testing and export', summary:'Smoke-test real fixture behavior, document fixture/live boundaries, and prepare a reproducible handoff.', readings:[
    'A smoke test runs a small real workflow. Set a known fixture city through the actual form, wait for the DOM result, assert the visible output, and report pass only after the assertion. A message that simply prints “passed” is not evidence.\n\nThe weather fixture is ideal for this: London must render 18°C and Cloudy without the network. Test controls should leave the normal form usable afterward. Save and restore input, output, status, mode, opt-in, and control state. Refuse to start during a pending normal lookup; restoring a Loading snapshot after invalidating its request would strand the interface. Also assert invalid-input no-call and HTTP-error behavior.',
    'Test more than the happy path over time: invalid input should make no call, Empty should be distinct, Error and Offline should be honest, and Slow then Fast should end at Fast. Each test starts from a known fixture condition. The grader injects the same deterministic API before learner code, so grading never asks a third-party service for weather.\n\nA live mode remains an optional user-owned integration, enabled only by explicit host capability and learner opt-in.',
    'For export, keep index.html, styles.css, weather.js, and main.js together with relative paths. Document that Fixture mode is reproducible and that a live provider needs separate, deliberate configuration. The ZIP root index.html is a compiled snapshot with its fixture adapter. source/ preserves the exact editable files. Editing source/ does not rebuild the root: edit in Project Code and Export runnable ZIP again. Serve the extracted root with python -m http.server 8080; direct file opening can break browser modules. Optional Live uses Open-Meteo with GeoNames attribution; offline fixtures remain the default.\n\nThe export is a handoff, not an automatic publication or hidden network permission.' ], objectives:['Run a visible smoke assertion through the real fixture form.','Explain reproducible fixture export and the explicit live-provider boundary.'], steps:[['Add a smoke button that submits London through #weather-form and checks the visible DOM result.','Report an honest pass or failure message.'],['Document the four portable files and fixture default.','State that live data requires separate explicit provider configuration.']], examples:['Smoke: London renders “London: 18°C, Cloudy”.','Export: fixture default is reproducible; live is optional.'], checks:['#run-weather-smoke performs a real London fixture check.','The handoff text distinguishes fixture export from optional live configuration.'], debug:'The supplied smoke skips its London output assertion. Restore the assertion so wrong weather cannot pass.', hints:['A smoke check should exercise the form, not call a private helper only.','Keep exported module paths relative to the files that import them.'] },
};

const blanks: Record<string, Array<Omit<Blank, 'path'>>> = {
  'weather-scope-and-data-contract': [{id:'weather-scope-contract-null',kind:'conceptual',prompt:'An unknown city resolves to which explicit value: null or a made-up weather object?',acceptedAnswers:['null'],explanation:'null communicates that no match exists without pretending weather was found.',normalization:conceptual},{id:'weather-scope-contract-field',kind:'code',prompt:'Complete the normalized field name: { city, ____, condition }',acceptedAnswers:['temperatureC'],explanation:'temperatureC makes the displayed unit explicit in the data contract.',normalization:code}],
  'weather-modules-and-request-stack': [{id:'weather-modules-boundary',kind:'conceptual',prompt:'Which file should normalize response data without querying the DOM?',acceptedAnswers:['weather.js'],explanation:'weather.js owns the request/data boundary; main.js owns DOM work.',normalization:conceptual},{id:'weather-modules-import',kind:'code',prompt:'Complete the sibling import: import { requestWeather } from "____";',acceptedAnswers:['./weather.js'],explanation:'The request module is a sibling of main.js.',normalization:code}],
  'weather-setup-and-search-form': [{id:'weather-setup-accessibility',kind:'conceptual',prompt:'Which attribute connects the City label to input#city-input?',acceptedAnswers:['for'],explanation:'label for must exactly equal the input id.',normalization:conceptual},{id:'weather-setup-submit',kind:'code',prompt:'Complete the submit handler: event.____();',acceptedAnswers:['preventDefault'],explanation:'Preventing the native submit keeps the result in the browser app.',normalization:code}],
  'weather-promises-and-async-control-flow': [{id:'weather-promises-state',kind:'conceptual',prompt:'Before delayedPreview settles, is its Promise pending, fulfilled, or rejected?',acceptedAnswers:['pending'],explanation:'Pending is the state while the future value is still unavailable.',normalization:conceptual},{id:'weather-promises-await',kind:'code',prompt:'Complete: const weather = ____ delayedPreview(city);',acceptedAnswers:['await'],explanation:'await obtains the fulfilled preview value inside an async function.',normalization:code}],
  'weather-fetch-and-render': [{id:'weather-fetch-response',kind:'conceptual',prompt:'Should response.ok be checked before calling response.json()?',acceptedAnswers:['yes'],explanation:'An unsuccessful response must not be treated as successful weather data.',normalization:conceptual},{id:'weather-fetch-json',kind:'code',prompt:'Complete: const data = await response.____();',acceptedAnswers:['json'],explanation:'json() asynchronously reads the response body.',normalization:code}],
  'weather-loading-empty-and-error-states': [{id:'weather-states-empty',kind:'conceptual',prompt:'Does a null weather result mean no match or an HTTP 503?',acceptedAnswers:['no match'],explanation:'null is the expected no-match representation; 503 is a response failure.',normalization:conceptual},{id:'weather-states-clear',kind:'code',prompt:'Clear an old rendered result: result.____ = "";',acceptedAnswers:['textContent'],explanation:'Clearing textContent removes stale weather before a new request settles.',normalization:code}],
  'weather-stale-responses-and-validation': [{id:'weather-stale-latest',kind:'conceptual',prompt:'When Slow starts before Fast, which result should remain visible?',acceptedAnswers:['fast'],explanation:'The newest request owns the current UI result.',normalization:conceptual},{id:'weather-stale-guard',kind:'code',prompt:'Complete the stale guard: if (request !== ____) return;',acceptedAnswers:['newest'],explanation:'Compare the request captured at submit time with the current newest token.',normalization:code}],
  'weather-testing-and-export': [{id:'weather-testing-fixture',kind:'conceptual',prompt:'Why use the London fixture in a smoke test?',acceptedAnswers:['it is deterministic','deterministic'],explanation:'A deterministic fixture makes the visible expectation repeatable.',normalization:conceptual},{id:'weather-testing-assert',kind:'code',prompt:'Complete the smoke condition: if (!/London/.____(result.textContent)) throw new Error("missing");',acceptedAnswers:['test'],explanation:'RegExp.test checks the visible text before a pass is reported.',normalization:code}],
};
function path(topic:string, part:'activities'|'blanks'|'challenges', id:string) { return `projects/${projectId}/topics/${topic}/${part}/${id}`; }
function broken(topic:string, files:Files, kind:'apply'|'debug'|'combine'):Files {
  const next={...files};
  if(topic==='weather-scope-and-data-contract') {
    next['index.html']=next['index.html'].replace('deterministic fixtures', kind==='apply'?'unbounded live network':'unbounded live network');
  } else if(topic==='weather-modules-and-request-stack') {
    next['index.html']=next['index.html'].replace(kind==='apply'?'weather.js: request and response normalization':'main.js: form events, current request, and rendering', kind==='apply'?'weather.js: visual styles':'main.js: visual styles');
  } else if(topic==='weather-setup-and-search-form') {
    next['main.js']=next['main.js'].replace(kind==='debug'?'event.preventDefault()':'city.length >= 2 && city.length <= 80', kind==='debug'?'/* navigation defect */':'city.length >= 1');
  } else if(topic==='weather-promises-and-async-control-flow') {
    next['main.js']=next['main.js'].replace(kind==='combine'?"city === 'Offline' ? reject(new Error('preview offline'))":"status.textContent = 'Loading preview…';", kind==='combine'?"false ? reject(new Error('preview offline'))":"status.textContent = 'Preview loaded.';");
  } else if(topic==='weather-fetch-and-render') {
    if(kind==='apply') next['main.js']=next['main.js'].replace('weather.temperatureC', '999');
    else if(kind==='debug') next['weather.js']=next['weather.js'].replace('if (!response || !response.ok)', 'if (false)');
    else next['main.js']=next['main.js'].replace('weather.condition', "'Wrong'");
  } else if(topic==='weather-loading-empty-and-error-states') {
    next['weather.js']=next['weather.js'].replace('if (value === null) return null;', "if (value === null) return { city: 'Empty', temperatureC: 0, condition: 'Clear' };");
  } else if(topic==='weather-stale-responses-and-validation') {
    next['main.js']=next['main.js'].replace(kind==='apply'?'city.length >= 2 && city.length <= 80':'if (request !== newest) return;', kind==='apply'?'city.length >= 1':'');
  } else {
    next['main.js']=next['main.js'].replace(kind==='apply'?'const smoke =':'result.textContent !== \'London: 18°C, Cloudy\'', kind==='apply'?'const smoke = null;':'false');
  }
  return next;
}
function reading(topic:string,id:string,title:string,objective:string,explanation:string):Activity { return {id,path:path(topic,'activities',id),title,kind:'reading',order:0,objective,outline:explanation,estimatedMinutes:8,explanation,instructions:['Trace one user action from the input to a visible status or result.','Name the next state before changing files.'],hints:['Use the stated selector contract so later checks can observe the work.','Keep fixture behavior deterministic while learning.']}; }
function guided(topic:string,id:string,title:string,objective:string,explanation:string,reference:Files,starter:Files,checks:string[],steps:string[]):Activity { return {id,path:path(topic,'activities',id),title,kind:'guided-coding',order:0,objective,outline:explanation,estimatedMinutes:15,explanation,instructions:['Continue the existing weather project; do not replace compatible work with a blank page.',...steps,'Run the preview and perform the stated interaction before using Check.','Use Fixture mode for every guided check.'],starterFiles:starter,validation:{observable:objective,checks},hints:['Make the smallest change that changes a visible state.','Read status and result as separate outputs.'],referenceSolution:reference}; }
function challenges(id:string, detail:Detail, reference:Files):Challenge[] { return (['apply','debug','combine'] as const).map((kind,index)=>({id:`${id}-${kind}`,path:path(id,'challenges',`${id}-${kind}`),title:index===0?'Apply the first increment':index===1?'Repair a regression':'Combine the complete feature',order:index+1,objective:index===0?detail.objectives[0]:index===1?detail.debug:detail.summary,starterFiles:broken(id,reference,kind),instructions:[index===0?'Apply the first guided increment in this separate draft.':index===1?detail.debug:'Implement the complete topic behavior independently while preserving prior selector and fixture contracts.',...(index===0?detail.steps[0]:detail.steps[1]),'Run the stated example, then Check challenge.'],examples:index===0?detail.examples.slice(0,1):detail.examples,behaviorValidation:{observable:index===0?detail.objectives[0]:detail.summary,checks:index===0?detail.checks.slice(0,1):detail.checks},hints:detail.hints,reference:[`${id}-read-1`,`${id}-guided-1`,`${id}-read-2`,`${id}-guided-2`,`${id}-read-3`],referenceSolution:reference})); }
function topic(id:string,order:number,prerequisiteTopicIds:string[]):Topic { const detail=details[id], reference=weatherReferenceByTopic[id]; const activities=[reading(id,`${id}-read-1`,`${detail.title}: understand the contract`,detail.objectives[0],detail.readings[0]),guided(id,`${id}-guided-1`,`${detail.title}: first increment`,detail.objectives[0],detail.readings[0],reference,broken(id,reference,'apply'),detail.checks.slice(0,1),detail.steps[0]),reading(id,`${id}-read-2`,`${detail.title}: trace the transition`,detail.objectives[1],detail.readings[1]),guided(id,`${id}-guided-2`,`${detail.title}: verify and repair`,detail.objectives[1],detail.readings[1],reference,broken(id,reference,'debug'),detail.checks,detail.steps[1]),reading(id,`${id}-read-3`,`${detail.title}: prepare independent work`,detail.summary,detail.readings[2])].map((activity,index)=>({...activity,order:index+1})); const topicBlanks=blanks[id].map(blank=>({...blank,path:path(id,'blanks',blank.id)})); return {id,path:`projects/${projectId}/topics/${id}`,projectId,title:detail.title,order,status:'published',summary:detail.summary,prerequisiteTopicIds,activities,blanks:topicBlanks,assessmentQuestions:weatherQuestions(id),challenges:challenges(id,detail,reference),gate:{type:'topic-gate',guidedActivityIds:[`${id}-guided-1`,`${id}-guided-2`],requiredChallengeIds:[`${id}-apply`,`${id}-debug`,`${id}-combine`],minimumDistinctCorrectQuestionIds:10,revealedAnswerEarnsCredit:false,requiresFreshEquivalentAfterReveal:true,wrongAnswerResetsProgress:false,retryPolicy:'exhaust-unseen-before-missed'}}; }

export const weatherTopics: Topic[] = [
  topic('weather-scope-and-data-contract',1,[]),
  topic('weather-modules-and-request-stack',2,['weather-scope-and-data-contract']),
  topic('weather-setup-and-search-form',3,['weather-modules-and-request-stack']),
  topic('weather-promises-and-async-control-flow',4,['weather-setup-and-search-form']),
  topic('weather-fetch-and-render',5,['weather-promises-and-async-control-flow']),
  topic('weather-loading-empty-and-error-states',6,['weather-fetch-and-render']),
  topic('weather-stale-responses-and-validation',7,['weather-loading-empty-and-error-states']),
  topic('weather-testing-and-export',8,['weather-stale-responses-and-validation']),
];
